### ISSUE TITLE
Cant find my project at firebase init

### ISSUE THREAD

**Issue by alon359** [firebase/firebase-tools#1154]
Hi,
I try Firebase Init and when i get to the step when i need to select the default Firebase project
i can't see my projects although i have a few...
How can i resolve this?
thanks
<img width="580" alt="pic" src="https://user-images.githubusercontent.com/38526461/53245905-d4494f00-36b7-11e9-918a-5d4a1f863fc7.png">

**Comment by Memeriaj** [comment]
None of your projects are showing up?  Are you logged into the CLI with the same Google account that you're viewing the Firebase Console with?

**Comment by alon359** [comment]
i'm with cli and can't find my project look at the image

‫בתאריך יום ו׳, 22 בפבר׳ 2019 ב-21:59 מאת ‪Alex Memering‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by bkendall** [comment]
@alon359 - the question is: are _any_ projects showing up in this list?

Could you also confirm that the account with which you are logged into the CLI (verify using `firebase login` - it will print the email address) the same as the one you've created the projects with in the Firebase Console?

**Comment by nephix** [comment]
I'm having the same issue
> the question is: are _any_ projects showing up in this list?
Yes, I two of my (older) projects show up. My newly created one doesn't when I run `firebase init`. The newly created one is listed when I run `firebase list` though.
> Could you also confirm that the account with which you are logged into the CLI the same as the one you've created the projects with in the Firebase Console?
It's the same account in my case. I also did 
```
$ firebase logout
$ firebase login
```
to make sure it's not a permission issue.

**Comment by nephix** [comment]
Looks like `firebase-tools/src/firebaseApi.js:8` (which is used when running `$ firebase init`) uses:
```
`/${API_VERSION}/projects?page_size=100`
```
with `API_VERSION` being `v1beta1`, while `firebase-tools/src/api.js:237` (which is used by `$ firebase list`) uses:
```
"/v1/projects"
```
which could mean the issue is in the API version `v1beta1`, I'm not very familiar with these API versions though.

**Comment by alon359** [comment]
> 
> 
> @alon359 - the question is: are _any_ projects showing up in this list?
> 
> Could you also confirm that the account with which you are logged into the CLI (verify using `firebase login` - it will print the email address) the same as the one you've created the projects with in the Firebase Console?

Yes i use an account with firebase projects...

**Comment by alon359** [comment]
I have still the some problem...

**Comment by alon359** [comment]
> 
> 
> I'm having the same issue
> 
> > the question is: are _any_ projects showing up in this list?
> 
> Yes, two of my (older) projects show up. My newly created one doesn't when I run `firebase init`. The newly created one is listed when I run `firebase list` though.
> 
> > Could you also confirm that the account with which you are logged into the CLI the same as the one you've created the projects with in the Firebase Console?
> 
> It's the same account in my case.
> I also did:
> 
> ```
> $ firebase logout
> $ firebase login
> ```
> 
> to make sure it's not a permission issue.
> Also:
> 
> ```
> $ firebase --version
> 6.4.0
> $ npm -v
> 6.8.0
> $ node -v
> v10.15.1
> ```
> 
> if that helps.

Still have this problem

**Comment by nephix** [comment]
Seems to work now, was probably fixed in `/v1beta1/projects`

**Comment by bkendall** [comment]
@nephix I think you're intuition that the two API calls (`v1beta1` vs `v1`) may be causing the difference. I'm going to bring this up with the relevant folks and confirm what this should be.

**Comment by kevinwolfcr** [comment]
Still happening on `6.5.0`

Running `firebase list` returns the actual list of my projects, but `firebase init` only show me the option to don't set up a default project and create a new project.

**Comment by danhadzami** [comment]
I'm currently having this issue. Yesterday was totally fine. Now, my project is gone.

**Comment by aditmodhvadia** [comment]
Me too. Gives an error of lacking authorization.

**Comment by MrNomNom98** [comment]
Searched for the same issue a while and for me worked to add the created GCP project  on https://console.firebase.google.com to the firebase projects. Then u can go ahead with `firebase init` or `firebase -P <project-id> init` to create your firebase instance

**Comment by danieldanielecki** [comment]
It did happen to me when my project related to `Angular Universal` in conjunction with `Cloud Functions for Firebase` wasn't configured correctly.  `ng add @angular/fire` automatically fixed all the setup, and the error was gone.

**Comment by tatihub** [comment]
> Still happening on `6.5.0`
> 
> Running `firebase list` returns the actual list of my projects, but `firebase init` only show me the option to don't set up a default project and create a new project.
> ### Temporary workaround
> 
> Running `firebase init --project [a project id got from firebase list]` works fine.

I get firebase list is not a Firebase command. 

Why does every google product have issues like these?

**Comment by RoryKelly** [comment]
I had this issue because I have $FIREBASE_TOKEN set on my environment. It always overrode the login calls.

**Comment by bkendall** [comment]
So this is a pretty old issue, and the `projects:list` command seems to be working as expected for me these days. If this is still an issue, please let me know, otherwise I'm going to let this issue close.

**Comment by arnemolland** [comment]
Hitting this right now. Logged in and out several times, re-verified that the correct account is logged in, tried settings GOOGLE_APPLICATION_CREDENTIALS yet e.g. `firebase projects:list` yields
```
❯ firebase projects:list
✔ Preparing the list of your Firebase projects
No projects found.
```

while explicitly adding the `--project` flag seems to work, though I'm using FlutterFire (which uses the CLI under  the good, but retrieves projects through projects:list) in this case, meaning I cannot pass the flag successfully.

**Comment by overandeasy** [comment]
Had the same issue. `firebase init`, `firebase init firestore` and `firebase init functions` all got `Error: There are no Firebase projects associated with this account.` `firebase projects:list` returned `No projects found.` 
Tried using `firebase -P <project-id> init` and it did trick.

**Comment by nico-zensara** [comment]
Having the same issue. Logged out from an old account, logged in with a new account, and now I can't see any of my new projects. Tried everything outlined above to no avail.
