### ISSUE TITLE
Firestore emulator: Invalid project id causes "2 UNKNOWN" error

### ISSUE THREAD

**Issue by JakeHedman** [firebase/firebase-tools#1256]
### [REQUIRED] Environment info

**firebase-tools:** 6.9.0

**Platform:** Arch Linux

### [REQUIRED] Test case

```sh
firebase emulators:start --only firestore
# In second terminal:
env FIREBASE_FIRESTORE_EMULATOR_ADDRESS=localhost:5002 node -e "require('@firebase/testing').initializeTestApp({ projectId: 'invalid.project.id' }).firestore().doc('a/a').get().catch(console.error)"
```

### [REQUIRED] Steps to reproduce
0. Initialize a test app with `projectId: 'invalid.project.id'`
1. Get a document

### [REQUIRED] Expected behavior
Should give some useful error in the node exception or in the emulator.

### [REQUIRED] Actual behavior
The emulator gives no output, the node output is:
```
node:32271) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
[2019-05-08T06:12:23.964Z]  @firebase/firestore: Firestore (6.0.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=unknown]: 2 UNKNOWN: 
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
{ Error [FirebaseError]: Failed to get document because the client is offline.
    at new FirestoreError (xxx/node_modules/@firebase/firestore/dist/index.node.cjs.js:355:28)
    at Object.next (xxx/node_modules/@firebase/firestore/dist/index.node.cjs.js:20709:28)
    at next (xxx/node_modules/@firebase/firestore/dist/index.node.cjs.js:20662:30)
    at Timeout._onTimeout (xxx/node_modules/@firebase/firestore/dist/index.node.cjs.js:19011:21)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
  code: 'unavailable',
  name: 'FirebaseError',
  toString: [Function] }
```

### Run the command with --debug flag, and include the logs below.

```
[2019-05-08T06:16:55.714Z] ----------------------------------------------------------------------
[2019-05-08T06:16:55.717Z] Command:       /usr/bin/node /usr/bin/firebase emulators:start --only firestore --debug
[2019-05-08T06:16:55.717Z] CLI Version:   6.9.0
[2019-05-08T06:16:55.717Z] Platform:      linux
[2019-05-08T06:16:55.717Z] Node Version:  v11.15.0
[2019-05-08T06:16:55.717Z] Time:          Wed May 08 2019 08:16:55 GMT+0200 (Central European Summer Time)
[2019-05-08T06:16:55.717Z] ----------------------------------------------------------------------

[2019-05-08T06:16:55.725Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2019-05-08T06:16:55.726Z] > authorizing via signed-in user
[2019-05-08T06:16:55.727Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[2019-05-08T06:16:55.727Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[2019-05-08T06:16:55.855Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=utf-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Wed, 08 May 2019 06:16:55 GMT, server=scaffolding on HTTPServer2, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-05-08T06:16:55.870Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/xxx  
 
i  Starting emulators: ["firestore"]
[2019-05-08T06:16:56.796Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Wed, 08 May 2019 06:16:56 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, server-timing=gfet4t7; dur=870, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-05-08T06:16:56.824Z] Starting emulator firestore with args {"host":"localhost","port":5002,"rules":"firestore/firestore.rules"}
i  firestore: Logging to firestore-debug.log
[2019-05-08T06:16:57.534Z] API endpoint: http://
[2019-05-08T06:16:57.535Z] localhost:5002

[2019-05-08T06:16:57.536Z] If you are using a library that supports the FIRESTORE_EMULATOR_HOST environment variable, run:
[2019-05-08T06:16:57.536Z] 

   export FIRESTORE_EMULATOR_HOST=localhost:5002

Dev App Server is now running.


i  firestore: For testing set FIREBASE_FIRESTORE_EMULATOR_ADDRESS=localhost:5002
[2019-05-08T06:16:59.962Z] May 08, 2019 8:16:59 AM io.gapi.emulators.grpc.GrpcServer$3 operationComplete
INFO: Adding handler(s) to newly registered Channel.

[2019-05-08T06:16:59.969Z] May 08, 2019 8:16:59 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected HTTP/2 connection.

[2019-05-08T06:17:00.056Z] May 08, 2019 8:17:00 AM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: Invalid app id

[2019-05-08T06:17:00.073Z] May 08, 2019 8:17:00 AM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: Invalid app id
```

**Comment by samtstern** [comment]
Thanks @JakeHedman that seems like a bug in the emulator.

**Comment by samtstern** [comment]
@yuchenshi assigning Ryan's old bugs to you.

**Comment by itsravenous** [comment]
Just a note to say that I arrived here after getting the `UNKNOWN 2` error when connecting firebase-admin to my local emulator (well, actually the error only occurs when attempting to interact with the emulator, e.g. create a document in Firestore). I was using the project ID suggested in [the documentation](https://firebase.google.com/docs/emulator-suite/connect_firestore#admin_sdks) (`YOUR_PROJECT_ID`). Perhaps that snippet (and any others like it) should be updated to include a valid ID, and the description above it be reworded to explain that any _valid_ project ID may be used. Currently it reads:

>Note that you do not need to use your real Firebase project ID, the Cloud Firestore emulator will accept any project ID.

**Comment by strom2357** [comment]
Thanks for highlighting that, I've made a quick ticket to make sure the documentation there is up to date as you note.  Tracking here: b/177098348

**Comment by yuchenshi** [comment]
Documentation is fixed now! Thanks again for highlighting it, @itsravenous!

**Comment by ekselys** [comment]
Error still present by the way, it will be very handy if emulator could handle more project ids in parallel (also with its REST endpoints to clear firestore and sign in), expecially for CI contests where running tests in parallel is crucial.

Thanks for the hard work!
