### ISSUE TITLE
rawBody is empty when using the functions emulator

### ISSUE THREAD

**Issue by ghinda** [firebase/firebase-tools#1322]
`req.rawBody` is not available when using the functions emulator. It is available to deployed functions.

### Environment info

**firebase-tools:** 6.10.0
**Platform:** Manjaro

### Test case

```
exports.test = functions.https.onRequest((req, res) => {
  res.send(req.rawBody);
})
```

### Steps to reproduce

Check returned function response with `curl`:
```
curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST https://app/test
```

If running the function with the functions emulator:
```
firebase emulators:start --only functions
```
POSTing to the function will return an empty response.

POSTing to the deployed function will return:
```
{"key1":"value1", "key2":"value2"}
```

### Expected behavior

When running the function in the emulator, `req.rawBody` should contain the raw request body.

### Actual behavior

`req.rawBody` is empty when using the emulator.

### Related issues:

* https://github.com/googlearchive/cloud-functions-emulator/issues/161
* https://github.com/googlearchive/cloud-functions-emulator/issues/167
* https://github.com/firebase/firebase-functions/issues/417

**Comment by abeisgoat** [comment]
Thanks for the report, looks like we missed the middleware which populates `rawBody`. We'll get it sorted for the next point release.

**Comment by abeisgoat** [comment]
We can fix this by adding the same [`rawBodySaver`](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/76f134b275df73878c9f47e5a452158c764eb1b9/src/invoker.ts#L302) verification method to our [`body-parser configs`](https://github.com/firebase/firebase-tools/blob/master/src/emulator/functionsEmulatorRuntime.ts#L547)

**Comment by abeisgoat** [comment]
Fix has been merged into `next` branch so it'll go out with the `firebase-tools@7.0.0` release

**Comment by jdarpinian** [comment]
This is not fixed for me. `rawBody` is still missing in firebase-tools@7.12.1
