### ISSUE TITLE
[functions.config()] is EMPTY when running [firebase serve] or [firebase deploy] (using Node.js v10 function environment)

### ISSUE THREAD

**Issue by super-jb** [firebase/firebase-tools#1836]
### Related issues
I know some people have complained about this in the past but I can't seem to get this working.

### [REQUIRED] Version info

**node:** v10.15.0

**firebase-functions:** ^3.0.0

**firebase-tools:**

**firebase:** 7.3.2

**firebase-admin:** ^8.0.0

### [REQUIRED] Test case
running **firebase serve** fails to read **functions.config()**

### [REQUIRED] Steps to reproduce

I've tried:
* firebase functions:config:get > .runtimeconfig.json (creates the .json file with my expected config values)
* firebase functions:config:get | ac .runtimeconfig.json (creates the .json with NO config values, just empty .json) - so i have to manually set the file in this case
* I've tried putting the .runtimeconfig.json in the **functions** folder
* I've tried putting the .runtimeconfig.json in the **src** folder
* I've tried putting the .runtimeconfig.json in the **src** & the **functions** folder

### [REQUIRED] Expected behavior
Running **firebase serve** should read **functions.config()**

### [REQUIRED] Actual behavior
**functions.config()** seems to always be empty

This is the location that the code should read **functions.config()** values

 TypeError: Cannot read property 'secret' of undefined
    at Object.<anonymous> (C:\Development\stripe\functions\lib\config.js:13:49)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Development\stripe\functions\lib\source.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)

### Were you able to successfully deploy your functions?

No... running **firebase deploy --only functions** gives me the exact same error.
If I replace **functions.config().myValue** with **the actual** value, both **firebase serve** and **firebase deploy** work - but this isn't the intended behavior... I don't want my secret key value exposed in the code 

![image](https://user-images.githubusercontent.com/6843604/65738439-ae918780-e096-11e9-8bc1-6715b0989fc7.png)

**Comment by JFGHT** [comment]
In my case `firebase functions:config:get | ac .runtimeconfig.json` does generate a .runtimeconfig.json filled with all properties but still, the `serve` doesn't load them.

This only happens in Windows.

**Comment by samtstern** [comment]
Hmmm yeah I am seeing this too but interestingly I can fix it like this:
```
$ CLOUD_RUNTIME_CONFIG=$(pwd)/functions/.runtimeconfig.json firebase emulators:start
```

So I think there may be something going wrong in `firebase-functions`, but I will keep investigating.

**Comment by agrippanux** [comment]
@samtstern adding the CLOUD_RUNTIME_CONFIG fixed the issue for me.  Nothing else worked, no matter where I put the .runtimeconfig.json

**Comment by dominikfoldi** [comment]
I am on Windows 10 and I cannot make .runtimeconfig.json used nor by the functions emulator, nor by firebase serve.

**Comment by mariotacke** [comment]
Just ran into the same issue. It looks like it was introduced in `3.4.0`. I confirmed it working properly in `3.3.0`.

**Comment by mbleigh** [comment]
@mariotacke can you file a new issue in the `firebase-functions` repo with detailed information about the versions of `firebase-tools` and `firebase-functions` you're using (in addition to the node version specified in your package.json) and specific debug logs and output? I'm not able to reproduce.

**Comment by samtstern** [comment]
The fix has been released in `7.16.0`

**Comment by axx** [comment]
I have 7.16.1 and I still have the problem.

**Comment by liezl200** [comment]
This is still happening to me 

(base) Liezls-MacBook-Pro:functions lie$ node --version
v12.13.1
(base) Liezls-MacBook-Pro:functions lie$ firebase --version
8.6.0

**Comment by liezl200** [comment]
const CONFIG = functions.config();
const CONFIG = functions.config();
console.log("config");
  console.log(JSON.stringify(CONFIG));
  // console.log(Object.keys(functions))
  const nextjsUrl = CONFIG.nextjs.url;

```
TypeError: Cannot read property 'url' of undefined
```

**Comment by liezl200** [comment]
cc @samtstern Still can't make this work. Could we re-open this issue for debugging?

**Comment by LeoLetourneur** [comment]
Hi, same problem here, can't make functions.config() work

**Comment by samtstern** [comment]
@liezl200 @LeoLetourneur if this is happening to you please open a new issue, this works in our testing so you're likely running into something new.

Make sure you have a `.runtimeconfig.json` file inside your `functions` folder!

**Comment by goleary** [comment]
I'm also running into this exact issue.  Even after upgrading to `firebase-tools: 8.14.1` `functions.config()` is still always undefined.

And I do have `.runtimeconfig.json` in my `functions` folder.

**Comment by leandro-manifesto** [comment]
I'm testing the Emulator Suite and this is definately still happening when I run:

```console
user@host:~/project$ yarn firebase emulators:start --project $PROJECT_ID
```

```
Ubuntu 20.04.2 LTS on WSL 2 on Windows 10 20H2 19042.870
Node v12.20.1
firebase-functions 3.13.2
firebase-tools 9.8.0
```

One would expect the runtime config to be downloaded from the current project.

**Comment by samtstern** [comment]
@leandro-manifesto we do not automatically download runtime configuration from prod, but you can do it yourself if you want to:

```
firebase functions:config:get > functions/.runtimeconfig.json
```

**Comment by leandro-manifesto** [comment]
I know you can download the configuration from the project.
What I'm saying is that as a developer that is cumbersome and I expected the tool to handle this for me.

**Comment by mbleigh** [comment]
Oftentimes using prod configs in local emulation can lead to accidents like sending live emails to users while testing something out locally. We keep the process a little more manual so that there is less chance of such mistakes. Thanks for the feedback, though!

**Comment by lundjrl** [comment]
Has anyone found a solution to this not working with firebase deploy? Tried to deploy my functions last night and I'm getting the same error OP is getting. Running  "firebase-admin": "^9.9.0", "firebase-functions": "^3.14.1" that were installed via npm on a 2019 Macbook pro. Also doesn't work for a Linux computer running the same versions.
