### ISSUE TITLE
firestore emulator does not support != and not in queries

### ISSUE THREAD

**Issue by sk-** [firebase/firebase-tools#2652]
### [REQUIRED] Environment info

**firebase-tools:** 8.11.2

**Platform:** macOS

### [REQUIRED] Test case

It's not easy to share a fully reproducible error, but see the queries below. 

### [REQUIRED] Steps to reproduce
Just ran a query like:

```js
const snapshot = await db.collection('test_not_equal').where('foo', '!=', 2).get();
const snapshot = await db.collection('test_not_in').where('foo', 'not-in', [1, 2]).get();
```

### [REQUIRED] Expected behavior

Firestore emulator should support `not-in` and `!=` as they are already supported by Firestore iOS [v1.18.0](https://github.com/firebase/firebase-ios-sdk/blob/master/Firestore/CHANGELOG.md#v1180) and nodejs firestore-admin [v4.3.0](https://github.com/googleapis/nodejs-firestore/releases/tag/v4.3.0).

### [REQUIRED] Actual behavior

Instead of returning the documents matching the query, all the documents of the collection are returned.

**Comment by samtstern** [comment]
@sk- thanks for reporting this!  Sounds like we need to cut a new Firestore Emulator JAR

**Comment by sk-** [comment]
Any ETA for this?

**Comment by yuchenshi** [comment]
Would you mind updating to the latest CLI version and latest SDK and try again? According to a Firebaser working on the SDK, this should work in the most recent versions.

**Comment by sk-** [comment]
@yuchenshi I just tried it with the latest version (8.12.1), but the results are the same.

Note that as @samtstern mentioned, this requires to cut a new release of the emulator and to update the version used by firebase-tools.

Note that the version of the firestore emulator was updated to 1.17.1 two months ago in https://github.com/firebase/firebase-tools/commit/0dedfa39503c9d2c83a3998710f794bf3ac39572. See also https://github.com/firebase/firebase-tools/blob/master/src/emulator/downloadableEmulators.ts#L43-L54

**Comment by yuchenshi** [comment]
Sure, let me cut a Firestore release soon and we'll see if that helps.

**Comment by yuchenshi** [comment]
I just tested this myself with latest JS SDK (7.23.0) on the web with Firestore Emulator v1.11.7 and everything is working fine (both `!=` and `not-in`).

I'm still proceeding with the release cutting, but at this rate I cannot really verify if it will work for you. Would you mind creating a minimal repro of the issue? A GitHub repo with your `package.json` and a script file that executes queries would be perfect.

**Comment by sk-** [comment]
@yuchenshi could you share the queries and tests you tried? Note that in my case the queries don't fail, but they produce wrong results, returning all documents.

Could it be that something is missing in `nodejs-firestore`?

I cannot easily share a repo, as the test I have is part of a private repo. However below is the test.

```js
const admin = require('firebase-admin');
const db = admin.firestore();

describe('not equal queries', () => {
  test('!=', async () => {
    const ref = db.collection('test_not_equal');
    await ref.doc('doc1').set({});
    await ref.doc('doc2').set({foo: 1});
    await ref.doc('doc3').set({foo: 2});
    await ref.doc('doc4').set({foo: null});
    await ref.doc('doc5').set({foo: 3});
    const snapshot = await ref.where('foo', '!=', 2).get();
    expect(snapshot.docs).toHaveLength(2);
  });

  test('not-in', async () => {
    const ref = db.collection('test_not_in');
    await ref.doc('doc1').set({});
    await ref.doc('doc2').set({foo: 1});
    await ref.doc('doc3').set({foo: 2});
    await ref.doc('doc4').set({foo: null});
    await ref.doc('doc5').set({foo: 3});
    const snapshot = await ref.where('foo', 'not-in', [2, 3]).get();
    expect(snapshot.docs).toHaveLength(1);
  });
});
```

In both cases I get 5 documents back from the query. Note that using `==` or `>=` works just fine.

**Comment by yuchenshi** [comment]
Thanks for the information! I can now reproduce the issue consistently on my local setup with Node.js (`firebase-admin`). It somehow doesn't happen on the web though. I've also verified that the Firestore Emulator release in flight will fix it, and it will come in pretty soon.

Again, I really appreciate your help on providing the tests!

**Comment by yuchenshi** [comment]
This is now fixed in the latest CLI release.

**Comment by RaviH** [comment]
This is still an issue for me. As you can see, not-in is still not there in the emulator and my tests that use not-in fail too!

![image](https://user-images.githubusercontent.com/141136/100292229-b7007f00-2f34-11eb-8336-7663be4b9bfa.png)

```
> firebase --version
8.16.2
```

**Comment by yuchenshi** [comment]
@RaviH I'm really surprised to hear your tests failing given that the Firestore Emulator itself (the Java process) should have full support of the `!=` operator already as of today. Would you please open a new issue with more details so that we can look into it?

And by the way, your screenshots describe https://github.com/firebase/firebase-tools-ui/issues/412 (support in Emulator UI, the web console), which will be released with the next CLI release or two.

**Comment by RaviH** [comment]
@yuchenshi Just a small clarification. It's `not-in` that I am interested in. Actually, it's blocking a prod issue for me. I will create a new ticket for sure, but thought if `not-in` is not working, then it's part of this issue itself.

**Comment by yuchenshi** [comment]
FYI: the Emulator UI changes shipped in the latest CLI release (v8.17.0) -- so that you can query data with the new operators in the Firestore Viewer.
