### ISSUE TITLE
Emulator export does not save created auth users

### ISSUE THREAD

**Issue by bradleymackey** [firebase/firebase-tools#2749]
### [REQUIRED] Environment info

**firebase-tools:** 8.14.0

**Platform:** macOS

### [REQUIRED] Test case

```sh
firebase emulators:start --export-on-exit="./my-local-dump"
```

Then add a user to the Auth emulator then exit by sending a `SIGINT`.

```sh
firebase emulators:start --import="./my-local-dump"
```

Checking auth emulator again, we see the user we just created is gone.

### [REQUIRED] Steps to reproduce

See above.

### [REQUIRED] Expected behavior

Auth users added via the emulator are saved in the emulator export.

### [REQUIRED] Actual behavior

The user is lost, it is not saved in the emulator export.

**Comment by IsaiahByDayah** [comment]
Noticed this too. I imagine it's in the pipeline for the fine folks at Firebase. Very excited for this awesome feature

**Comment by samtstern** [comment]
@bradleymackey @IsaiahByDayah thanks for trying out the Auth emulator right away!  Yes this is on the roadmap for sure.

**Comment by SamyPesse** [comment]
Thank you 👏  Really exciting to see the auth emulator, we were waiting on it to write better integration tests on some of our login flows. And it'll soon make it possible to dev locally without using the deployed environment.

But the lack of export makes it impossible for us to use it at the moment. All of our tests depend on a firestore export (generated from a testing data set) and we need the auth emulator to be in sync with it.

**Comment by yuchenshi** [comment]
Also, remember that you can [create users](https://firebase.google.com/docs/reference/admin/node/admin.auth.Auth#createuser) with email+password / phone using the Node.js Admin SDK with [UIDs of your choice](https://firebase.google.com/docs/reference/admin/node/admin.auth.CreateRequest#uid), which comes in handy when matching database records in other emulators.

Keeping a setup script should unblock you from testing for now. And stay tuned while we work on import/exports!

**Comment by herberthobregon** [comment]
It would be great to be able to define it in firebase.json like

```json
{
  "emulators": {
    "ui": {
      "enabled": true,
      "host": "localhost",
      "port": 4000
    },
    "auth": {
      "data": "./.firebase/auth"
    }
  }
}
```

**Comment by IsaiahByDayah** [comment]
@yuchenshi, when you get the time would you be able to provide an example "setup script" that can use the Admin SDK to create users? Not sure if I'm doing something wrong or if I ran into the bug mentioned here (https://github.com/firebase/firebase-admin-node/issues/1077)

**Comment by malcolmdeck** [comment]
Hey there, I've created b/172261810 to track this feature request internally :)

**Comment by jjalonso** [comment]
waiting this to be able to use the auth emulator ! thanks guys

**Comment by Gbuomprisco** [comment]
At the moment i wrote a script to setup my user before tests, or I run it after starting the Emulator:

```
const { auth } = require('./emulator-admin');

(async () => {
  await auth.createUser({
    uid: 'ID',
    email: 'test@yourdomain.com',
    password: 'pwd',
    displayName: 'User Name',
  });

  console.log('User created successfully');
  process.exit();
})();
```

The "emulator-admin" script is a simple setup where I initialize an admin app with references to the emuulator's endpoints

**Comment by tudor07** [comment]
I have the same issue + my firestore data is also not saved/restored

**Comment by Gbuomprisco** [comment]
@tudor07 you'll need to export it manually or add "--export-on-exit"

**Comment by tudor07** [comment]
@Gbuomprisco Ok, I fixed firestore data, but users are still not exported

**Comment by Joebayld** [comment]
> Also, remember that you can [create users](https://firebase.google.com/docs/reference/admin/node/admin.auth.Auth#createuser) with email+password / phone using the Node.js Admin SDK with [UIDs of your choice](https://firebase.google.com/docs/reference/admin/node/admin.auth.CreateRequest#uid), which comes in handy when matching database records in other emulators.
> 
> Keeping a setup script should unblock you from testing for now. And stay tuned while we work on import/exports!

Hey @yuchenshi what would be the best way to use a startup script? This method would work for me but I’m just unsure where to apply the setup code. 

Thanks!
Joe

**Comment by Gbuomprisco** [comment]
@tudor07 yes, hence this ticket

**Comment by yuchenshi** [comment]
@Joebayld You'd want it to be a Node.js script that you run every time you start the Auth Emulator, since Admin privileges are required to create with a fixed UID. For example, `firebase emulators:exec 'node ./your-setup-script.js && node ./your-test-script.js'`. For interactive development, you can replace `node ./your-test-script.js'` with `read` (or `pause` on Windows), and you can add `--ui` after `emulators:exec` to start the Emulator UI.

We know this is not ideal and we're committed to add support for import/exports just like the other emulators. Once we have that, the tricks above will only be required for more involved setups that cannot be covered with imports.

**Comment by faggv** [comment]
> At the moment i wrote a script to setup my user before tests, or I run it after starting the Emulator:
> 
> ```
> const { auth } = require('./emulator-admin');
> 
> (async () => {
>   await auth.createUser({
>     uid: 'ID',
>     email: 'test@yourdomain.com',
>     password: 'pwd',
>     displayName: 'User Name',
>   });
> 
>   console.log('User created successfully');
>   process.exit();
> })();
> ```
> 
> The "emulator-admin" script is a simple setup where I initialize an admin app with references to the emuulator's endpoints

Can you give us more clue about the "emulator-admin" script. Im trying to do this this way but the user is created in the actulal firebase project and not in the emulator.
`const admin = require('firebase-admin')

const serviceAccount = require('./serviceAccount.json')

const adminConfig = {
  credential: admin.credential.cert(serviceAccount),
  databaseURL: 'http://localhost:9000?ns=my-own-kpis',
}
admin.initializeApp(adminConfig)`

> At the moment i wrote a script to setup my user before tests, or I run it after starting the Emulator:
> 
> ```
> const { auth } = require('./emulator-admin');
> 
> (async () => {
>   await auth.createUser({
>     uid: 'ID',
>     email: 'test@yourdomain.com',
>     password: 'pwd',
>     displayName: 'User Name',
>   });
> 
>   console.log('User created successfully');
>   process.exit();
> })();
> ```
> 
> The "emulator-admin" script is a simple setup where I initialize an admin app with references to the emuulator's endpoints

Can you give us more clue about the "emulator-admin" script. Im trying to do this this way but the user is created in the actulal firebase project and not in the emulator.
`const admin = require('firebase-admin')

const serviceAccount = require('./serviceAccount.json')

const adminConfig = {
  credential: admin.credential.cert(serviceAccount),
  databaseURL: 'http://localhost:9000?ns=my-own-kpis',
}
admin.initializeApp(adminConfig)`

**Comment by faggv** [comment]
> At the moment i wrote a script to setup my user before tests, or I run it after starting the Emulator:
> 
> ```
> const { auth } = require('./emulator-admin');
> 
> (async () => {
>   await auth.createUser({
>     uid: 'ID',
>     email: 'test@yourdomain.com',
>     password: 'pwd',
>     displayName: 'User Name',
>   });
> 
>   console.log('User created successfully');
>   process.exit();
> })();
> ```
> 
> The "emulator-admin" script is a simple setup where I initialize an admin app with references to the emuulator's endpoints

Can you give us more clue about the "emulator-admin" script. Im trying to do this this way but the user is created in the actulal firebase project and not in the emulator.
`const admin = require('firebase-admin')

const serviceAccount = require('./serviceAccount.json')

const adminConfig = {
  credential: admin.credential.cert(serviceAccount),
  databaseURL: 'http://localhost:9000?ns=my-own-kpis',
}
admin.initializeApp(adminConfig)`

**Comment by Gbuomprisco** [comment]
@faggv added a gist here https://gist.github.com/Gbuomprisco/a74f1b0e91542eca0fcf4b89edf23823 - hope it helps! :)

**Comment by horizon89** [comment]
🙋‍♂️ waiting for this as well. Thanks so much for the work you do, Emulator Suite is awesome!

**Comment by nicholasio** [comment]
I was able to work around this by setting up a script that would recreate users with the same UID. In our app we have a `users` collection which stores additional user data. 

I modified a `onUserWrite` trigger we already have to store the user email in the user collection (only when using the emulator).

```js
const functions = require('firebase-functions');
const admin = require('firebase-admin');

const throwsHttpError = require('./throwsHttpError');


exports.onUserWrite = fn.firestore.document('users/{userId}').onWrite(async (change, context) => {
	const db = admin.firestore();
	const newValue = change.after.data();


	try {
                // do our regular stuff user data.

		/**
		 * Due to a limitation in firebase auth emulator where users are
		 * not persisted, we store the users email in the user collection
		 * to allows us to recreate user accounts when bootstrapping the emulator.
		 */
		if (process.env.FUNCTIONS_EMULATOR === 'true') {
			const user = await admin.auth().getUser(userId);
			await userDoc.update({ emulator_user_email: user.email });
		}
	} catch (ex) {
		throwsHttpError('unkown', ex.message);
	}
});
```

Then in a script called  `setup-emulator.js` we do the following:

```js
const admin = require('firebase-admin');
const readline = require('readline');

const rl = readline.createInterface({
	input: process.stdin,
	output: process.stdout,
});

admin.initializeApp({ projectId: 'YOUR_PROJECT_ID' });

(async () => {
	const auth = admin.auth();
	const db = admin.firestore();

	const usersSnapshot = await db.collection('users').get();
	usersSnapshot.forEach((doc) => {
		const data = doc.data();

		if (data.emulator_user_email) {
			auth.createUser({
				uid: doc.id,
				email: data.emulator_user_email,
				password: '123456',
				displayName: data.userName,
			});
		}
	});
        // used to keep firebase emulator alive
	rl.question('Hit CTRL+C to close'  () => {});
})();
```

This is the command we run to start the emulator:

```
FIREBASE_AUTH_EMULATOR_HOST=localhost:9099 firebase use default && firebase emulators:exec 'node ./functions/setup-emulator.js' --import=./save-data --export-on-exit --ui
```

**Comment by rsandor** [comment]
It would be great if we could get the auth export from the emulator to handle Google/FB/etc accounts so that they show right back up on import. Excited for this it will make development a lot easier for me every time I stop and start up the emulator. Thanks!

**Comment by Joebayld** [comment]
> @Joebayld You'd want it to be a Node.js script that you run every time you start the Auth Emulator, since Admin privileges are required to create with a fixed UID. For example, `firebase emulators:exec 'node ./your-setup-script.js && node ./your-test-script.js'`. For interactive development, you can replace `node ./your-test-script.js` with `read` (or `pause` on Windows), and you can add `--ui` after `emulators:exec` to start the Emulator UI.
> 
> We know this is not ideal and we're committed to add support for import/exports just like the other emulators. Once we have that, the tricks above will only be required for more involved setups that cannot be covered with imports.

Thanks @yuchenshi. This helps me out. 

Something I've noticed with the setup script that the auth user triggers are called for the created users every time I start the emulator. This isn't ideal as I perform some tasks (such as create Stripe users in test mode) and this now gets called every time when in reality the stripe user already exists. My workaround is a bunch of `(process.env.FUNCTIONS_EMULATOR === 'true')` checks in the trigger, but then if I want to test created a user AFTER the emulator is running, my trigger no longer works. 😥

I wonder if there is a way to create some test users BEFORE the triggers are enabled / active? 

I know this is something Google will fix in the future, however I'm itching to use the new Auth emulator in some capacity! 

Thanks

**Comment by samtstern** [comment]
@Joebayld we actually have an API (not documented yet, but stable) in the emulators that lets you temporarily disable background triggers.  This API exists in the **emulator hub** which is a small server that runs inside the Firebase CLI for emulate orchestration.  This normally starts up at port `4400`.

Here's some pseudocode:
```
# Disable all non-HTTP functions triggers
HTTP PUT http://localhost:4400/functions/disableBackgroundTriggers

# Add your auth users in this middle period
# ...

# Enable all non-HTTP functions triggers
HTTP PUT http://localhost:4400/functions/disableBackgroundTriggers
```

So you can just make two `PUT` requests in your setup script, one at the start and one at the end, to add your users without firing any functions.

**Comment by samtstern** [comment]
For anyone waiting for this feature it will be included in the _next_ release of `firebase-tools`!

**Comment by yuchenshi** [comment]
Shipped in v9.1.0!

**Comment by TDAK1509** [comment]
> @faggv added a gist here https://gist.github.com/Gbuomprisco/a74f1b0e91542eca0fcf4b89edf23823 - hope it helps! :)

Thanks, you saved my life!

**Comment by Joebayld** [comment]
> @Joebayld we actually have an API (not documented yet, but stable) in the emulators that lets you temporarily disable background triggers. This API exists in the **emulator hub** which is a small server that runs inside the Firebase CLI for emulate orchestration. This normally starts up at port `4400`.
> 
> Here's some pseudocode:
> 
> ```
> # Disable all non-HTTP functions triggers
> HTTP PUT http://localhost:4400/functions/disableBackgroundTriggers
> 
> # Add your auth users in this middle period
> # ...
> 
> # Enable all non-HTTP functions triggers
> HTTP PUT http://localhost:4400/functions/disableBackgroundTriggers
> ```
> 
> So you can just make two `PUT` requests in your setup script, one at the start and one at the end, to add your users without firing any functions.

Hey there @samtstern. Thanks for this info.

I know that the Auth state is now preserved in the emulator data, but now that I have this fancy setup script I'd like to still use it. Something I've noticed though is your method for disabling triggers doesn't seem to apply to Auth triggers such as `functions.auth.user().onCreate`. It works in disabling Firestore triggers when documents are created, deleted, etc. Just not for Auth triggers. Is that expected?

**Comment by samtstern** [comment]
@Joebayld nope that sounds like a bug to me!  But I can already in my head see why that went wrong :-) I'll get a fix together.

**Comment by Joebayld** [comment]
@samtstern Couple things to note with that bug. It does indicate the functions are disabled in the CLI but they just aren't. The other fun part I found is that for each time you call `http://localhost:4400/functions/enableBackgroundTriggers`, it causes triggers to fire multiple times instead of once. 

This was after creating a single user after calling the HTTP method a handful of times. 
<img width="456" alt="image" src="https://user-images.githubusercontent.com/9399317/103413696-a2716100-4b48-11eb-9436-19c0df42ca1b.png">

So if I call that http method 10 times, then create a user, the `onCreate` function will get called 10 times. My Stripe test account looks very interesting right now. 😉

**Comment by samtstern** [comment]
@Joebayld oh nice catch on the second issue!  I think both are fixed here:
https://github.com/firebase/firebase-tools/pull/2986

**Comment by ngbede** [comment]
> Shipped in v9.1.0!

I am still experiencing this issue, and I am using the latest version of firebase-tools which is 9.10.0 as of the time of writing.
