### ISSUE TITLE
[FR] Verifying emulated ID Tokens and creating session cookies only works in the Functions Emulator

### ISSUE THREAD

**Issue by favs-sama** [firebase/firebase-tools#2764]
### [REQUIRED] Environment info

**firebase-tools:** 8.14.1

**Platform:** Windows 10

### [REQUIRED] Test case
Currently emulating a scenario where a signed in user sends **userToken** from frontend and backend decoded this token and retrieves **uid** for fetching data from database.
```
const firebase = require('firebase/app');
require('firebase/auth');

const config = require('./config/firebaseConfig.json');

const firebaseConfig = {
  apiKey: config.apiKey,
  authDomain: config.authDomain,
  databaseURL: config.projectId,
  projectId: config.projectId,
  storageBucket: config.storageBucket,
  messagingSenderId: config.messagingSenderId,
  appId: config.appId,
  measurementId: config.measurementId
};

firebase.initializeApp(firebaseConfig);
firebase.auth().useEmulator("http://localhost:9099/");

const serviceAccountKey = require('./config/serviceAccountKey.json');

const admin = require('firebase-admin');

const databaseUrl = `http://localhost:9000/?ns=${config.projectId}`;
admin.initializeApp({
  credential: admin.credential.cert(serviceAccountKey),
  databaseURL: databaseUrl
});

const perform = async() => {
  const email = "test3@gmail.com";
  const password = "password";
  await admin.auth().createUser({
    email: email,
    password: password
  });

  await firebase.auth().signInWithEmailAndPassword(email, password);
  const userToken = await firebase.auth().currentUser.getIdToken();

  // code fails here where admin is supposed to successfully verify id token
  await admin.auth().verifyIdToken(userToken);
};

perform();
```

### [REQUIRED] Steps to reproduce
make sure that the following node packages are installed and firebase emulators for auth, firestore, and database are enabled:
```
 npm install -g firebase-tools
 npm install --save firebase
 npm install --save firebase-admin
```

### [REQUIRED] Expected behavior
The userToken is decoded properly so that uid is extracted from the token for fetching data.

### [REQUIRED] Actual behavior
It fails with Firebase ID token has no "kid" claim. The code is working normally except when using emulator.
```
WARNING: You are using the Auth Emulator, which is intended for local testing only.  Do not use with production credentials.
(node:24084) UnhandledPromiseRejectionWarning: Error: Firebase ID token has no "kid" claim. See https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve an ID token.
    at FirebaseAuthError.FirebaseError [as constructor]
```

**Comment by joachimroeleveld** [comment]
I'm running into this as well. I can't verify `idToken`s created by the emulator.

**Comment by samtstern** [comment]
@favs-sama where are you running the admin code? 

Right now `verifyIdToken()` for auth emulator tokens only works inside the Functions emulator.  This is out of a concern for security, short-circuiting `verifyIdToken()` is obviously dangerous if it accidentally happens in production so right now we only allow it in the Functions emulator, which we can control fully.

**Comment by favs-sama** [comment]
@samtstern originally i'm running the admin code `verifyIdToken()` in a backend prehandler function for handling user authorization; so, no i'm not running this inside a firebase function. although is there any other way to approach this kind of testing if currently `verifyIdToken()` for auth emulator is only accessible via functions emulator?

**Comment by samtstern** [comment]
@favs-sama yeah right now the only way to test this is inside the Functions emulator.  We do want to change this eventually but it requires us to build in a more secure version of `verifyIdToken()` that would be less dangerous to your server in the event of a configuration mistake! 

So for now I'll consider this a feature request.

**Comment by malcolmdeck** [comment]
I've created b/172262218 to track this feature request internally

**Comment by ricardoatsouza** [comment]
Also running into this. Will be watching this issue.

**Comment by samtstern** [comment]
I changed the name of this issue to more accurately reflect the feature request and include the use case from #2770

**Comment by AudunWA** [comment]
I'd need to verify/decode the token with the emulator as well.

**Comment by daniel-tucano** [comment]
> @favs-sama where are you running the admin code?
> 
> Right now `verifyIdToken()` for auth emulator tokens only works inside the Functions emulator. This is out of a concern for security, short-circuiting `verifyIdToken()` is obviously dangerous if it accidentally happens in production so right now we only allow it in the Functions emulator, which we can control fully.

I was planing to use the auth emulator to do tests without some weird workarounds required at the moment. I think that this behaviour (or at least some imitation of it) should be implemented for testing purposes. This also should have been mentioned at the documentation, would have saved me some time haha

**Comment by patelnets** [comment]
Does anyone have a workaround for this?

**Comment by mjgerace** [comment]
@samtstern just voicing my support for this - many, many engineers do not use https.callable and instead opt for express setups, myself included. Not being able to support this means that we have a lack of ability to test our client-server interaction through integration tests.

From an engineering perspective, shouldn't this be as easy as disabling the 'kid' claim check when a certain envvar is set to true (IE, an envvar that is only set when firebase is running emulator mode)? I don't particularly understand why this would be hard to facilitate.

**Comment by samtstern** [comment]
@mjgerace we know how to do this, but we're being extra careful about security.  If your production server ever got into a situation where it thought it should disable/skip ID token verification then you'd have a big problem!

In order to have _something_ in time for the launch of the Auth Emulator we compromised on a simple solution in the Node.js Admin SDK that is only enabled inside the Functions emulator.  We are actively working on a longer-term solution that we're happier with and when we finish it we will bring it to all of our Admin SDKs (Node, Java, Go, Python, etc) so that you can develop on your own server.

**Comment by mjgerace** [comment]
@samtstern this makes total sense - is there any timeline for this work? In the meantime, would it be bad to set an env var (FIREBASE_EMULATOR=1 yarn jest {test_file}) and otherwise workaround the issue in my actual auth middleware?

So long as I can modify the `verifyIdToken()` function, I could manually implement my suggested fix while I work on testing. Our app isn't in production and this would allow us to write tests without doing anything overly risky.

**Comment by samtstern** [comment]
@mjgerace we never offer timelines but this is something we're actively working on, it's not on the backlog.  If you want to work around this issue on your own server and you're confident you know how, go for it!

**Comment by daniel-tucano** [comment]
> Does anyone have a workaround for this?

At the moment when I'm running tests i change NODE_ENV environment variable to "test" and, based on that, change the auth token checking code to use the decode function from 'jsonwebtoken' module instead of firebase auth

**Comment by neural9** [comment]
> > Does anyone have a workaround for this?
> 
> At the moment when I'm running tests i change NODE_ENV environment variable to "test" and, based on that, change the auth token checking code to use the decode function from 'jsonwebtoken' module instead of firebase auth

Where are you getting the shared secret from in order to validate? Or by validate do you actually mean 'decode' to obtain UID etc?

**Comment by ideodora** [comment]
I want use admin.createSessionCookie with auth emulator.
There is no workaround for this.

**Comment by nicoburns** [comment]
@samtstern Couldn't this be as simple as checking for the presence of the `FIREBASE_AUTH_EMULATOR_HOST` environment variable? If you are using the auth emulator then it is safe to assume that you're not running in production (or you already have some very serious security issues).

**Comment by samtstern** [comment]
@nicoburns we use the presence of that environment variable to redirect any outbound HTTP requests the Admin SDK makes to the Auth API.  However verifying ID Tokens and creating session cookies are mostly local operations that do not touch the Auth API.  So changing how they work just based on the presence of an env var would create the possibility of someone remotely short-circuiting your Admin server's security, something we really really want to avoid.

We're working on changes to how the Admin SDK handles these operations that will make it safer to fix this issue.

**Comment by tudor07** [comment]
any updates on this?

**Comment by jasonho-lynx** [comment]
The error seems to also happen despite using the Functions emulator - do you mean that it only works if `verifyIdToken` is used within a `https.callable`? I'm using Express in my Cloud Function instead

**Comment by yuchenshi** [comment]
This restriction is now lifted as of [Node.js Admin SDK v9.5.0](https://github.com/firebase/firebase-admin-node/releases/tag/v9.5.0). Happy verifying emulator tokens!

**Comment by Joebayld** [comment]
> This restriction is now lifted as of [Node.js Admin SDK v9.5.0](https://github.com/firebase/firebase-admin-node/releases/tag/v9.5.0). Happy verifying emulator tokens!

Is there anything special we need to do for the `firebase-admin` to verify emulator tokens? I'm still getting the 'Firebase ID token has no "kid" claim.' error..

**Comment by athomasoriginal** [comment]
Hey all!  Glad to here this landed in Node Admin SDK.  Is there an issue where I can track when this lands in Java Admin SDK?

**Comment by yuchenshi** [comment]
@athomasoriginal https://github.com/firebase/firebase-admin-java/issues/493 tracks the Java Admin SDK feature request.

**Comment by aacebo** [comment]
> > This restriction is now lifted as of [Node.js Admin SDK v9.5.0](https://github.com/firebase/firebase-admin-node/releases/tag/v9.5.0). Happy verifying emulator tokens!
> 
> Is there anything special we need to do for the `firebase-admin` to verify emulator tokens? I'm still getting the 'Firebase ID token has no "kid" claim.' error..
> 
> EDIT:
> I found the issue.. I had to set the `FIREBASE_AUTH_EMULATOR_HOST` env variable. However, when running in Docker, localhost doesn't work and you have to use a special url. The following works if you're doing tests in a docker image:
> `docker run -e FIREBASE_AUTH_EMULATOR_HOST='host.docker.internal:9099' -p 8088:8080 my-image`

looks like based on the PR description from the release here https://github.com/firebase/firebase-admin-node/pull/1148 you need to do something like `firebase emulators:start -p my-project-id` and then initialize the sdk with that project id

**Comment by vajahath** [comment]
@yuchenshi Let's update the Firebase documentation. It still says
> When running in any other environment, such as Cloud Run or your own server, these tokens will be rejected by the Admin SDK.

ref: https://firebase.google.com/docs/emulator-suite/connect_auth#id_tokens

**Comment by yuchenshi** [comment]
@vajahath We're updated the docs. Thanks for the heads up.

**Comment by chrisjacobs91** [comment]
> > This restriction is now lifted as of [Node.js Admin SDK v9.5.0](https://github.com/firebase/firebase-admin-node/releases/tag/v9.5.0). Happy verifying emulator tokens!
> 
> Is there anything special we need to do for the `firebase-admin` to verify emulator tokens? I'm still getting the 'Firebase ID token has no "kid" claim.' error..
> 
> EDIT:
> I found the issue.. I had to set the `FIREBASE_AUTH_EMULATOR_HOST` env variable. However, when running in Docker, localhost doesn't work and you have to use a special url. The following works if you're doing tests in a docker image:
> `docker run -e FIREBASE_AUTH_EMULATOR_HOST='host.docker.internal:9099' -p 8088:8080 my-image`

@Joebayld Would you be able to point me to any documentation on this?

I'm trying to get this working with a NextJS setup and struggling. I've updated firebase-admin to v9.9.0 but having no joy with the auth emulator tokens.

**Comment by artooras** [comment]
Hi. A silly question perhaps, but where does on set the FIREBASE_AUTH_EMULATOR_HOST environment variable? The documentation doesn't explicitly state it. In which file should it be set? Where should it be located? @Joebayld , you seem to have figured it out, so any advice would be really appreciated... :) Thanks!

**Comment by v-kiniv** [comment]
> Hi. A silly question perhaps, but where does one set the FIREBASE_AUTH_EMULATOR_HOST environment variable? The documentation doesn't explicitly state it. In which file should it be set? Where should it be located? @Joebayld , you seem to have figured it out, so any advice would be really appreciated... :) Thanks!

It's environment variable, you can set it globally in ~/.bash_profile or in terminal before firebase command:
`FIREBASE_AUTH_EMULATOR_HOST=localhost:9099; firebase emulators:start`.

For convenience use something like https://www.npmjs.com/package/dotenv, to separate configurations.

**Comment by artooras** [comment]
Thanks @v-kiniv . Only I made it work by setting the variable on the dev script as opposed to the emulators script:

"dev": "FIREBASE_AUTH_EMULATOR_HOST=localhost:9099 next dev"

**Comment by harmandeep-singh** [comment]
This still existing in my case  ,
```
    code: 'auth/argument-error',
    message: 'Firebase ID token has no "kid" claim. See https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve an ID token.'
```
 i am using firebase latest : 
`"firebase-admin": "^9.11.0",`
also set env. variable  : 
`FIREBASE_AUTH_EMULATOR_HOST=localhost:9099`  



```js
const idToken="eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJlbWFpbCI6InJvaGFuLmtoYWFuYWlvQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiYXV0aF90aW1lIjoxNjI3NTY5NDA3LCJ1c2VyX2lkIjoiQ2VmQXV6ZlFsdG4yWkN2V1dIYU9rWE82YmhOMCIsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicm9oYW4ua2hhYW5haW9AZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifSwiaWF0IjoxNjI3NTY5NDA3LCJleHAiOjE2Mjc1NzMwMDcsImF1ZCI6InNreWNybS0xYjYzOSIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9za3ljcm0tMWI2MzkiLCJzdWIiOiJDZWZBdXpmUWx0bjJaQ3ZXV0hhT2tYTzZiaE4wIn0.";

admin.auth().verifyIdToken(idToken).then((decodedToken) => {
        console.log("decode token", decodedToken);
})
```

**Comment by v-kiniv** [comment]
> This still existing in my case ,
> 
> ```
>     code: 'auth/argument-error',
>     message: 'Firebase ID token has no "kid" claim. See https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve an ID token.'
> ```
> 
> i am using firebase latest :
> `"firebase-admin": "^9.11.0",`
> also set env. variable :
> `FIREBASE_AUTH_EMULATOR_HOST=localhost:9099`
> 
> ```js
> const idToken="eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJlbWFpbCI6InJvaGFuLmtoYWFuYWlvQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiYXV0aF90aW1lIjoxNjI3NTY5NDA3LCJ1c2VyX2lkIjoiQ2VmQXV6ZlFsdG4yWkN2V1dIYU9rWE82YmhOMCIsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicm9oYW4ua2hhYW5haW9AZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifSwiaWF0IjoxNjI3NTY5NDA3LCJleHAiOjE2Mjc1NzMwMDcsImF1ZCI6InNreWNybS0xYjYzOSIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9za3ljcm0tMWI2MzkiLCJzdWIiOiJDZWZBdXpmUWx0bjJaQ3ZXV0hhT2tYTzZiaE4wIn0.";
> 
> admin.auth().verifyIdToken(idToken).then((decodedToken) => {
>         console.log("decode token", decodedToken);
> })
> ```

Make sure you've updated `firebase-tools` to the latest version:
`npm i -g firebase-tools`

**Comment by harmandeep-singh** [comment]
> ```js
> const idToken="eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJlbWFpbCI6InJvaGFuLmtoYWFuYWlvQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiYXV0aF90aW1lIjoxNjI3NTY5NDA3LCJ1c2VyX2lkIjoiQ2VmQXV6ZlFsdG4yWkN2V1dIYU9rWE82YmhOMCIsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicm9oYW4ua2hhYW5haW9AZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifSwiaWF0IjoxNjI3NTY5NDA3LCJleHAiOjE2Mjc1NzMwMDcsImF1ZCI6InNreWNybS0xYjYzOSIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9za3ljcm0tMWI2MzkiLCJzdWIiOiJDZWZBdXpmUWx0bjJaQ3ZXV0hhT2tYTzZiaE4wIn0.";
> ```

**sorry ! it was my Bad , after set env. reload the console  can help if some one else stuck in same situation.**  😀😀

**Comment by harmandeep-singh** [comment]
> > This still existing in my case ,
> > ```
> >     code: 'auth/argument-error',
> >     message: 'Firebase ID token has no "kid" claim. See https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve an ID token.'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i am using firebase latest :
> > `"firebase-admin": "^9.11.0",`
> > also set env. variable :
> > `FIREBASE_AUTH_EMULATOR_HOST=localhost:9099`
> > ```js
> > const idToken="eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJlbWFpbCI6InJvaGFuLmtoYWFuYWlvQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiYXV0aF90aW1lIjoxNjI3NTY5NDA3LCJ1c2VyX2lkIjoiQ2VmQXV6ZlFsdG4yWkN2V1dIYU9rWE82YmhOMCIsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicm9oYW4ua2hhYW5haW9AZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifSwiaWF0IjoxNjI3NTY5NDA3LCJleHAiOjE2Mjc1NzMwMDcsImF1ZCI6InNreWNybS0xYjYzOSIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9za3ljcm0tMWI2MzkiLCJzdWIiOiJDZWZBdXpmUWx0bjJaQ3ZXV0hhT2tYTzZiaE4wIn0.";
> > 
> > admin.auth().verifyIdToken(idToken).then((decodedToken) => {
> >         console.log("decode token", decodedToken);
> > })
> > ```
> 
> Make sure you've updated `firebase-tools` to the latest version:
> `npm i -g firebase-tools`

sorry ! it was my Bad , after set env. reload the console can help if some one else stuck in same situation. 😀😀

**Comment by samlof** [comment]
Any news on this for other SDKs? I'm developing with Go and came across this.

Not hard to bypass when you find this but takes an hour to figure out why and implement it

**Comment by aruntj** [comment]
> Any news on this for other SDKs? I'm developing with Go and came across this.
> 
> Not hard to bypass when you find this but takes an hour to figure out why and implement it
> 
> EDIT. Seems my problem was using old package. Firestore docs https://firebase.google.com/docs/firestore/quickstart#go tell to install the old GOPATH version and not /v4

Oh my! You're a life saver! Following the docs does lead go users right into this issue. Thanks for this. And thanks firebase team!

**Comment by rromanchuk** [comment]
Is there an implementation (or merge) reference of the type of branching `FIREBASE_AUTH_EMULATOR_HOST` is doing during jwt decoding of unsigned emulator tokens?  AKA, I don't have a Admin SDK so decoding/verification fails so need to implement myself.

**Comment by jalvini** [comment]
This is still happening to me.

I am logging the user in using the following piece of code in Swift:

Auth.auth().signIn(withEmail: email, password: password)


I am then passing in an ID token to the backend web call like so:

```
let userIDToken = try await signIn.result?.user.getIDToken() ?? ""
await web.webCall(endpoint: userIDToken)
```

Finally, I am using Express/Cloud Run on the backend and verifying my token like this:

```
let idToken = await admin.auth().verifyIdToken(req.body.idToken);
const uid = idToken.uid;

console.log(uid);
```

However, I am getting the following error message:

FirebaseAuthError: Firebase ID token has no "kid" claim. See https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve an ID token.

When I go to that URL, it tells me to do exactly what Im doing, so what am I doing wrong?

**Comment by taeold** [comment]
@jalvini If you are having issues, can you file a new bug?

**Comment by HigorAlves** [comment]
Even with the env var Im getting this error: 

`FirebaseAppError: Error while making request: connect ECONNREFUSED ::1:9099. Error code: ECONNREFUSED`

**Comment by wesharper** [comment]
> Even with the env var Im getting this error:
> 
> `FirebaseAppError: Error while making request: connect ECONNREFUSED ::1:9099. Error code: ECONNREFUSED`

I had to change mine to `127.0.0.1:9099` vs `localhost:9099`. However, I'm now having an issue where the firebase auth emulator cannot find the user corresponding to the identifier in the JWT.

**Comment by Mikephii** [comment]
any update on this for the go v4 sdk? is it safe to use "firebase.google.com/go" instead of v4?

**Comment by abdushkur** [comment]
I implemented like this:
```
async function getToken(email, password) {
  const isRunningInEmulator = process.env.FUNCTIONS_EMULATOR === 'true';
  const baseUrl = isRunningInEmulator? 'http://192.168.1.136:9099' : 'https://www.googleapis.com';
  const data = {
    email: email,
    password: password,
    returnSecureToken: true
  };

  try {
    const response = await axios.post(`${baseUrl}/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=API_KEY`, data, {
      headers: {
        'Content-Type': 'application/json'
      }
    });
    return response.data;
  } catch (error) {
    console.error('Error getting token:', error.response ? error.response.data : error.message);
    throw error;
  }
}
```
FUNCTIONS_EMULATOR is automatically set

**Comment by rublev** [comment]
Unreal that I am still getting the "Firebase ID token has no "kid" claim". Complete joke.

**Comment by khozzy** [comment]
@rublev make sure that you set the variable in the shell where the token is verified (not produced)

**Comment by Dan6200** [comment]
If you are using the emulator both server side and client side. The client-side variable is "http://localhost:9099" and the server side variable is "localhost:9099". This is useful for those using nextjs and the some server side logic with server actions and also clientside logic sometimes.

**Comment by kirill-dev-pro** [comment]
Thats bullshit, now im getting this error also in production with no emulator involved. React-native firebase on the frontend just do not include kid into id token, it seems
