### ISSUE TITLE
 400, Precondition check failed. When running firebase database:instances:create instanceName

### ISSUE THREAD

**Issue by mohitsud** [firebase/firebase-tools#2917]
I am running firebase-tools version 8.18.

When running ```firebase database:instances:create instanceName``` I get the error:

```
Error: HTTP Error: 400, Precondition check failed.
``

Any insight is appreciated.

**Comment by bkendall** [comment]
Can you provide any additional details from your `firebase-debug.json` file? Or running the command with `--debug`?

**Comment by mohitsud** [comment]
Attached is the firebase-debug.json logs

```
[debug] [2020-12-11T15:08:10.210Z] ----------------------------------------------------------------------
[debug] [2020-12-11T15:08:10.212Z] Command:       /Users/me/.nvm/versions/node/v10.22.1/bin/node /Users/me/.nvm/versions/node/v10.22.1/bin/firebase database:instances:create decor-timeandspace --project decor-timeandspace --json --debug
[debug] [2020-12-11T15:08:10.212Z] CLI Version:   8.12.1
[debug] [2020-12-11T15:08:10.212Z] Platform:      darwin
[debug] [2020-12-11T15:08:10.212Z] Node Version:  v10.22.1
[debug] [2020-12-11T15:08:10.213Z] Time:          Fri Dec 11 2020 07:08:10 GMT-0800 (Pacific Standard Time)
[debug] [2020-12-11T15:08:10.213Z] ----------------------------------------------------------------------
[debug] [2020-12-11T15:08:10.213Z]
[debug] [2020-12-11T15:08:10.219Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-12-11T15:08:10.219Z] > authorizing via signed-in user
[debug] [2020-12-11T15:08:10.221Z] [iam] checking project decor-timeandspace for permissions ["firebase.projects.get","firebasedatabase.instances.create"]
[debug] [2020-12-11T15:08:10.224Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/decor-timeandspace:testIamPermissions
 {"permissions":["firebase.projects.get","firebasedatabase.instances.create"]}
[debug] [2020-12-11T15:08:10.392Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Fri, 11 Dec 2020 15:08:10 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","server-timing":"gfet4t7; dur=55","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-12-11T15:08:10.393Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/decor-timeandspace

[debug] [2020-12-11T15:08:10.579Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Fri, 11 Dec 2020 15:08:10 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-12-11T15:08:10.580Z] >>> HTTP REQUEST POST https://mobilesdk-pa.googleapis.com/v1/projects/277554221689/databases

[debug] [2020-12-11T15:08:11.001Z] <<< HTTP RESPONSE 400 {"vary":"X-Origin, Referer, Origin,Accept-Encoding","content-type":"application/json; charset=UTF-8","date":"Fri, 11 Dec 2020 15:08:10 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2020-12-11T15:08:11.001Z] <<< HTTP RESPONSE BODY {"error":{"code":400,"message":"Precondition check failed.","status":"FAILED_PRECONDITION"}}
[error]
[error] Error: HTTP Error: 400, Precondition check failed.
[debug] [2020-12-11T15:08:11.006Z] Error Context: {
  "body": {
    "error": {
      "code": 400,
      "message": "Precondition check failed.",
      "status": "FAILED_PRECONDITION"
    }
  },
  "response": {
    "statusCode": 400,
    "body": {
      "error": {
        "code": 400,
        "message": "Precondition check failed.",
        "status": "FAILED_PRECONDITION"
      }
    },
    "headers": {
      "vary": "X-Origin, Referer, Origin,Accept-Encoding",
      "content-type": "application/json; charset=UTF-8",
      "date": "Fri, 11 Dec 2020 15:08:10 GMT",
      "server": "ESF",
      "cache-control": "private",
      "x-xss-protection": "0",
      "x-frame-options": "SAMEORIGIN",
      "x-content-type-options": "nosniff",
      "alt-svc": "h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"",
      "accept-ranges": "none",
      "transfer-encoding": "chunked"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "mobilesdk-pa.googleapis.com",
        "port": 443,
        "hostname": "mobilesdk-pa.googleapis.com",
        "hash": null,
        "search": null,
        "query": null,
        "pathname": "/v1/projects/277554221689/databases",
        "path": "/v1/projects/277554221689/databases",
        "href": "https://mobilesdk-pa.googleapis.com/v1/projects/277554221689/databases"
      },
      "method": "POST"
    }
  }
}

```

**Comment by apsoftwaredev** [comment]
I'm getting this same error now when I deploy to hosting.  -- only functions works fine.  hosting gives this error:

**Comment by apsoftwaredev** [comment]
It looks like I exceeded the daily bandwidth or compute quota is what is doing it for me. Check the usage and billing section in the console.  That might be it.  Thanks.

**Comment by mpwei** [comment]
I have same problem when deploying to hosting, and I have found the question:
firebase.json:
`{
  "hosting": [
    {
      "target": "<my-target>",
      "public": "<my-public-path>",
      "ignore": [
        "firebase.json",
        "**/.*",
        "**/node_modules/**"
      ],
      "rewrites": [
        {
          "source": "**",
          "destination": "/index.html"
        },
        {
          "source": "/api/**",
          "run": {
            "serviceId": "<cloud-run-service-id>",
            "region": "<cloud-run-service-region>"
          }
        }
      ],
      "headers": [
        { "source":"/api/**", "headers": [{"key": "Cache-Control", "value": "no-cache, no-store"}] }
      ]
    }
}`

When I run "firebase deploy --only hosting:<my-target>", I'm getting response "HTTP Error: 400, Precondition check failed."
Now I have removed rewrite config and deploy again, then my project deployed successfully.
This is now my configuration in firebase.json:
`{
  "hosting": [
    {
      "target": "<my-target>",
      "public": "<my-public-path>",
      "ignore": [
        "firebase.json",
        "**/.*",
        "**/node_modules/**"
      ]
    },
}`

I guess rewrite configuration to cloud run has something error.

**Comment by bkendall** [comment]
@apsoftwaredev and @mpwei - I believe you were hitting a different issue than the original post. #2949 is what you were looking for (which is resolved).

@mohitsud - I'm sorry this took so long to get back to you. First, it looks like the version of the CLI that you're using is older than 8.18. It may help to upgrade the CLI. My second thought is that maybe you need permissions in the project for that check. Can you confirm that you have the `firebasedatabase.instances.list` in the project?

**Comment by mohitsud** [comment]
I will close this issue for now. It still exists, but I find it fixes it self when I log into firebase and click on "Realtime Database" and select "Get Started". It seems that one button solves this bug for me. I cant explain it.

**Comment by bkendall** [comment]
I think @sarajmunjal may be the best person to take more of a look. I'm not completely familiar with this flow, so hopefully he can help out.

**Comment by sarajmunjal** [comment]
Hi @mohitsud did the error persist after you upgraded the CLI version?
