### ISSUE TITLE
Firebase serves hangs on 'Watching "/path/" for Cloud Functions...'

### ISSUE THREAD

**Issue by JSmithOner** [firebase/firebase-tools#3003]
### [REQUIRED] Environment info

**firebase-tools:** 9.1.1

**Platform:** MacOS Catalina 10.15.5

### [REQUIRED] Test case

worked on the server (changed files structure ), exit the server, then try to restart it.
Sorry if I can't send you all the file. I've been trying `firebase emulators:start --only functions` and it seemed to work fine
Inside my file I have firestore write triggers and and http.callable functions.

### [REQUIRED] Steps to reproduce

run `firebase emulators:start`

### [REQUIRED] Expected behavior

functions should launch

### [REQUIRED] Actual behavior

Haven't copied all the stack trace but here is where it stops

> 
> [2021-01-07T16:51:58.030Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Thu, 07 Jan 2021 16:51:57 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
> i  hosting: Serving hosting files from: N {"metadata":{"emulator":{"name":"hosting"},"message":"Serving hosting files from: \u001b[1mN\u001b[22m"}}
> ✔  hosting: Local server: http://localhost:5000 {"metadata":{"emulator":{"name":"hosting"},"message":"Local server: \u001b[4m\u001b[1mhttp://localhost:5000\u001b[22m\u001b[24m"}}
> [2021-01-07T16:51:58.057Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"ui"},"message":"Ignoring unsupported arg: auto_download"}}
> [2021-01-07T16:51:58.058Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"ui"},"message":"Ignoring unsupported arg: port"}}
> [2021-01-07T16:51:58.058Z] Starting Emulator UI with command {"binary":"node","args":["/Users/vv/.cache/firebase/emulators/ui-v1.4.1/server.bundle.js"],"optionalArgs":[],"joinArgs":false} {"metadata":{"emulator":{"name":"ui"},"message":"Starting Emulator UI with command {\"binary\":\"node\",\"args\":[\"/Users/vv/.cache/firebase/emulators/ui-v1.4.1/server.bundle.js\"],\"optionalArgs\":[],\"joinArgs\":false}"}}
> i  ui: Emulator UI logging to ui-debug.log {"metadata":{"emulator":{"name":"ui"},"message":"Emulator UI logging to \u001b[1mui-debug.log\u001b[22m"}}
> [2021-01-07T16:51:58.169Z] Web / API server started at http://localhost:4000
>  {"metadata":{"emulator":{"name":"ui"},"message":"Web / API server started at http://localhost:4000\n"}}
> i  functions: Watching "/Users/XX/XXX/XX/XXX//functions" for Cloud Functions... {"metadata":{"emulator":{"name":"functions"},"message":"Watching \"/Users/XX/XXX/XX/XXX//functions\" for Cloud Functions..."}}
> [2021-01-07T16:51:58.334Z] [worker-pool] addWorker(~diagnostic~) {"metadata":{"emulator":{"name":"functions"},"message":"[worker-pool] addWorker(~diagnostic~)"}}
> [2021-01-07T16:51:58.334Z] [worker-pool] Adding worker with key ~diagnostic~, total=1 {"metadata":{"emulator":{"name":"functions"},"message":"[worker-pool] Adding worker with key ~diagnostic~, total=1"}}
> [2021-01-07T16:51:58.335Z] [worker-pool] submitWork(triggerId=) {"metadata":{"emulator":{"name":"functions"},"message":"[worker-pool] submitWork(triggerId=)"}}
> [2021-01-07T16:51:58.335Z] [worker-~diagnostic~-7e113a21-2bae-405a-b858-1c47c2e4205d]: Assigning socketPath: /var/folders/v5/_l2gvs2j6d5g1y92xlrdj9nc0000gn/T/fire_emu_3880.sock {"metadata":{"emulator":{"name":"functions"},"message":"[worker-~diagnostic~-7e113a21-2bae-405a-b858-1c47c2e4205d]: Assigning socketPath: /var/folders/v5/_l2gvs2j6d5g1y92xlrdj9nc0000gn/T/fire_emu_3880.sock"}}
> [2021-01-07T16:51:58.335Z] [worker-~diagnostic~-7e113a21-2bae-405a-b858-1c47c2e4205d]: BUSY {"metadata":{"emulator":{"name":"functions"},"message":"[worker-~diagnostic~-7e113a21-2bae-405a-b858-1c47c2e4205d]: BUSY"}}
> [2021-01-07T16:51:58.498Z] [runtime-status] [3880] Functions runtime initialized. {"cwd":"/Users/XX/XXX/XX/XXX//functions","node_version":"14.5.0"} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [3880] Functions runtime initialized. {\"cwd\":\"/Users/XX/XXX/XX/XXX//functions\",\"node_version\":\"14.5.0\"}"}}
> [2021-01-07T16:51:58.499Z] [runtime-status] [3880] Disabled runtime features: undefined {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [3880] Disabled runtime features: undefined"}}
> [2021-01-07T16:51:58.502Z] [runtime-status] [3880] Resolved module firebase-admin {"declared":true,"installed":true,"version":"9.4.1","resolution":"/Users/XX/XXX/XX/XXX//functions/node_modules/firebase-admin/lib/index.js"} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [3880] Resolved module firebase-admin {\"declared\":true,\"installed\":true,\"version\":\"9.4.1\",\"resolution\":\"/Users/XX/XXX/XX/XXX//functions/node_modules/firebase-admin/lib/index.js\"}"}}
> [2021-01-07T16:51:58.503Z] [runtime-status] [3880] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.12.0","resolution":"/Users/XX/XXX/XX/XXX//functions/node_modules/firebase-functions/lib/index.js"} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [3880] Resolved module firebase-functions {\"declared\":true,\"installed\":true,\"version\":\"3.12.0\",\"resolution\":\"/Users/XX/XXX/XX/XXX//functions/node_modules/firebase-functions/lib/index.js\"}"}}
> [2021-01-07T16:51:58.504Z] [runtime-status] [3880] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.12.0","resolution":"/Users/XX/XXX/XX/XXX//functions/node_modules/firebase-functions/lib/index.js"} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [3880] Resolved module firebase-functions {\"declared\":true,\"installed\":true,\"version\":\"3.12.0\",\"resolution\":\"/Users/XX/XXX/XX/XXX//functions/node_modules/firebase-functions/lib/index.js\"}"}}
> [2021-01-07T16:51:58.505Z] [runtime-status] [3880] Set PUBSUB_EMULATOR_HOST to localhost:8085 {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [3880] Set PUBSUB_EMULATOR_HOST to localhost:8085"}}
> [2021-01-07T16:51:58.506Z] [runtime-status] [3880] Outgoing network have been stubbed. [{"name":"http","status":"mocked"},{"name":"http","status":"mocked"},{"name":"https","status":"mocked"},{"name":"https","status":"mocked"},{"name":"net","status":"mocked"}] {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [3880] Outgoing network have been stubbed. [{\"name\":\"http\",\"status\":\"mocked\"},{\"name\":\"http\",\"status\":\"mocked\"},{\"name\":\"https\",\"status\":\"mocked\"},{\"name\":\"https\",\"status\":\"mocked\"},{\"name\":\"net\",\"status\":\"mocked\"}]"}}
> [2021-01-07T16:51:58.507Z] [runtime-status] [3880] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.12.0","resolution":"/Users/XX/XXX/XX/XXX//functions/node_modules/firebase-functions/lib/index.js"} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [3880] Resolved module firebase-functions {\"declared\":true,\"installed\":true,\"version\":\"3.12.0\",\"resolution\":\"/Users/XX/XXX/XX/XXX//functions/node_modules/firebase-functions/lib/index.js\"}"}}
> [2021-01-07T16:51:58.548Z] [runtime-status] [3880] Checked functions.config() {"config":{}} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [3880] Checked functions.config() {\"config\":{}}"}}
> [2021-01-07T16:51:58.548Z] [runtime-status] [3880] firebase-functions has been stubbed. {"functionsResolution":{"declared":true,"installed":true,"version":"3.12.0","resolution":"/Users/XX/XXX/XX/XXX//functions/node_modules/firebase-functions/lib/index.js"}} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [3880] firebase-functions has been stubbed. {\"functionsResolution\":{\"declared\":true,\"installed\":true,\"version\":\"3.12.0\",\"resolution\":\"/Users/XX/XXX/XX/XXX//functions/node_modules/firebase-functions/lib/index.js\"}}"}}
> [2021-01-07T16:51:58.549Z] [runtime-status] [3880] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.12.0","resolution":"/Users/XX/XXX/XX/XXX//functions/node_modules/firebase-functions/lib/index.js"} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [3880] Resolved module firebase-functions {\"declared\":true,\"installed\":true,\"version\":\"3.12.0\",\"resolution\":\"/Users/XX/XXX/XX/XXX//functions/node_modules/firebase-functions/lib/index.js\"}"}}
> [2021-01-07T16:51:58.550Z] [runtime-status] [3880] Resolved module firebase-admin {"declared":true,"installed":true,"version":"9.4.1","resolution":"/Users/XX/XXX/XX/XXX//functions/node_modules/firebase-admin/lib/index.js"} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [3880] Resolved module firebase-admin {\"declared\":true,\"installed\":true,\"version\":\"9.4.1\",\"resolution\":\"/Users/XX/XXX/XX/XXX//functions/node_modules/firebase-admin/lib/index.js\"}"}}
> [2021-01-07T16:51:58.550Z] [runtime-status] [3880] Resolved module firebase-functions {"declared":true,"installed":true,"version":"3.12.0","resolution":"/Users/XX/XXX/XX/XXX//functions/node_modules/firebase-functions/lib/index.js"} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [3880] Resolved module firebase-functions {\"declared\":true,\"installed\":true,\"version\":\"3.12.0\",\"resolution\":\"/Users/XX/XXX/XX/XXX//functions/node_modules/firebase-functions/lib/index.js\"}"}}
> [2021-01-07T16:51:58.550Z] [runtime-status] [3880] firebase-admin has been stubbed. {"adminResolution":{"declared":true,"installed":true,"version":"9.4.1","resolution":"/Users/XX/XXX/XX/XXX//functions/node_modules/firebase-admin/lib/index.js"}} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [3880] firebase-admin has been stubbed. {\"adminResolution\":{\"declared\":true,\"installed\":true,\"version\":\"9.4.1\",\"resolution\":\"/Users/XX/XXX/XX/XXX//functions/node_modules/firebase-admin/lib/index.js\"}}"}}
> [2021-01-07T16:51:58.552Z] [runtime-status] [3880] initializeApp(DEFAULT) {"storageBucket":"test-7b835.appspot.com","databaseURL":"http://localhost:9000/?ns=test-7b835","projectId":"test-7b835"} {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [3880] initializeApp(DEFAULT) {\"storageBucket\":\"test-7b835.appspot.com\",\"databaseURL\":\"http://localhost:9000/?ns=test-7b835\",\"projectId\":\"test-7b835\"}"}}
> [2021-01-07T16:51:58.594Z] [runtime-status] [3880] auth.setJwtVerificationEnabled(false) {"metadata":{"emulator":{"name":"functions"},"message":"[runtime-status] [3880] auth.setJwtVerificationEnabled(false)"}}
> [2021-01-07T16:51:58.842Z] addFirestoreTrigger "{\"eventTrigger\":{\"resource\":\"projects/test-7b835/databases/(default)/documents/vendors/{vendorId}/parts/{partId}\",\"eventType\":\"providers/cloud.firestore/eventTypes/document.write\",\"service\":\"firestore.googleapis.com\"}}"
> [2021-01-07T16:51:58.843Z] >>> HTTP REQUEST PUT http://localhost:8080/emulator/v1/projects/test-7b835/triggers/updateVendoredPart-0
>  {"eventTrigger":{"resource":"projects/test-7b835/databases/(default)/documents/vendors/{vendorId}/parts/{partId}","eventType":"providers/cloud.firestore/eventTypes/document.write","service":"firestore.googleapis.com"}}
> [2021-01-07T16:51:58.845Z] [worker-~diagnostic~-7e113a21-2bae-405a-b858-1c47c2e4205d]: IDLE {"metadata":{"emulator":{"name":"functions"},"message":"[worker-~diagnostic~-7e113a21-2bae-405a-b858-1c47c2e4205d]: IDLE"}}
>

**Comment by bkendall** [comment]
Does this work on `9.1.2` or `9.1.0`? We had an issue in `9.1.1` that we fixed this morning.

**Comment by JSmithOner** [comment]
@bkendall  the same I've tested all three of these. my callable functions are recognised when running `npm run build` but the process still hangs. It happened after restarting the server. Thanks in advance

**Comment by bkendall** [comment]
@JSmithOner is it possible to create a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for this issue? Stopping and starting the emulator isn't enough to trigger this in my testing. If you're also using a build step, please be sure to remove the old files and re-build - sometimes old files can cause havoc in situations where file structure changes.

**Comment by JSmithOner** [comment]
ok sorry I finally have a reproducible example.
`mkdir foldername`
`cd foldername`
`firebase init`
choose all options
paste this to `index.ts` in `foldername/functions/src`
`cd functions`
`npm run build`
`cd ..`
`firebase emulators:start`

and here is my function in `index.ts`

@bkendall  Please let me know if you need more infos

```
import * as admin from 'firebase-admin';
import * as functions from 'firebase-functions';

admin.initializeApp();

const firestore = admin.firestore();


exports.updateVendoredPart = functions.firestore.document('vendors/{vendorId}/parts/{partId}').onWrite(
    (change, context) => {
        const vendorId = context.params.vendorId;
        const partId = context.params.partId;
        const currentDocGlobalChangesRef = firestore.collection(`vendors/${vendorId}/parts/${partId}/changes`).doc('global');
        const currentCollectionChangesRef = firestore.collection(`vendors/${vendorId}/parts/${partId}/changes`);
        const currentDocChangesRef = currentCollectionChangesRef.doc();
        const before = <any>change.before.data()
        const after = <any>change.after.data()

        if (!change.before.exists)
            return (Promise.resolve());
        else if (!change.after.exists)
            return (Promise.resolve());
        else if (change.before.exists && !before.archived && !after.archived){

            let changeDocIds = <any[]>[];
            before.global = false;

            return firestore.runTransaction(
                (t) => {
                    return t.get(currentDocGlobalChangesRef).then(
                        (globalChangesResponse) => {
                            const globalData = globalChangesResponse.data();
                            if (globalData)
                                changeDocIds = globalData.changesDocIds;
                            return (t.set(currentDocChangesRef, before));             
                        }
                    )
                    .then(
                        () => {
                            const previousId = changeDocIds.length ? changeDocIds[changeDocIds.length - 1].id : "np";
                            changeDocIds.push(
                                {
                                    id: currentDocChangesRef.id,
                                    previous: previousId,
                                    timestamp: (before.update_date ? before.update_date : before.creation_date).toDate().getTime(),
                                    version: before['version'],
                                    comment: before['revision_comment'],
                                }
                            );
                            if (changeDocIds.length > 10 && after.overwrite){
                                const deleteDocObj = changeDocIds.splice(0, 1);
                                changeDocIds[0].prev = "np";
                                t.delete(currentCollectionChangesRef.doc(deleteDocObj[0].id))
                            }
                            return (t.set(currentDocGlobalChangesRef, {
                                        global: true,
                                        key: after.compound_key,
                                        changesDocIds: changeDocIds
                                    }, {
                                        merge:true
                                    }
                                )
                            )              
                        }
                    ).catch((err) => functions.logger.log(err))
                }
            )
        }
        else
            return (Promise.resolve().then().catch(err => console.log(err)));
    }
);
```

**Comment by JSmithOner** [comment]
@bkendall  just saw that one of my Promise wasn't using `catch` now it's working, I'll try this with the other ones and get back to you if the problem is still here. Thanks

**Comment by samtstern** [comment]
@JSmithOner thanks for following up on this one!  I think actually if you had waited longer this would have eventually errored out due to our timeout handling (default 60s).  I think that's the best we can do as far as logging for hanging promises, it's hard to tell if something is hanging or if it's just taking a while!
