### ISSUE TITLE
Cannot start emulator with only 'beforeSignIn' blocking function

### ISSUE THREAD

**Issue by dvoloshyn** [firebase/firebase-tools#4617]
### [REQUIRED] Environment info

**firebase-tools:** 11.0.1

**Platform:** Manjaro Linux

### [REQUIRED] Test case

`
export const beforeSignIn = auth.user().beforeSignIn((user, context) => {
});
`

### [REQUIRED] Steps to reproduce

1. Create a firebase blocking function 'beforeSignIn', do not create a function 'beforeCreate'
2. Try to start local emulator for functions and auth
3. Observe errors
`
✔  functions[us-central1-beforeSignIn]: providers/cloud.auth/eventTypes/user.beforeSignIn function initialized (http://localhost:5001/incubator-5dol/us-central1/beforeSignIn).
⚠  Error updating blocking functions config to the auth emulator: FirebaseError: HTTP Error: 400, INVALID_BLOCKING_FUNCTION: ((Expected an absolute URI with valid scheme and host.))

`
5. Now additionally add 'beforeCreate'
6. Observe emulators starting successfully
7. A had a quick glance at the source code and it looks like blocking functions config by default is initialized to ''. When only one function is present still both functions are being registered and don't pass validation. Maybe registering only those that are initialized should fix the issue.

### [REQUIRED] Expected behavior

Emulators should start successfully even if only one of two blocking functions is present

### [REQUIRED] Actual behavior

`
✔  functions[us-central1-beforeSignIn]: providers/cloud.auth/eventTypes/user.beforeSignIn function initialized (http://localhost:5001/incubator-5dol/us-central1/beforeSignIn).
⚠  Error updating blocking functions config to the auth emulator: FirebaseError: HTTP Error: 400, INVALID_BLOCKING_FUNCTION: ((Expected an absolute URI with valid scheme and host.))

`

**Comment by patzj** [comment]
I had to start the emulators separately. Functions first. After the functions initialized, I'm starting auth in a separate terminal.

**Comment by fbarzin** [comment]
I ran into the same issue on the emulator. So, I tried to deploy it to Firebase to see if it goes through and I got the following log on my console:

```
HTTP Error: 400, OPERATION_NOT_ALLOWED : Blocking Functions may only be configured for GCIP projects.
```

Seems like `auth.beforeCreate`  trigger is only available on Google Cloud Identity Platform (GCIP) which explains why [Firebase documentation](https://firebase.google.com/docs/functions/auth-events) doesn't mention anything about it.

**Comment by colerogers** [comment]
Hi everyone, sorry for the trouble. I'm seeing that you folks are using `11.0.1`. This issue should have been fixed in [version 11.2.0](https://github.com/firebase/firebase-tools/releases/tag/v11.2.0). Can you all update to that version or the latest version and re-try the emulator. Thanks!

**Comment by bkendall** [comment]
(With no responses, I'm going to close this out.)

**Comment by cybex-dev** [comment]
@colerogers 

Not sure if I'm missing something but looks like this issue persists.

---

**OS: 5.18.12-arch1-1**
**npm: v8.5.1**
**Node: v17.6.0**

**Firebase-tools**
```bash
$ firebase -V
11.2.0
```

Using `npm list`
```bash
$ npm list firebase-tools -g
/home/cybex/.nvm/versions/node/v17.6.0/lib
└── firebase-tools@11.2.0
```

---

### MCVE

**Code Sample:**
```ts
import * as admin from "firebase-admin";
import {auth} from "firebase-functions";
import {credential} from "firebase-admin";
import applicationDefault = credential.applicationDefault;

// / Workaround for multiple Firebase Apps issue: "Error: The default Firebase app already exists."
// / Source: https://github.com/firebase/firebase-tools/issues/1532#issuecomment-812562512
if (admin.apps.length === 0) {
    admin.initializeApp({
        credential: applicationDefault(),
        databaseURL: "https://myapp-api-default-rtdb.firebaseio.com",
        storageBucket: "gs://myapp-api.appspot.com",
    },);
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const beforeSignIn = auth.user().beforeSignIn((user, context) => {
    console.log("auth beforeSignIn");
});

```

**Deploy**

```bash
$ firebase deploy --only functions

=== Deploying to 'myapp-api'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint --ext .js,.ts .

Running command: npm --prefix "$RESOURCE_DIR" run build

> build
> tsc

✔  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing codebase default for deployment
i  functions: preparing functions directory for uploading...
i  functions: packaged /home/cybex/WebstormProjects/myapp-backend-server/myapp-backend-server/functions (112.19 KB) for uploading
i  functions: ensuring required API identitytoolkit.googleapis.com is enabled...
✔  functions: required API identitytoolkit.googleapis.com is enabled
✔  functions: functions folder uploaded successfully
i  functions: updating Node.js 16 function beforeSignIn(us-central1)...
HTTP Error: 400, OPERATION_NOT_ALLOWED : Blocking Functions may only be configured for GCIP projects.

Functions deploy had errors with the following functions:
        beforeSignIn(us-central1)
i  functions: cleaning up build files...

Error: There was an error deploying functions

Having trouble? Try again or contact support with contents of firebase-debug.log
```

**firebase-debug.log snippet**
Cleaned out some sensitive bits but the important parts are here including `HTTP/400` response and `firebase-tools` deploy stacktrace.
```log
[debug] [2022-08-04T01:31:54.692Z] >>> [apiv2][body] PATCH https://identitytoolkit.googleapis.com/admin/v2/projects/myapp-api/config {"blockingFunctions":{"triggers":{"beforeSignIn":{"functionUri":"https://us-central1-myapp-api.cloudfunctions.net/beforeSignIn"}},"forwardInboundCredentials":{"accessToken":false,"idToken":false,"refreshToken":false}}}
[debug] [2022-08-04T01:31:55.350Z] <<< [apiv2][status] PATCH https://identitytoolkit.googleapis.com/admin/v2/projects/myapp-api/config 400
[debug] [2022-08-04T01:31:55.350Z] <<< [apiv2][body] PATCH https://identitytoolkit.googleapis.com/admin/v2/projects/myapp-api/config {"error":{"code":400,"message":"OPERATION_NOT_ALLOWED : Blocking Functions may only be configured for GCIP projects.","status":"INVALID_ARGUMENT"}}
[error] HTTP Error: 400, OPERATION_NOT_ALLOWED : Blocking Functions may only be configured for GCIP projects.
[debug] [2022-08-04T01:31:55.356Z] Total Function Deployment time: 54016
[debug] [2022-08-04T01:31:55.356Z] 1 Functions Deployed
[debug] [2022-08-04T01:31:55.356Z] 1 Functions Errored
[debug] [2022-08-04T01:31:55.356Z] 0 Function Deployments Aborted
[debug] [2022-08-04T01:31:55.356Z] Average Function Deployment time: 54015
[info] 
[info] Functions deploy had errors with the following functions:
	beforeSignIn(us-central1)
...

[debug] [2022-08-04T01:32:02.650Z] Could not find image for function projects/myapp-api/locations/us-central1/functions/beforeSignIn
[debug] [2022-08-04T01:32:02.982Z] <<< [apiv2][status] GET https://artifactregistry.googleapis.com/v1beta2/projects/myapp-api/locations/us-central1/operations/1232d971-cd83-4966-826f-47fc7ed98776 200
[debug] [2022-08-04T01:32:02.982Z] <<< [apiv2][body] GET https://artifactregistry.googleapis.com/v1beta2/projects/myapp-api/locations/us-central1/operations/1232d971-cd83-4966-826f-47fc7ed98776 {"name":"projects/myapp-api/locations/us-central1/operations/1232d971-cd83-4966-826f-47fc7ed98776","metadata":{"@type":"type.googleapis.com/google.devtools.artifactregistry.v1beta2.OperationMetadata"},"done":true,"response":{"@type":"type.googleapis.com/google.protobuf.Empty"}}
[debug] [2022-08-04T01:32:03.422Z] Error: Failed to register blocking trigger function beforeSignIn in region us-central1
    at /home/cybex/.nvm/versions/node/v17.6.0/lib/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:41:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Fabricator.registerBlockingTrigger (/home/cybex/.nvm/versions/node/v17.6.0/lib/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:475:9)
    at async Fabricator.setTrigger (/home/cybex/.nvm/versions/node/v17.6.0/lib/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:432:13)
    at async Fabricator.updateEndpoint (/home/cybex/.nvm/versions/node/v17.6.0/lib/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:144:9)
    at async handle (/home/cybex/.nvm/versions/node/v17.6.0/lib/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:77:17)
[error] 
[error] Error: There was an error deploying functions
```

**Comment by colerogers** [comment]
@cybex-dev It looks like you have an error deploying a function, not running the emulator. In the future, please open a new issue instead.

The error message you're receiving is from Google Cloud Identity Platform. [According the prerequisites section in the Firebase docs](https://firebase.google.com/docs/auth/extend-with-blocking-functions#before_you_begin):
```
To use blocking functions you must upgrade your Firebase project to Firebase Authentication with Identity Platform. If you haven't already upgraded, do so first.
```

That is a **required** step before you can use/deploy any blocking functions.

**Comment by dzivoing** [comment]
I am using it with Identity platform it works when deployed but it doesn't work in emulator for some reason

**Comment by cupojoe** [comment]
Is someone looking into why blocking auth functions v2 do not work in the emulator?

Auth events do not trigger them and the console prints out:

```
POST http://localhost:9099/identitytoolkit.googleapis.com/v1/accounts:lookup?key=*** 400 (Bad Request)
```
