### ISSUE TITLE
firebase deploy --only hosting fails with webframeworks experiment enabled

### ISSUE THREAD

**Issue by lesnitsky** [firebase/firebase-tools#5268]
### Environment info

**firebase-tools:**
11.16.1

**Platform:**
macOS arm

### Steps to reproduce

- create Next.js app with `yarn create next-app --typescript`
- initialise firebase hosting
- run `firebase deploy --only hosting`

### Expected behavior

deploy succeeded

### Actual behavior

Deploy fails

<details><summary>firebase-debug.log</summary>

```
[debug] [2022-11-25T15:10:57.874Z] Error: The package "esbuild-darwin-64" could not be found, and is needed by esbuild.

If you are installing esbuild with npm, make sure that you don't specify the
"--no-optional" flag. The "optionalDependencies" package.json feature is used
by esbuild to install the correct binary executable for your current platform.
    at generateBinPath (/Users/lesnitsky/.cache/firebase/tools/lib/node_modules/firebase-tools/node_modules/esbuild/lib/main.js:1786:15)
    at esbuildCommandAndArgs (/Users/lesnitsky/.cache/firebase/tools/lib/node_modules/firebase-tools/node_modules/esbuild/lib/main.js:1850:33)
    at ensureServiceIsRunning (/Users/lesnitsky/.cache/firebase/tools/lib/node_modules/firebase-tools/node_modules/esbuild/lib/main.js:2015:25)
    at Object.build (/Users/lesnitsky/.cache/firebase/tools/lib/node_modules/firebase-tools/node_modules/esbuild/lib/main.js:1906:26)
    at ɵcodegenFunctionsDirectory (/Users/lesnitsky/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/frameworks/next/index.js:190:23)
    at async prepareFrameworks (/Users/lesnitsky/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/frameworks/index.js:302:84)
    at async deploy (/Users/lesnitsky/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/deploy/index.js:53:13)
[error] 
[error] Error: An unexpected error has occurred.
```

</details>

**Comment by digvan** [comment]
same issue

**Comment by jamesdaniels** [comment]
Right now esbuild is need for the nextjs ssr integration while we get a handle on turbo/swcpack, have you tried manually adding esbuild as a devDependency?

**Comment by lesnitsky** [comment]
@jamesdaniels, yes, I did – didn't help. Stacktrace suggests firebase tools expect esbuild in `.cache/firebase` folder.
I was trying to install the dependency there, no luck either.

Quick note: this happens only on macos arm, I was able to deploy same app from github actions.

**Comment by digvan** [comment]
I fixed it with installing node 16 with mac pkg file.

**Comment by erick303** [comment]
Getting the same error, tried switching to node v16.18.1 still the same issue

```
firebase deploy

...

Error: The package "esbuild-darwin-64" could not be found, and is needed by esbuild.

If you are installing esbuild with npm, make sure that you don't specify the
"--no-optional" flag. The "optionalDependencies" package.json feature is used
by esbuild to install the correct binary executable for your current platform.
    at generateBinPath (/Users/<user>/.cache/firebase/tools/lib/node_modules/firebase-tools/node_modules/esbuild/lib/main.js:1786:15)
    at esbuildCommandAndArgs (/Users/<user>/.cache/firebase/tools/lib/node_modules/firebase-tools/node_modules/esbuild/lib/main.js:1850:33)
    at ensureServiceIsRunning (/Users/<user>/.cache/firebase/tools/lib/node_modules/firebase-tools/node_modules/esbuild/lib/main.js:2015:25)
    at Object.build (/Users/<user>/.cache/firebase/tools/lib/node_modules/firebase-tools/node_modules/esbuild/lib/main.js:1906:26)
    at ɵcodegenFunctionsDirectory (/Users/<user>/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/frameworks/next/index.js:190:23)
    at async prepareFrameworks (/Users/<user>/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/frameworks/index.js:302:84)
    at async deploy (/Users/<user>/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/deploy/index.js:53:13)
```

**Comment by bhaskarmurthy** [comment]
Same issue here.

**Comment by romain22222** [comment]
I also confirm having the same issue with a next app, but under windows

**Comment by kirittanna** [comment]
```
[debug] [2022-12-14T03:58:31.948Z] Error: The package "esbuild-darwin-64" could not be found, and is needed by esbuild.

If you are installing esbuild with npm, make sure that you don't specify the
"--no-optional" flag. The "optionalDependencies" package.json feature is used
by esbuild to install the correct binary executable for your current platform.
```

Yes, facing this issue on a M1 Mac running OSX 13 and Node v16.18.1.

**Comment by akshayknz** [comment]
Having an issue where webframreworks experiement automatically try creating functions in my free firebase plan while I'm deploying static website.

**Comment by jamesdaniels** [comment]
@akshayknz there is a heuristic to determine if a Cloud Function is needed for proper functionality of your Next.js app. In the upcoming version of the CLI we will be logging the reasons why. If you nix those it will deploy an entirely static app to Firebase Hosting. 

Likely culprits: use of the App directory in Next 13 (this is fairly unstable so we can't optimize it yet), Image Optimization, and advanced rewrites/redirects/headers in your next.config.js. API routes, ISR, and route fallbacks also require Cloud Functions but that's probably not as surprising.

**Comment by jamesdaniels** [comment]
If i were to guess this is because firebase-tools is shrinkwrapped. I suspect if I move to `npx esbuild ...` on deploy things will function better in other environments but I don't have an M1 mac to test this on.

**Comment by MarcosNotch** [comment]
Hi! I´m having a similar problem but the log of the firebase deploy says:

TypeError: Cannot read properties of null (reading 'toString')
    at ɵcodegenFunctionsDirectory (C:\Users\Usuario\AppData\Roaming\npm\node_modules\firebase-tools\lib\frameworks\next\index.js:220:18)
    at async prepareFrameworks (C:\Users\Usuario\AppData\Roaming\npm\node_modules\firebase-tools\lib\frameworks\index.js:305:84)
    at async deploy (C:\Users\Usuario\AppData\Roaming\npm\node_modules\firebase-tools\lib\deploy\index.js:53:13)
[error] 
[error] Error: An unexpected error has occurred.

any help with this? Im using next version 13.0.7
this only happens with next, if I deploy a regular react proyect everything works fine

**Comment by jamesdaniels** [comment]
@MarcosNotch that is likely a different issue, if you run `npm ls --omit=dev --all --json` do you get an error? I should have put a success check on that

**Comment by MarcosNotch** [comment]
@jamesdaniels no errors if I run that command, just prints the dependencies

**Comment by SitequestCarlo** [comment]
@MarcosNotch I have that same problem

**Comment by MiftahClassifieds** [comment]
same issue as @MarcosNotch

**Comment by DimanthaG** [comment]
anyone found a solution for @MarcosNotch 's issue?
