### ISSUE TITLE
Firebase Deploy - Failed to configure trigger

### ISSUE THREAD

**Issue by strongishdeveloper** [firebase/firebase-tools#5429]
### Environment info

**firebase-tools:** 11.20.0

**Platform:** Windows

### Test case
Fresh Firebase functions project using firebase init functions

```
const admin = require("firebase-admin");
const functions = require("firebase-functions");
const firestore = require("firebase-admin/firestore");

admin.initializeApp();

const db = firestore.getFirestore();

exports.testOnSummaryUpdated = functions.firestore
    .document("/summary/{id}")
    .onWrite((change, context) => {
        console.log("Summary doc has triggered onWrite");
    });
```

### Steps to reproduce

1. Deploy to Firebase Functions

###  Expected behavior

Successful deployment of functions package

### Actual behavior

```
[debug] [2023-01-16T04:17:16.246Z] {
  "endpoint": {
    "id": "testOnSummaryUpdated",
    "project": "asset-compliance",
    "region": "us-central1",
    "entryPoint": "testOnSummaryUpdated",
    "platform": "gcfv1",
    "runtime": "nodejs16",
    "eventTrigger": {
      "eventType": "providers/cloud.firestore/eventTypes/document.write",
      "retry": false,
      "eventFilters": {
        "resource": "projects/asset-compliance/databases/(default)/documents/summary/{id}"
      }
    },
    "labels": {
      "deployment-tool": "cli-firebase"
    },
    "serviceAccount": null,
    "ingressSettings": null,
    "availableMemoryMb": null,
    "timeoutSeconds": null,
    "maxInstances": null,
    "minInstances": null,
    "vpc": null,
    "environmentVariables": {
      "FIREBASE_CONFIG": "{\"projectId\":\"asset-compliance\",\"storageBucket\":\"asset-compliance.appspot.com\",\"locationId\":\"australia-southeast1\"}",
      "GCLOUD_PROJECT": "asset-compliance",
      "EVENTARC_CLOUD_EVENT_SOURCE": "projects/asset-compliance/locations/us-central1/functions/testOnSummaryUpdated"
    },
    "codebase": "default",
    "targetedByOnly": false,
    "hash": "03154987cdea12a274f4732eab2674d5ad36056e"
  },
  "op": "create",
  "original": {
    "name": "FirebaseError",
    "children": [],
    "exit": 1,
    "message": "Failed to configure trigger event-type:providers/cloud.firestore/eventTypes/document.write resource:projects/asset-compliance/databases/(default)/documents/summary/{id} service:firestore.googleapis.com",
    "status": 13
  }
}
[debug] [2023-01-16T04:17:16.494Z] Error: Failed to create function testOnSummaryUpdated in region us-central1
    at C:\Users\James\AppData\Roaming\npm\node_modules\firebase-tools\lib\deploy\functions\release\fabricator.js:48:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Fabricator.createV1Function (C:\Users\James\AppData\Roaming\npm\node_modules\firebase-tools\lib\deploy\functions\release\fabricator.js:177:32)
    at async Fabricator.createEndpoint (C:\Users\James\AppData\Roaming\npm\node_modules\firebase-tools\lib\deploy\functions\release\fabricator.js:129:13)
    at async handle (C:\Users\James\AppData\Roaming\npm\node_modules\firebase-tools\lib\deploy\functions\release\fabricator.js:85:17)
```

**Comment by strongishdeveloper** [comment]
Just to add: This error appears with all Firebase Triggers (onDelete, onCreate, onWrite, onUpdate)

**Comment by FortySL** [comment]
Hello, same problem here. 
My functions was working last week, but when I change the name and want to redeploy it today, I got the error **"Failed to configure trigger event-type:providers/cloud.firestore/eventTypes/document.create"**

With whatever I did, this error still exists and it comes with all 4 methods (**onCreate, onUpdate, onWrite and onDelete**)

**Comment by JarnoRFB** [comment]
Also happens to me, but also happens with `firebase-tools` 11.19.0, so maybe it is rather a problem in the backend.

What i noticed when running with `--debug` option is that the `environmentVariables.EVENTARC_CLOUD_EVENT_SOURCE` is not matching the function name that causes the error.

**Comment by Thaanu2001** [comment]
Same error, It gets for the Firebase Triggers and Rest APIs deploys successfully

**Comment by JarnoRFB** [comment]
Now it worked again for me.

**Comment by Thaanu2001** [comment]
Try adding `/` before the document reference worked for me.

**Comment by strongishdeveloper** [comment]
Seems to have been resolved, must have been a backend issue.

**Comment by dylanrandle** [comment]
I am still getting this issue. 

```
Failed to configure trigger for event-type:providers/cloud.firestore/eventTypes/document.{create,update,delete}
```

If I keep trying enough times it eventually works. I had to retry 4 times to get it to work.

**Comment by olegkorol** [comment]
I was experiencing the same issue when deploying a Firebase project with GitHub Actions.
In my case, the service account used for the deployment was missing the `Eventarc Admin` role. Eventarc is used in the background for Firebase triggers.

**Comment by dylanrandle** [comment]
Still getting this error. I have retried about 9-10 times and still not working.

**Comment by javabudd** [comment]
Still getting this error non-deterministically. This makes reliable deploys pretty much impossible. Please for the love of god fix your deploy rate limits.
