### ISSUE TITLE
Error deploying v2 Firebase function containing a dash (replaces dash with dot in entry point after deployment)

### ISSUE THREAD

**Issue by trevor-rex** [firebase/firebase-tools#5506]
### [REQUIRED] Environment info

**firebase-tools:**
11.22.0

**Platform:**
macOS

### [REQUIRED] Test case

`firebase deploy --only functions:my-function` with the below source code

### [REQUIRED] Steps to reproduce

In my use case, I am trying to modify the function name at deploy time by converting from camelCase to kebab-case to conform to FCFv2 naming standards while not having a single lowercase-token function name.

My index.js is as follows:
```
for (let f = 0, fl = files.length; f < fl; f++) {
  const file = files[f];
  // camelCase makes it so we can have directory file names
  // (e.g. "db/users/onwrite.f.js" -> dbUsersOnWrite)

  // Strip off '.f.js'
  const filePrefix = (file.split("/").pop() as string).slice(0, -5);

  const functionName = kebabCase(filePrefix);

  if (
    !process.env.FUNCTION_NAME ||
    process.env.FUNCTION_NAME === functionName
  ) {
    const actualFunction = require(file)[filePrefix];
    // NOTE: Functions must have the same name as their file name for this to work
    exports[functionName] = actualFunction;
  }
}

```

And my function code is as follows:
```
import { https } from "firebase-functions/v2";

export const myFunction = https.onCall(...);
```

When I deploy `my-function`, I get the following error:
```
i  functions: creating Node.js 16 function my-function(us-central1)...
Could not create or update Cloud Run service run-analysis-engine, Container Healthcheck failed. The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information.

Logs URL: https://console.cloud.google.com/logs/viewer?project=my-project&resource=cloud_run_revision/service_name/my-function/revision_name/my-function-00001-[redacted]
For more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start

Functions deploy had errors with the following functions:
	my-function(us-central1)
```

Additionally, here is info from the logs:
```
DEFAULT 2023-02-10T22:50:25.000000Z Function 'my.function' is not defined in the provided module.
DEFAULT 2023-02-10T22:50:25.000000Z Did you specify the correct target function to execute?
DEFAULT 2023-02-10T22:50:25.000000Z Could not load the function, shutting down.
WARNING 2023-02-10T22:50:25.000000Z Container called exit(1).
```

In the logs and the functions console, the executed function/entry point is `my.function` and not `my-function`. Why is the dash being replaced with a dot in both of these places? I have also attempted to declare my function this way:
```
const myFunction = https.onCall(...);

module.exports = {
  'my-function': myFunction
}
```
with the same result.

I do also want to note that if I repeat this behavior (including leaving the function file name and function declaration in camelCase) but instead `.toLowerCase()` the function, everything works perfectly.

Is there any possible way to deploy a Firebase Cloud Function v2 with a hyphen in the first place? I am trying to work around the character set issue until uppercase letters are eventually allowed, but it seems my team is stuck with lowercasing our function names if we want to convert a function to v2, unless there is a way around this issue.

### [REQUIRED] Expected behavior

The function deploys with its entry point as `my-function`, or at least does not error when its name is `my-function` and its entry point is `my.function`.

### [REQUIRED] Actual behavior

The function's entry point gets swapped to `my.function` and the container health fails and the function cannot deploy. I also have to delete this function before I can ever deploy another.

This is a similar issue to https://github.com/firebase/firebase-functions/issues/1131

I do not believe the debug logs contain any additional useful information.

**Comment by buu700** [comment]
I'm running into this as well.

**Comment by AntonAI** [comment]
Any update on this? This is still happening and is a critical error preventing any Firebase Function Gen2 deployments where function names contain hyphens.

**Comment by colerogers** [comment]
Hey folks sorry for the headache. It looks like our docs had a mistake and should not state that you can use `-`'s in function names. In JS/TS, you can't use dashes in variable names, so Firebase Functions used them to signal the [group functions](https://firebase.google.com/docs/functions/beta/organize-functions#group_functions) feature. Apologies for the confusion in the docs and they are currently being updated so nobody else runs into this.

**Comment by buu700** [comment]
Got it, thanks for clarifying that. If that's the case, are there any plans to reintroduce support for capital letters? Alternatively, do (or will) underscores work?

**Comment by colerogers** [comment]
@buu700 We're currently in the process of planning out our roadmap for the year, but the naming of functions is limited to k8 resource names - https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names

Under the hood, your function is actually a Cloud Run container that conforms to these standards

**Comment by buu700** [comment]
Got it, that makes sense. Having to conform to both k8s label name requirements and JS variable name requirements is a rather unfortunate overlap.

**Comment by YannicEl** [comment]
> @buu700 We're currently in the process of planning out our roadmap for the year, but the naming of functions is limited to k8 resource names - https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
> 
> Under the hood, your function is actually a Cloud Run container that conforms to these standards

Do I understand that correctly that V2 function names can only contain lowercase alphanumeric characters?

**Comment by trevor-rex** [comment]
> > @buu700 We're currently in the process of planning out our roadmap for the year, but the naming of functions is limited to k8 resource names - https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
> > Under the hood, your function is actually a Cloud Run container that conforms to these standards
> 
> Do I understand that correctly that V2 function names can only contain lowercase alphanumeric characters?

Yes apparently

**Comment by Velkamhell97** [comment]
Any update ? this means that i must to name a function `onordercreated` instead  of `onOrderCreated` ?

**Comment by trevor-rex** [comment]
> Any update ? this means that i must to name a function `onordercreated` instead of `onOrderCreated` ?

This should be fixed now on the latest version; uppercase characters are allowed now.

**Comment by unbounded26** [comment]
Still facing this issue with the update, details are [here ](https://stackoverflow.com/questions/76990628/firebase-functions-could-not-create-or-update-cloud-run-service-container-heal). Here is the sample code of  `index.js`
```
const calledFunctionName = process.env.K_SERVICE;
if (!calledFunctionName || calledFunctionName === "addCourseData") {
  const {onRequest} = require("firebase-functions/v2/https");

  // Take the email and adds an entry to Firestore with Course data
  exports.addCourseData = onRequest(async (request, response) => {
    return await (await require("./my-functions/course/add-course-data-function"))
        .addCourseData(request, response);
  });
}
```
I'm not using hyphens in function names, but in directory & file names only, is it the reason for the error described in the link???

NOTE: the functions, in the file were working properly already, tested many times, but since made the update it is causing the  issues

**Comment by unbounded26** [comment]
I need to change this line
```javascript
if (!calledFunctionName || calledFunctionName === "addCourseData")
```
to 
```javascript
if (!calledFunctionName || calledFunctionName === "addcoursedata")
```
as **`process.env.K_SERVICE` returns the lower alphabets ONLY**, instead of camelCase or names-with-hyphens.

Finally, I found the answer to my issue after 2 days of researching and debugging. Maybe it save someone's time!

**Comment by marcusicaro** [comment]
Hey, I've found a solution to this:

```
exports.test = {
    coffee,
};

exports.login = {
    auth,
    recoverPassword,
};

```

Doing this you'd get the following route: `/test-coffee` or `login-auth` or `login-recoverPassword`.

You simply create an object containing what you want on a specific route, rename the function that the route is going to acces to what you want and that's it.

Happy new year, folks.

**Comment by erosostolato** [comment]
@marcusicaro it worked! Thank you!

**Comment by marcusicaro** [comment]
> @marcusicaro it worked! Thank you!

Glad it helped :)
