### ISSUE TITLE
firebase deploy hosting with webframeworks experiment fails on arm mac (Unsupported platform for inotify@1.4.6)

### ISSUE THREAD

**Issue by daihuaye** [firebase/firebase-tools#5558]
### [REQUIRED] Environment info

**firebase-tools: 11.24.0**

**Platform: macOS arm**

### [REQUIRED] Steps to reproduce

- create new Next.js project
- enable webframeworks experiment
- run firebase init hosting
- run `firebase deploy`

### [REQUIRED] Expected behavior

deploy succeeds

### [REQUIRED] Actual behavior

Error
```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for inotify@1.4.6: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64
```

**firebase-debug.log**
```
23 verbose stack Error: Unsupported platform for inotify@1.4.6: wanted {"name":"inotify","version":"1.4.6","engines":{"node":">=0.8"},"os":["linux"],"dependencies":{"bindings":"^1.3.1","nan":"^2.12.1"},"optionalDependencies":{},"peerDependenciesMeta":{},"devDependencies":{},"bundleDependencies":false,"peerDependencies":{},"deprecated":false,"_resolved":"https://registry.npmjs.org/inotify/-/inotify-1.4.6.tgz","_integrity":"sha512-WW8/uqIA04O3AePQVe/Ms3ZLR0yGamaz8YOEpaXc4WBAGOPZfzu58wWErEPSUYaPyDrJRIeCn6PEIQgC1ZyQ5w==","_shasum":"c5a51852df1647d1a589d46c4baa2771ed36b8d2","_shrinkwrap":null,"_id":"inotify@1.4.6","_from":"inotify@>= 0.1.6","_requested":{"type":"range","registry":true,"raw":"inotify@>= 0.1.6","name":"inotify","escapedName":"inotify","rawSpec":">= 0.1.6","saveSpec":null,"fetchSpec":">= 0.1.6"},"_spec":"inotify@>= 0.1.6","_where":"/Users/account/Projects/nextjs-app/project/.firebase/project/functions/node_modules/dev"} (current: {"os":"darwin","cpu":"x64"})
23 verbose stack     at checkPlatform (/snapshot/firepit/node_modules/npm/node_modules/npm-install-checks/index.js:46:14)
23 verbose stack     at thenWarnEngineIssues (/snapshot/firepit/node_modules/npm/lib/install/validate-args.js:63:5)
23 verbose stack     at /snapshot/firepit/node_modules/npm/node_modules/iferr/iferr.js:3:64
23 verbose stack     at checkEngine (/snapshot/firepit/node_modules/npm/node_modules/npm-install-checks/index.js:25:10)
23 verbose stack     at /snapshot/firepit/node_modules/npm/lib/install/validate-args.js:60:3
23 verbose stack     at resolveWithNewModule (/snapshot/firepit/node_modules/npm/lib/install/deps.js:677:10)
23 verbose stack     at /snapshot/firepit/node_modules/npm/lib/install/deps.js:600:7
23 verbose stack     at /snapshot/firepit/node_modules/npm/node_modules/iferr/iferr.js:3:64
23 verbose stack     at /snapshot/firepit/node_modules/npm/node_modules/call-limit/call-limit.js:28:43
23 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:78:11)
24 verbose pkgid inotify@1.4.6
...
28 verbose node v16.16.0
29 verbose npm  v6.14.18
30 error code EBADPLATFORM
31 error notsup Unsupported platform for inotify@1.4.6: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
32 error notsup Valid OS:    linux
32 error notsup Valid Arch:  any
32 error notsup Actual OS:   darwin
32 error notsup Actual Arch: x64
33 verbose exit [ 1, true ]
```

**Comment by kuyazee** [comment]
Any updates on this?

**Comment by jamesdaniels** [comment]
We no longer pin the dependencies, this issue should be resolved.

**Comment by juanpa097** [comment]
Hello @jamesdaniels,

I'm still facein this issue with 12.2.1. This is my stack:
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for inotify@1.4.6: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/juanpenaloza/.npm/_logs/2023-05-30T17_59_31_895Z-debug.log
```

**Comment by Startouf** [comment]
Hello, I'm trying to deploy an Angular 17 application with SSR using the newest guides and `application` builder, and I still run into an error when running `firebase deploy --debug` which seems to be related to Vite.

(I am running the Angular app fine using ng serve)

```
[2023-12-23T16:59:54.264Z] Error: Cannot find module @rollup/rollup-darwin-x64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/Users/utilisateur/dev/rockit-website/frontend/node_modules/vite/node_modules/rollup/dist/native.js:87:9)
    at Object.<anonymous> (/Users/utilisateur/dev/rockit-website/frontend/node_modules/vite/node_modules/rollup/dist/native.js:96:48)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._compile (pkg/prelude/bootstrap.js:1890:32)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)

Error: An unexpected error has occurred.
```

It might be related to https://github.com/vitejs/vite/issues/15122 or something similar

My specs
- Macbook m2 macOs 14.2 (23C64)
- Node v18.19.0
- Firebase 13.0.2
- Angular 17
