### ISSUE TITLE
$RESOURCE_DIR predeploy variable

### ISSUE THREAD

**Issue by dylanjmcdonald** [firebase/firebase-tools#610]
### Version info

3.17.1

### Steps to reproduce

Set up cloud functions via `firebase init` and selected TypeScript
Run `firebase deploy --only functions`

### Expected behavior

Expecting firebase-tools to deploy the cloud functions.

### Actual behavior

Receive the following error message:

deploying functions
Running command: npm --prefix $RESOURCE_DIR run lint
npm ERR! path C:\PATH_REMOVED_FOR_SHARING_PURPOSES\\$RESOURCE_DIR\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\PATH_REMOVED_FOR_SHARING_PURPOSES\\$RESOURCE_DIR\package.json'
npm ERR! enoent This is related to npm not being able to find a file.

Is this something that needs to be set up manually or should firebase-tools take care of this? I am not seeing any documentation for this.

**Comment by laurenzlong** [comment]
@dylanjmcdonald What platform are you using?

**Comment by tinaliang** [comment]
Could you make sure your functions folder has a package.json file? I'm unable to recreate this error.

**Comment by dylanjmcdonald** [comment]
@laurenzlong Windows 10, node v8.9.4, firebase-tools v3.17.1. Functions folder does indeed have a package.json file.

**Comment by tinaliang** [comment]
Does the command work for you if you replace $RESOURCE_DIR with %RESOURCE_DIR%?

**Comment by dylanjmcdonald** [comment]
@tinaliang It does work!

**Comment by ScottMorris** [comment]
I'm seeing this on Windows as well, but we use both Windows and Linux, so is there away to handle both platforms?

**Comment by nico75005** [comment]
Same here. I followed [this tutorial](https://firebase.google.com/docs/functions/get-started) and activated lint. When I execute (on a Mac)
```
npm --prefix $RESOURCE_DIR run lint
```

I get this error:
```
Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
    explore, get, help, help-search, i, init, install,
    install-test, it, link, list, ln, login, logout, ls,
    outdated, owner, pack, ping, prefix, profile, prune,
    publish, rb, rebuild, repo, restart, root, run, run-script,
    s, se, search, set, shrinkwrap, star, stars, start, stop, t,
    team, test, token, tst, un, uninstall, unpublish, unstar,
    up, update, v, version, view, whoami

npm <command> -h     quick help on <command>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /Users/nico1/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@5.6.0 /usr/local/lib/node_modules/npm

Did you mean one of these?
    list
    link
    ping
```

**Comment by ScottMorris** [comment]
What I ended up doing was editing the firebase.json file and changed the preflight commands to be `npm --prefix ./functions run lint`.  This seems to work on both Linux and Windows.  The environment variable is only compatible with shells that use that structure.

**Comment by cmwakio** [comment]
Same Error here: 
Running command: npm --prefix %RESOURCE_DIR% run lint

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
    explore, get, help, help-search, i, init, install,
    install-test, it, link, list, ln, login, logout, ls,
    outdated, owner, pack, ping, prefix, profile, prune,
    publish, rb, rebuild, repo, restart, root, run, run-script,
    s, se, search, set, shrinkwrap, star, stars, start, stop, t,
    team, test, token, tst, un, uninstall, unpublish, unstar,
    up, update, v, version, view, whoami

npm <command> -h     quick help on <command>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

**Comment by finppp** [comment]
Also getting this error!

**Comment by ricardosobral** [comment]
also getting this error on Mac. This is so buggy!!!!!!

**Comment by merlinnot** [comment]
Hey guys, you all probably have sth in your `predeploy` in `firebase.json`, don't you? Just delete what you have there for now if it's not that important. We're actively working on this issue.

@ricardosobral It's a Windows-specific "bug" (personally, I don't think it's a bug, but it is being discussed elsewhere). Please make a new issue if you're experiencing some problems on Mac, it has to be sth else.

**Comment by ScottMorris** [comment]
@merlinnot it seems the issue is the predeployment scripts are using an environment variable that isn't compatible with all shells.  The use of the script is a clever work around for compiling TypeScript before it is deployed, so removing it would render that method of precompiling useless.  

The change I made was to replace the env var with the relative path to my functions folder and that worked perfectly on both platforms.  It is probably not the perfect fix, as it hard codes in the path, but it keeps the desired functionality alive.

**Comment by ricardosobral** [comment]
I deleted everything and re-installed. Seems to work now. Took me ages to find all the files. A removal feature would be great. Tks for your prompt reply. Better than bug free is good support ;) Well done!

**Comment by merlinnot** [comment]
@ScottMorris Exactly, the problem is with env variables. I know it must work eventually, I was just trying to give you some advice for the time being ;)

**Comment by ScottMorris** [comment]
@merlinnot Does NPM have it's own, cross-platform env var stucture that could be leveraged?

**Comment by merlinnot** [comment]
I have literally no experience with Windows, I'm using Unix-based OSs since forever. As I understand, Windows has three CLIs available: CMD, PowerShell and Bash. Can I kindly ask some Windows dev which one do you guys use in development?

**Comment by ManminderTomar1223** [comment]
@merlinnot  Have the same error in windows. I am using cmd to deploy functions. Error is resolved when I deleted all the files except Function and firebase.Json leaving out just the curly braces.  It works fine on Ubuntu and it doesn't have any error.

**Comment by dylanjmcdonald** [comment]
@merlinnot I typically use PowerShell

**Comment by mbleigh** [comment]
This will hopefully be fixed by #644

Can anyone try `npm install -g git://github.com/firebase/firebase-tools#master` and let us know if deploying works without messing with `firebase.json` in Windows now? It did in our own tests but I'd love community confirmation. :smile:

**Comment by dylanjmcdonald** [comment]
@mbleigh I'm still getting the same error from my original post. Here's the steps I took for testing your fix:

1. Deleted functions directory, firebase.json, and .firebaserc files from project.
2. Uninstalled firebase-tools globally.
3. Ran `npm cache verify`
4. Ran `npm install -g git://github.com/firebase/firebase-tools#master`
5. From project root ran `firebase init`
6. Selected Functions/Hosting from firebase configuration and using TypeScript for functions.

Additional Info: `firebase --version` return `3.17.4`

**Comment by ntomallen** [comment]
I got this error and stumbled on this thread. I did the following:
1. Uninstalled `firebase-tools` globally
2. Ran `npm install -g git://github.com/firebase/firebase-tools#master`
3. `cd`'d into my functions project directory
4. Ran `firebase deploy --only functions`

Still getting the same error. I'm running Windows 10, ran this from PowerShell

**Comment by tinaliang** [comment]
@dylanjmcdonald The predeploy commands should print to console when you run `firebase deploy`. Can you check to make sure the commands being run are of the correct version for your platform?

**Comment by dylanjmcdonald** [comment]
@tinaliang Here's the entire output from the console after running `firebase deploy --only functions`

```
i  deploying functions
Running command: npm --prefix $RESOURCE_DIR run lint
npm ERR! path D:\PATH_TO_PROJECT\$RESOURCE_DIR\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'D:\PATH_TO_PROJECT\$RESOURCE_DIR\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\PATH_TO_USER\AppData\Roaming\npm-cache\_logs\2018-01-30T18_58_07_868Z-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code4294963238
```

I understand that I need adjust the environment variables within `firebase.json` in order for deployment to work within PowerShell. It would be nice if firebase-tools could set them up automatically so that additional manual user configuration is not required depending on the environment.

**Comment by tinaliang** [comment]
@dylanjmcdonald Thank you for your patience! 

Can you try npm install -g git://github.com/firebase/firebase-tools#master again and let us know if that fixes things? We've hopefully fixed things with #651

**Comment by jonmountjoy** [comment]
I get this error on OS X.  On a newly created dir (where I executed `firebase init`). `firebase --version` is 3.17.4.  I also installed pulling from master, as indicated above.

```
firebase deploy --only functions

=== Deploying to 'foxtrot-3344'...

i  deploying functions
Running command: npm --prefix $RESOURCE_DIR run lint

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
    explore, get, help, help-search, i, init, install,
    install-test, it, link, list, ln, login, logout, ls,
    outdated, owner, pack, ping, prefix, profile, prune,
    publish, rb, rebuild, repo, restart, root, run, run-script,
    s, se, search, set, shrinkwrap, star, stars, start, stop, t,
    team, test, token, tst, un, uninstall, unpublish, unstar,
    up, update, v, version, view, whoami

npm <command> -h     quick help on <command>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /Users/x/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@5.6.0 /usr/local/lib/node_modules/npm

Error: functions predeploy error: Command terminated with non-zero exit code1
```

**Comment by dylanjmcdonald** [comment]
@tinaliang That did the trick! Thank you @tinaliang @laurenzlong @mbleigh!

**Comment by tinaliang** [comment]
@jonmountjoy It doesn't seem like yours is the same error, since $RESOURCE_DIR is correct for OS X. Please file a new issue with the output of `firebase deploy --only functions --debug`.

**Comment by andrew-veresov** [comment]
Great! `npm install -g git://github.com/firebase/firebase-tools#master` fixed the issue.

**Comment by mBeierl** [comment]
Another work-around: install `cross-env` as dev dependency and change the predeploy script in `firebase.json` to `"cross-env npm --prefix $RESOURCE_DIR run lint"`

**Comment by Artux-White** [comment]
I had the same issue on Mac. The problem was that my project folder had a space in its name, therefore  $RESOURCE_DIR was point to my home dir '~'.  Removing the space did the trick.

**Comment by aurel282** [comment]
I got the same error on windows and impossible to make it work.
Keep me updated if you find something.

Thanks,

**Comment by laurenzlong** [comment]
You can remove everything under "predeploy" in firebase.json, and it'll stop running the script which is causing issues.

**Comment by benjiwheeler** [comment]
installing from `git://github.com/firebase/firebase-tools#master` didn't fix the issue for me. Still getting npm usage after `npm --prefix $RESOURCE_DIR run lint` is run. My path has no spaces.

**Comment by IceCubes** [comment]
When you write "$ firebase init " or " $ firebase init function "  firebase ask you if you want to intall and use EsLint in your project , this create your RESOURCE_DIR and this bug your project, just don't install. 
👍 
THIS WORK FOR ME

**Comment by jnorkus** [comment]
Edit `firebase.json` and replace `$RESOURCE_DIR` with `functions`. That did the trick for me.

**Comment by daveball** [comment]
i fixed this by downgrading my version of firebase-tools to 3.1.0

**Comment by viplovejha** [comment]
this cloud whatever thing is crap, trying out for firs time and deployment errors nowhere in mood stop, for some it works,for others it s**ks, by the way ,i m running it on windows 10 powershell and getting errors like " no such file or directory found", nothing is working, pls help ,if anybody could...

**Comment by Stone2517** [comment]
Thanks, Jnorkus It works for me.

**Comment by selcukyucel** [comment]
@merlinnot I was frustrating to fix it since morning, then I saw you saying "Hey guys, you all probably have sth in your predeploy in firebase.json, don't you? Just delete what you have there for now"
and I was like why not then hoooray.. Thanks.

**Comment by merlinnot** [comment]
It should actually be fixed in the latest release, but I'm glad I've saved you some of the precious time.

**Comment by essejose** [comment]
@jnorkus It works for me.

**Comment by Japheth-Mwongela** [comment]
@laurenzlong That worked for me. Thank you.

**Comment by BenjaminNjoroge** [comment]
This is How i fixed it
Hey guys, this is a pre-deploy error issue. 
just open your firebase.json file
delete the entire line containing %RESOURCE_DIR%.
i hope the best

**Comment by arunkush** [comment]
I an facing this error 


C:\Users\Lenovo>firebase deploy

=== Deploying to 'connecttofriend-c2d6f'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint
npm ERR! path C:\Users\Lenovo\%RESOURCE_DIR%\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Lenovo\%RESOURCE_DIR%\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2018-06-27T05_56_29_321Z-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code4294963238

C:\Users\Lenovo>

**Comment by pisaacs** [comment]
Ran into the same issue, but solve was easy:

- during the `firebase init` process,  I selected `no` for `Do you want to install dependencies with npm now?`
- From root of project, I had to cd to `functions` folder and run `npm install`. Was good to after after from root with `firebase deploy`

**Comment by markgoho** [comment]
How is this _still_ an issue? There's a workaround, but no fix in place?

**Comment by robertopato** [comment]
@jnorkus that did it for me! Thanks!

**Comment by charyjagdeesh** [comment]
@BenjaminNjoroge tq bro its working fine..

**Comment by pinich** [comment]
I have changed in *firebase.json* file the following lines and it worked

```javascript
"functions": {
    "predeploy": [
      "npm --prefix \"%RESOURCE_DIR%\" run lint",
      "npm --prefix \"%RESOURCE_DIR%\" run build"
    ]
  }
```

it's a shame that it does'nt work out of the box

**Comment by OrbitalJeffL** [comment]
There must be a way to make a O/S agnostic command for boilerplate code like this.

**Comment by laurenzlong** [comment]
@OrbitalJeffL You would think... but that hasn't proven to be the case so far :( 

I made some investigations and have documented the issue and workaround for Windows users here https://github.com/firebase/firebase-tools/issues/822#issuecomment-406754186, please continue the dicussion there.

**Comment by tuancaraballo** [comment]
I ended up switching my node environment from 6.11.5 to 9.5.0 and it worked.
( Be aware that google cloud runs on v6 by default, v8 is currently on beta)

I didn't touch my firebase.json It still looks like this
`{
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint"
    ]
  }
}`

**Comment by SuperRoo123** [comment]
Hi..running on windows 10..had to change the firebase.json predeploy to:
`"predeploy": [    
      "npm --prefix \"%RESOURCE_DIR%\" run build"
    ]`
& had to delete the lint command...this is firebase version 4.2.0 & Node 8.11.1 on August 23 with the issue going since Jan 19...when are you going to get it fixed?

**Comment by Divya0319** [comment]
What I did was just edited the firebase.json file and changed the part where $RESOURCE_DIR is there to %RESOURCE_DIR%. Worked like a charm for me

**Comment by dylannnn** [comment]
> %

This works for me under firebase version of 4.2.1

**Comment by dylannnn** [comment]
> I have changed in _firebase.json_ file the following lines and it worked
> 
> ```js
> "functions": {
>     "predeploy": [
>       "npm --prefix \"%RESOURCE_DIR%\" run lint",
>       "npm --prefix \"%RESOURCE_DIR%\" run build"
>     ]
>   }
> ```
> 
> it's a shame that it does'nt work out of the box

This works for me under firebase version of 4.2.1

**Comment by enigma49** [comment]
I had the same issue, I just removed "predeploy" in from firebase.json file and it worked lika charm

> You can remove everything under "predeploy" in firebase.json, and it'll stop running the script which is causing issues.

thanks worked perfectly

**Comment by raphael-luciano** [comment]
Only doing the /%RESOURCE_DIR%/ on firebase.json file woked like a charm for me too  =)
Thanks you all !

**Comment by Omar-Qalei** [comment]
I solved this problem, It's very easy. You don't need to uninstall.
Step1: open firebase.json
you will show this JSON file

```
"functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ]
  }
```
Step2: Delete  `"npm --prefix \"$RESOURCE_DIR\" run lint"`, and `"npm --prefix \"$RESOURCE_DIR\" run build"`
```
 "functions": {
    "predeploy": [
      
    ]
  }
```
Step3: Like and share my solved.

**Comment by rasamaya** [comment]
> I solved this problem, It's very easy. You don't need to uninstall.
> **Step1**: open firebase.json
> you will show this JSON file
> 
> ```
> "functions": {
>     "predeploy": [
>       "npm --prefix \"$RESOURCE_DIR\" run lint",
>       "npm --prefix \"$RESOURCE_DIR\" run build"
>     ]
>   }
> ```
> **Step2**: Delete `"npm --prefix \"$RESOURCE_DIR\" run lint"`, and `"npm --prefix \"$RESOURCE_DIR\" run build"`
> 
> ```
>  "functions": {
>     "predeploy": [
>       
>     ]
>   }
> ```
> **Step3**: `firebase deploy --only functions`
> **Step4**: Like and share my solved.

I liked your answer as it worked, but its is still a workaround. Its also a workaround to place package.json in the %RESOURCE_DIR% folder (on windows)

**Comment by Omar-Qalei** [comment]
Yes, but I seen my answered ,It's best solution for beginner .

**Comment by lborgman** [comment]
I got this error now when I am trying to resume a project I have left dormant some month. (This is on Windows 10.)

Why is this bug report closed?

**Comment by laurenzlong** [comment]
Let's consolidate comments on this to https://github.com/firebase/firebase-tools/issues/822#issuecomment-406754186. Please follow my instructions on that comment for workarounds. This is a high priority bug for us to fix, unfortunately it's not straightforward.

**Comment by ahmadalibaloch** [comment]
For ubuntu you need to change `firebase.json` to following, notice `$` before `RESOURCE_DIR`
```
{
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ]
  }
}
```

for Windows 10 you need to change `firebase.json` to following, notice `%` after and before `RESOURCE_DIR`

```
{
  "functions": {
    "predeploy": [
      "npm --prefix \"%RESOURCE_DIR%\" run lint",
      "npm --prefix \"%RESOURCE_DIR%\" run build"
    ]
  }
}
```

**Comment by alexcsandru** [comment]
**_### QUICK FIX_** 👍 Thanks to @ahmadalibaloch

For ubuntu you need to change firebase.json to following, notice $ before RESOURCE_DIR

```
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ]
```

for Windows 10 you need to change firebase.json to following, notice % after and before RESOURCE_DIR

```
  "functions": {
    "predeploy": [
      "npm --prefix \"%RESOURCE_DIR%\" run lint",
      "npm --prefix \"%RESOURCE_DIR%\" run build"
    ]
  }
```

**Comment by 3dmirtech** [comment]
Thanks a lot @ahmadalibaloch
Your solution worked for me!

**Comment by darrelfrancis** [comment]
Explanation:

The Firebase people are trying to allow you to give any name you want for your "functions" folder, and still create a script for you to deploy those functions automatically. This means they have to use an environment variable. Unfortunately all our various operating systems have different ways of referencing environment variables. I am a Windows User (don't hate me) and there are several shells people use.

I use the "original and worst" shell, CMD.exe shell, like many who can't be bothered to learn Powershell. I need to reference an environment variable as `%VARIABLENAME%`. Additionally just in case there are spaces in the folder name, I need to add quotes around it, and because this is JSON I need to escape them, thus: `\"%VARIABLENAME%\"`

For you clever Unix people it might be `$VARIABLENAME` or whatever.

It is hard for the Firebase people to fix, because even if they think hard at "firebase init" time to work out what OS we are using, we might well sync the folder to another system with a different OS and get screwed up.

There are several solutions. The simplest is to hard-code the name of the functions folder to be `functions`. That way, no environment variables etc. People can be told "if you want to have a different name, that's fine, just change it in the `firebase.json`. But the default `firebase init` will use `functions`"

The various solutions shown above offer other solutions, some manually hard-coding the folder name "functions", and others providing a way of referencing the environment variable `RESOURCE_DIR` in one particular shell (but probably not others). 

If people are having this problem, and are happy to hardcode the function folder to be "functions", the definitive fix is to make each line that tries to reference `RESOURCE_DIR` to have the form:
`   "npm --prefix \"functions\" run lint",`

This should work even if you sync the file across multiple systems and build in different OS's

**Comment by mbleigh** [comment]
Excellent summary of our challenge, thanks for adding the comment!

**Comment by lborgman** [comment]
Please hard code it for now (until you have a solution). I, as a user, just don't want the trouble.

**Comment by hariangr** [comment]
> Does the command work for you if you replace $RESOURCE_DIR with %RESOURCE_DIR%?

thanks! it does works!

**Comment by abhisawesome** [comment]
"npm --prefix functions run build"

**Comment by BLACKCAT25896** [comment]
What can i do now 
i am tried every way but its error On Mac

1. Uninstalled firebase-tools globally
2.  npm install -g git://github.com/firebase/firebase-tools#master
3. cd into my functions project directory
4. Ran firebase deploy --only functions


`{
  "functions": {
    "predeploy": [
      "npm --prefix \"%RESOURCE_DIR%\" run lint",
      "npm --prefix \"%RESOURCE_DIR%\" run build"
    ]
  }
}`



`=== Deploying to 'flas-chat-f6e00'...

i  deploying functions
Running command: npm --prefix "%RESOURCE_DIR%" run lint
npm ERR! path /Users/macbookair/Desktop/check/%RESOURCE_DIR%/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/Users/macbookair/Desktop/check/%RESOURCE_DIR%/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/macbookair/.npm/_logs/2019-09-22T10_58_49_649Z-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code254
`

**Comment by samrat19** [comment]
took a long time but finished

**Comment by byronglendon** [comment]
Run npm install from within your functions directory to make sure you have the correct node modules installed for your functions.

**Comment by Geekgineer** [comment]
Solved by deleting the node_modules folder from functions directory and within the directory run:
```sh
$ npm i
$ firebase deploy
```

**Comment by frugoman** [comment]
In my case, I solved this adding `"npm --prefix \"$RESOURCE_DIR\" install"` to predeploy scripts

the issue, as I understand is that at the moment of running lint or build scripts on CI at least, node modules are not installed yet.. (/node_modules does not exist and shouldn't be tracked by git)

**Comment by rafialikhan** [comment]
> Run npm install from within your functions directory to make sure you have the correct node modules installed for your functions.

This was the issue, i had initially setup firebase init on a mac machine and then later cloned it on a windows machine. 
The line error is misleading. All i had to do was go to functions folder which has a seperate package.json and do npm i.

Even if you are not using functions in  your project; **firebase deploy** looks for it and processes the functions and without the npm node modules, it gives that error assuming its a directory error.

**Comment by deeps1287** [comment]
IT WORKS...

{
  "functions": {
    "predeploy": [
      "npm --prefix ./functions/ install",
      "npm --prefix ./functions/ run lint"
    ],
    "source": "functions"
  }
}

**Comment by myaoo18** [comment]
> I solved this problem, It's very easy. You don't need to uninstall. **Step1**: open firebase.json you will show this JSON file
> 
> ```
> "functions": {
>     "predeploy": [
>       "npm --prefix \"$RESOURCE_DIR\" run lint",
>       "npm --prefix \"$RESOURCE_DIR\" run build"
>     ]
>   }
> ```
> 
> **Step2**: Delete `"npm --prefix \"$RESOURCE_DIR\" run lint"`, and `"npm --prefix \"$RESOURCE_DIR\" run build"`
> 
> ```
>  "functions": {
>     "predeploy": [
>       
>     ]
>   }
> ```
> 
> **Step3**: `firebase deploy --only functions` **Step4**: Like and share my solved.

this worked on Mac OS!

**Comment by darrelfrancis** [comment]
> \"%RESOURCE_DIR%\"

You are using the Windows way of accessing an environment variable, but you are on a Mac.
Assuming you are happy with the functions directory being hard coded as "functions", just change the mentions of `\"%RESOURCE_DIR%\"` to `functions`, or if you like to use more characters, `\"functions\"`.

**Comment by malik199** [comment]
Solved by running "npm i" inside of the functions folder.
