### ISSUE TITLE
Deploy fails due to "missing" default storage bucket

### ISSUE THREAD

**Issue by bergeoisie** [firebase/firebase-tools#6162]
### [REQUIRED] Environment info

**firebase-tools:** 12.4.4

**Platform:** Ubuntu

### [REQUIRED] Test case

Not sure the best way to do this since it relates to the state of firebase/GCP project.

### [REQUIRED] Steps to reproduce

Run `firebase deploy`

### [REQUIRED] Expected behavior

Deploy succeeds.

### [REQUIRED] Actual behavior
After attempting to upgrade our `firebase-tools` version from 11.18.0 to 12.4.4, our deploys fail with 
```
[2023-07-13T05:49:06.671Z] Default storage bucket is undefined.


There was an issue deploying your functions. Verify that your project has a Google App Engine instance setup at https://console.cloud.google.com/appengine and try again. If this issue persists, please contact support.

Error: Your project is being set up. Please wait a minute before deploying again.
1
```
It appears that the call to obtain the default storage bucket was changed in between those versions in https://github.com/firebase/firebase-tools/pull/5973

I ran the calls locally to see the difference in output (redacting our project details). The old call:
```
 curl -X GET \
    -H "Authorization: Bearer $(gcloud auth print-access-token)" \
    -H "x-goog-user-project: REDACTED" \
    "https://appengine.googleapis.com/v1/apps/REDACTED"
```
returns
```
{
  "name": "apps/REDACTED",
  "id": "REDACTED",
  "authDomain": "gmail.com",
  "locationId": "us-central",
  "codeBucket": "staging.REDACTED.appspot.com",
  "servingStatus": "SERVING",
  "defaultHostname": "REDACTED.uc.r.appspot.com",
  "defaultBucket": "REDACTED.appspot.com",
  "serviceAccount": "REDACTED@appspot.gserviceaccount.com",
  "gcrDomain": "us.gcr.io",
  "databaseType": "CLOUD_DATASTORE_COMPATIBILITY",
  "featureSettings": {
    "splitHealthChecks": true,
    "useContainerOptimizedOs": true
  }
}
```
versus the new call:
```
 curl -X GET \
    -H "Authorization: Bearer $(gcloud auth print-access-token)" \
    -H "x-goog-user-project: REDACTED" \
    "https://firebase.googleapis.com/v1beta1/projects/REDACTED"
```
which returns a much smaller blob
```
{
  "projectId": "REDACTED",
  "projectNumber": "1234567890",
  "displayName": "REDACTED",
  "name": "projects/REDACTED",
  "resources": {
    "hostingSite": "REDACTED"
  },
  "state": "ACTIVE",
  "etag": "1_c080f4ba-b2da-4369-8f5f-b3a731257079"
}
```

It seems like these APIs might not actually be equivalent? 

Thanks!

**Comment by aalej** [comment]
Hi @bergeoisie, thanks for reaching out and for sharing details about your observations! I’m trying to reproduce the issue you’re encountering but so far I haven’t encountered any issue while deploying.

From what I can gather, you’re trying to deploy your Firebase rules for Cloud Storage. Could you verify if you’ve initialized Cloud Storage for the project you’re trying to deploy to? Also, are you able to repro the issue in a fresh project?

**Comment by bergeoisie** [comment]
> Hi @bergeoisie, thanks for reaching out and for sharing details about your observations! I’m trying to reproduce the issue you’re encountering but so far I haven’t encountered any issue while deploying.
> 
> From what I can gather, you’re trying to deploy your Firebase rules for Cloud Storage. Could you verify if you’ve initialized Cloud Storage for the project you’re trying to deploy to? Also, are you able to repro the issue in a fresh project?

Thanks for the quick response!

Yep, that's right. Our current `firebase.json` included a `storage` block that pointed to an v1 storage config. I wonder if that's the issue. It doesn't look like that's actually configuring firebase storage anymore? Since this is unused in our product, we're going to just remove the block. Deploys work after doing that. Thanks for the assistance!

**Comment by cedvdb** [comment]
@bergeoisie please reopen, removing the use of storage is not a fix.

Same issue here happens in github action deployment since today.

**Comment by Jpoliachik** [comment]
Yup, also started seeing this issue as of today.

**Comment by lucsande** [comment]
we have started seeing the issue as of today to. We made a successful deploy earlier today (around 10 AM GMT-03:00). But have not been capable of making new deploys in the last hour

**Comment by pangolinkeys** [comment]
I'm also experiencing this issue

**Comment by Azuka** [comment]
Just started seeing this today too. Did any of you upgrade (or have dependabot upgrade) https://github.com/google-github-actions/auth from v1 to v2? That seems to be the only CI change I'm seeing on my end.

**Comment by pangolinkeys** [comment]
> Just started seeing this today too. Did any of you upgrade (or have dependabot upgrade) [google-github-actions/auth](https://github.com/google-github-actions/auth) from v1 to v2? That seems to be the only CI change I'm seeing on my end.

I've not made any dependency changes today failing both locally & ci.

**Comment by JWhite212** [comment]
Yup

> > Just started seeing this today too. Did any of you upgrade (or have dependabot upgrade) [google-github-actions/auth](https://github.com/google-github-actions/auth) from v1 to v2? That seems to be the only CI change I'm seeing on my end.
> 
> I've not made any dependency changes today failing both locally & ci.

I have also not changed anything, and as of today am getting the same issue.

**Comment by lhallowes** [comment]
me too, just started today.

**Comment by Russell-Pollari** [comment]
Same issue here, just noticed today

**Comment by yukioy1** [comment]
Same here, started today too

**Comment by appvisionco** [comment]
Same here

**Comment by andrewkrippner** [comment]
+1 deploys failing for me as well

**Comment by carlos-lara-dev** [comment]
Someone fix this ?

**Comment by unxavi** [comment]
Seeing this now in our 3 projects and trying to deploy from different machines

**Comment by remilefort** [comment]
same here

**Comment by kazukinagata** [comment]
Same here, downgraded to v11.30.0 and it worked.

**Comment by oyvindholmstad** [comment]
Same here as of today.

**Comment by sasos90** [comment]
Same here.. what do we do now? Did they update something?

**Comment by jawsandteeth** [comment]
ah.. so its not just me..

**Comment by xaphod** [comment]
Yay all our deploys are broken

**Comment by joerozek** [comment]
same problem here.

**Comment by aalej** [comment]
Hey everyone, apologies for the delay in updates here. Our team has investigated the issue and rolled out a fix. Could anyone try deploying their storage rules with `firebase deploy --only storage` to confirm if errors persist? I tested it on v12.9.1 and encountered no issues.

**Comment by joerozek** [comment]
Works again for me.

**Comment by joehan** [comment]
Hey all, gonna close this out for now since the issue has been resolved. For some context: the root cause of this was a backend change that went out too early. In the upcoming v13 of firebase-tools, we'll be moving this call to use a new API that is more accurate. At some point in the coming months, we'll need to roll out that backend change again. To avoid future issues, please upgrade to v13 ASAP when it is released.

If you're coming back to this issue later and experiencing something similar, the best way forward is to upgrade to firebase-tools@>13.0.0 and try again.

**Comment by jmw11x** [comment]
I have this issue now too. THis is an active bug This cant be closed

I have upgraded and the issue still persists I have an active support case on it and they agree it is a firebase issue.

**Comment by 6h4n3m** [comment]
Same here, no idea why this is being closed.... We're actively supporting an enterprise with our software and cannot deploy a hotfix that is halting operations because of this!

**Comment by jmw11x** [comment]
> Same here, no idea why this is being closed.... We're actively supporting an enterprise with our software and cannot deploy a hotfix that is halting operations because of this!

I thought it didn't work too. I upgraded etc even have support case..

I firebase deploy --only storage 

Then firebase deploy WORKED no problem.

Also yesterday firebase deploy --only hosting worked as well. Only firebase deploy did not work.

**Comment by joehan** [comment]
Apologies all, looks like I closed this preemptively. The backend fix is rolling out but may not have fully finished yet - reopening.

**Comment by 6h4n3m** [comment]
> > Same here, no idea why this is being closed.... We're actively supporting an enterprise with our software and cannot deploy a hotfix that is halting operations because of this!
> 
> I thought it didn't work too. I upgraded etc even have support case..
> 
> I firebase deploy --only storage
> 
> Then firebase deploy WORKED no problem.
> 
> Also yesterday firebase deploy --only hosting worked as well. Only firebase deploy did not work.

Thank you, I'll go try either of those.

**Comment by jmw11x** [comment]
> > > Same here, no idea why this is being closed.... We're actively supporting an enterprise with our software and cannot deploy a hotfix that is halting operations because of this!
> > 
> > 
> > I thought it didn't work too. I upgraded etc even have support case..
> > I firebase deploy --only storage
> > Then firebase deploy WORKED no problem.
> > Also yesterday firebase deploy --only hosting worked as well. Only firebase deploy did not work.
> 
> Thank you, I'll go try either of those.

firebase deploy --debug

will show you where it is failing if the issue persist

**Comment by joehan** [comment]
This issue has been resolved. Apologies for the disruption all!

**Comment by romaincoeur** [comment]
> same here

Putain je me prend la tête là dessus depuis hier !!

**Comment by joerozek** [comment]
It's happening again today.

**Comment by ramizitx** [comment]
Confirming, seeing this issue as well.

end of log looks like this...

```
[2025-02-02T06:59:16.266Z] Default storage bucket is undefined.
There was an issue deploying your functions. Verify that your project has a Google App Engine instance setup at https://console.cloud.google.com/appengine and try again. If this issue persists, please contact support.
Error: Your project is being set up. Please wait a minute before deploying again.
```

Log about app engine being setup doesn't make sense, because repeating this deploy doesn't yield any results.

**Comment by NaokiOtsu** [comment]
The following fixed it: npm install -g firebase-tools
