### ISSUE TITLE
error while connecting google assistant with SAP Hana 

### ISSUE THREAD

**Issue by shivamshukla12** [firebase/firebase-tools#623]
Hi ,

I am following the below blog for interfacing between google cloud platform & SAP HANA -

https://blogs.sap.com/2017/05/29/hey-google-let-me-talk-to-hana/comment-page-1/#comment-406705

but when i am creating the function & deploying it's throwing the below error -

Deployment failure:

Function load error: Code in file index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'actions-on-google'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/index.js:1:114)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
function is askHANA from blog.

let me know if i need to share more details about the issue.

Thanks,

Shivam

**Comment by shivamshukla12** [comment]
This is fixed .
Thanks !!

**Comment by itzukah** [comment]
I tried the code on the link but not lucky.. 
still getting an error. I tried to use the SAP Hana service layer using json script.
Hope i could see your simple code on posting to SAP Hana.
