### ISSUE TITLE
Cloud Runtime Config is currently experiencing issues and not able to deploy

### ISSUE THREAD

**Issue by nerder** [firebase/firebase-tools#7341]
### [REQUIRED] Environment info

**firebase-tools:** 13.11.2

**Platform:** Github Action (ubuntu)

### [REQUIRED] Test case

when running `firebase deploy --only functions` i get the following error:

```
Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.
```

### [REQUIRED] Steps to reproduce

Run `firebase deploy --only functions` on a Firebase Project

### [REQUIRED] Expected behavior

Not to fail

**Comment by brycecammo** [comment]
This is also happening for me when deploying functions with `firebase-tools@13.11.2`. Can't see any issues currently at https://status.firebase.google.com/ or https://status.cloud.google.com/.

**Comment by chen-zhihang** [comment]
same

**Comment by myfknoll** [comment]
Same here

**Comment by unxavi** [comment]
can reproduce

**Comment by geoffcfchen** [comment]
Same here... I thought that I did something wrong..... Thank god, I see all of you see the same issue.

**Comment by newsu1** [comment]
same

**Comment by fan-ka-yagi** [comment]
same

**Comment by zariweyo** [comment]
I'm having same issue. When I execute with --debug, I can see this 502 response in configs calls:

[2024-06-19T07:04:46.862Z] >>> [apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1/projects/XXXXXX/configs [none]
[2024-06-19T07:05:26.615Z] <<< [apiv2][status] GET https://runtimeconfig.googleapis.com/v1beta1/projects/XXXXXX/configs 502

**Comment by becjit** [comment]
same

**Comment by magelikescoke** [comment]
Same,get 502 when fetch run time config

**Comment by sg-tbiswas** [comment]
Same issue
![image](https://github.com/firebase/firebase-tools/assets/51081413/7c4bad6e-7314-4704-bc64-a1fbfd1b18c8)

**Comment by Vochsel** [comment]
Same here. Had an issue like this before... Very frustrating having an outage like this...

**Comment by nicklbaert** [comment]
same

**Comment by devkimkr** [comment]
@Vochsel When did it happen? How did you solved before?

**Comment by martin-minovski** [comment]
Same issue with firebase-tools 13.11.2

**Comment by Vochsel** [comment]
> @Vochsel When did it happen? How did you solved before?

It was a different issue/error, but same problem: A centralised outage breaking all deployments

**Comment by denisyilmaz** [comment]
The error from debug (via `firebase deploy --only functions --debug`) is: 
```
502 That’s an error.
The server encountered a temporary error and could not complete your request.
Please try again in 30 seconds.
That’s all we know.
```

```bash
[2024-06-19T07:45:32.433Z] <<< [apiv2][status] GET https://runtimeconfig.googleapis.com/v1beta1/projects/<project-name>/configs 502
[2024-06-19T07:45:32.433Z] <<< [apiv2][body] GET https://runtimeconfig.googleapis.com/v1beta1/projects/<project-name>/configs "<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n  <title>Error 502 (Server Error)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>502.</b> <ins>That’s an error.</ins>\n  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>\n"
```

**Comment by GoogleFir** [comment]
I contacted Firebase Support and it looks that they are already trying to fix this. I had to update one of my functions ASAP and managed to workaround this issue using gcloud via Google Cloud Shell (https://cloud.google.com/functions/docs/create-deploy-gcloud).

**Comment by KSiejka** [comment]
I contacted Firebase Support and they are aware of this outage and are actively trying to fix it. I had to deploy one of my functions ASAP to fix a major bug and thankfully managed to do it using gcloud via Cloud Shell. If you have any critical updates that need to be pushed you may try this https://cloud.google.com/functions/docs/create-deploy-gcloud

**Comment by beevor** [comment]
same

**Comment by devkimkr** [comment]
> > @Vochsel When did it happen? How did you solved before?
> 
> It was a different issue/error, but same problem: A centralised outage breaking all deployments

Thank you

**Comment by hacthe-codelink** [comment]
We are all waiting for a hotfix ~~

**Comment by avi12** [comment]
> I contacted Firebase Support and they are aware of this outage and are actively trying to fix it. I had to deploy one of my functions ASAP to fix a major bug and thankfully managed to do it using gcloud via Cloud Shell. If you have any critical updates that need to be pushed you may try this https://cloud.google.com/functions/docs/create-deploy-gcloud

How come wasn't the [status page](https://status.firebase.google.com/) updated?

**Comment by vaivai130** [comment]
Can anyone confirm whether downgrading their firebase tools fixed the issue?

**Comment by npty** [comment]
> I contacted Firebase Support and they are aware of this outage and are actively trying to fix it. I had to deploy one of my functions ASAP to fix a major bug and thankfully managed to do it using gcloud via Cloud Shell. If you have any critical updates that need to be pushed you may try this https://cloud.google.com/functions/docs/create-deploy-gcloud

thank you for reaching out to them 🙏🏻

**Comment by Ahseo** [comment]
> Can anyone confirm whether downgrading their firebase tools fixed the issue?

I downgraded Firebase tools to 11.1.0, but it still does not work :(

**Comment by mondyfy** [comment]
I had the same issue at my end as well, tried deploying with multiple versions of Firebase tools, and in the different regions, it didn't work, expecting quick fixes from their end.

**Comment by duy-dev** [comment]
I am also having the same problem on version 13.5.0 🥲
![image](https://github.com/firebase/firebase-tools/assets/87229133/0bdcfb8a-868e-42d8-8d34-97e38220f45e)

**Comment by rohanmathur91** [comment]
Facing same issue.

**Comment by chamaraserviceform** [comment]
same here!!

**Comment by rodneyrd** [comment]
same here

**Comment by kojitakakipathos** [comment]
same here

**Comment by kvn-DN** [comment]
Same here

**Comment by krol-m2** [comment]
same here

**Comment by iwanwmys** [comment]
Same here

**Comment by willemjanvankranenburg** [comment]
@avi12 
> How come wasn't the [status page](https://status.firebase.google.com/) updated?

Because Firebase/Google never updates that page.. Everything is always working according to that page, even if everything is broken for everyone

**Comment by avi12** [comment]
What status page should we refer to then?

**Comment by harshit-j** [comment]
I'm facing this issue too. Using firebase-tools@13.6.0

**Comment by iwanwmys** [comment]
I think this is affecting everyone. Going back to sleep ...

**Comment by adinvadim** [comment]
Same
Following this thread

**Comment by chunrui-qashier** [comment]
same here

**Comment by eriklundstrom** [comment]
Same here

**Comment by kibitzing** [comment]
Same here

**Comment by yy0867** [comment]
Same here..

**Comment by tooHH** [comment]
same here

**Comment by igl** [comment]
👋

**Comment by YoucefSFPlus** [comment]
Same issue !

**Comment by KSiejka** [comment]
I just tried deploying my functions and it looks like it's working again.

**Comment by goodje** [comment]
It's back normal. Can Google give a summary of what's happened?

**Comment by vaivai130** [comment]
Can confirm it's now working on my side

**Comment by tooHH** [comment]
Is working fine now

**Comment by kvn-DN** [comment]
it's fine now

**Comment by denisyilmaz** [comment]
The previous error disappeared, but now i get the follow error message:

```⚠  functions: Upload Error: HTTP Error: 400, <?xml version='1.0' encoding='UTF-8'?><Error><Code>EntityTooLarge</Code><Message>Your proposed upload is larger than the maximum object size specified in your Policy Document.</Message><Details>Content-length exceeds upper bound on range</Details></Error>

Error: HTTP Error: 400, <?xml version='1.0' encoding='UTF-8'?><Error><Code>EntityTooLarge</Code><Message>Your proposed upload is larger than the maximum object size specified in your Policy Document.</Message><Details>Content-length exceeds upper bound on range</Details></Error>```

my functions did not change though and were able to deploy yesterday without any issues.
any idea if this is related or anyone else with that error?

**Comment by denisyilmaz** [comment]
it seems like the S3 Bucket where the .zip of the cloud functions is uploaded to is throwing the error. 

```bash
[2024-06-19T09:57:49.780Z] <<< [apiv2][status] PUT https://storage.googleapis.com/uploads-xxx.europe-west3.cloudfunctions.appspot.com/xxx-e3a4-47bc-b181-xxx.zip 400
[2024-06-19T09:57:49.781Z] <<< [apiv2][body] PUT https://storage.googleapis.com/uploads-xxx.europe-west3.cloudfunctions.appspot.com/xxx-e3a4-47bc-b181-xxx.zip [omitted]
⚠  functions: Upload Error: HTTP Error: 400, <?xml version='1.0' encoding='UTF-8'?><Error><Code>EntityTooLarge</Code><Message>Your proposed upload is larger than the maximum object size specified in your Policy Document.</Message><Details>Content-length exceeds upper bound on range</Details></Error> 

Error: HTTP Error: 400, <?xml version='1.0' encoding='UTF-8'?><Error><Code>EntityTooLarge</Code><Message>Your proposed upload is larger than the maximum object size specified in your Policy Document.</Message><Details>Content-length exceeds upper bound on range</Details></Error>
[2024-06-19T09:57:50.005Z] Error Context: {
  "body": {
    "error": {
      "message": "<?xml version='1.0' encoding='UTF-8'?><Error><Code>EntityTooLarge</Code><Message>Your proposed upload is larger than the maximum object size specified in your Policy Document.</Message><Details>Content-length exceeds upper bound on range</Details></Error>"
    }
  },
  "response": {
    "statusCode": 400
  }
}
```

**Comment by becjit** [comment]
also looks like the uppercase functions are not deployed. created https://github.com/firebase/firebase-tools/issues/7344

**Comment by unxavi** [comment]
V2 cloud functions are getting a new error:

```
Error: Cannot set CPU on the functions my-Function-onCreate because they are GCF gen 1
```

**Comment by aalej** [comment]
Hey folks, apologies for the issue this has caused. Our Firebase Support team has escalated this issue to our engineering team. This issue should be resolved and functions deployment should now work correctly. I was able to successfully deploy my functions.

**Comment by camelmasa** [comment]
I encountered it again now.

**Comment by camelmasa** [comment]
That's fine now!

**Comment by anatoo** [comment]
I encountered the same problem for a while now, but after a few deployments I was able to deploy successfully.

**Comment by rendomnet** [comment]
SAME ERROR! I have deployed test build with constant firebase db update and now I CANT disable IT!

**Comment by davidsomekh** [comment]
Experienced this issue just now - anyone else?

**Comment by Alex0x47** [comment]
> Experienced this issue just now - anyone else?

Yes, I'm having the same issue right now as well.

**Comment by leeparayno** [comment]
I'm having the same issue trying to deploy cloud functions on two different Firebase/GCP projects:

Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.
Run `firebase deploy --except functions` if you want to continue deploying the rest of your project.

**Comment by leeparayno** [comment]
Firebase Status page doesn't show anything except Dynamic Links having an issue so Cloud Runtime Config must be not instrumented for Firebase:

https://status.firebase.google.com

**Comment by Ajmaljalal** [comment]
Encountered this issue just now

**Comment by mariusmcl** [comment]
I am experiencing same issue

**Comment by franklastborn** [comment]
Same here, experiencing the same problem now.

**Comment by akshatdatacrowd** [comment]
experiencing issue just now, what was the last stable version, last month

**Comment by verscph** [comment]
Same here

@joehan you closed this issue, can you give more information pls? Is it Firebase platform related, has it something to do with firebase-functions/v1 support, ... ?

**Comment by jgavazzisp** [comment]
Come on guys, we spent 1000s per month on Firebase and now we cannot even update code which has a critical bug.

**Comment by davidedandrea25** [comment]
Experiencing the same issue, but updating tools to 13.15.4 version seems to resolve.

**Comment by Nahee-Park** [comment]
same here

**Comment by franklastborn** [comment]
> Experiencing the same issue, but updating tools to `13.15.4` version seems to resolve.

Are you sure this solved the issue?

**Comment by Alex0x47** [comment]
> Experiencing the same issue, but updating tools to `13.15.4` version seems to resolve.

I was in 13.7.5, updated with 'npm install -g firebase-tools', now in 13.15.4 but I'm still having the issue.

**Comment by shayAiode** [comment]
The same issue... can't believe this is a Google service.

**Comment by AndRud** [comment]
Tha same issue

**Comment by arifsuheyl** [comment]
> The same issue... can't believe this is a Google service.

me too...

**Comment by TudorAxinte** [comment]
[2024-08-27T07:06:46.815Z] <<< [apiv2][body] GET https://runtimeconfig.googleapis.com/v1beta1/projects/helix-network/configs/email/variables {"error":{"code":500,"message":"Internal error encountered.","status":"INTERNAL"}}

Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.

**Comment by jgavazzisp** [comment]
I hope someone is on call at the moment.

**Comment by sscr197** [comment]
Same here

**Comment by nl** [comment]
i had it a few minutes ago but seems fixed now

**Comment by AndRud** [comment]
It works! In case somebody still have a problem try to update firebase cli

**Comment by Ajmaljalal** [comment]
It is fixed now, but definitely is not a CLI upgrade or downgrade issue. 500 error means something for us developers folks.

**Comment by dcurtin91** [comment]
Hey this is happening to me now. Anyone else?

**Comment by jdriscoll98** [comment]
> Hey this is happening to me now. Anyone else?

Happening to me too

**Comment by rdavidsc** [comment]
Same.... It's Happening again....

**Comment by colnaghijr** [comment]
I was hitting this issue just recently and got it fixed. 

**To circumvent it, I:**

1. Opened my GCP console project, navigated to API & Services (https://console.cloud.google.com/apis/dashboard)
2. Selected "Cloud Runtime Configuration API" and disabled the API. Since I'm only using Secret Manager, this API is unnecessary.

**firebase deploy** for whatever reason tries to reach "_[apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1..._" and fails with 500, halting the deployment.

**Comment by jdriscoll98** [comment]
> I was hitting this issue just recently and got it fixed.
> 
> **To circumvent it, I:**
> 
> 1. Opened my GCP console project, navigated to API & Services (https://console.cloud.google.com/apis/dashboard)
> 2. Selected "Cloud Runtime Configuration API" and disabled the API. Since I'm only using Secret Manager, this API is unnecessary.
> 
> **firebase deploy** for whatever reason tries to reach "_[apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1..._" and fails with 500, halting the deployment.

You're a wizard that worked.

**Comment by rdavidsc** [comment]
> I was hitting this issue just recently and got it fixed.
> 
> **To circumvent it, I:**
> 
>     1. Opened my GCP console project, navigated to API & Services (https://console.cloud.google.com/apis/dashboard)
> 
>     2. Selected "Cloud Runtime Configuration API" and disabled the API. Since I'm only using Secret Manager, this API is unnecessary.
> 
> 
> **firebase deploy** for whatever reason tries to reach "_[apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1..._" and fails with 500, halting the deployment.

Worked for me Thanks a lot!!

**Comment by dcurtin91** [comment]
> I was hitting this issue just recently and got it fixed.
> 
> **To circumvent it, I:**
> 
> 1. Opened my GCP console project, navigated to API & Services (https://console.cloud.google.com/apis/dashboard)
> 2. Selected "Cloud Runtime Configuration API" and disabled the API. Since I'm only using Secret Manager, this API is unnecessary.
> 
> **firebase deploy** for whatever reason tries to reach "_[apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1..._" and fails with 500, halting the deployment.
> 
> Edit: There's a request quota (during deploy) that can easily be hit if you're deploying multiple functions (5+). See [documentation](https://firebase.google.com/docs/functions/manage-functions?gen=2nd#deploy_functions).
> 
> In these cases, they recommend deployments of only the changed functions. ex: _firebase deploy --only functions:addMessage,functions:makeUppercase_

This worked for me, too! Thank you

**Comment by gadgrandez** [comment]
That worked for me, thanks.

> 1. Opened my GCP console project, navigated to API & Services (https://console.cloud.google.com/apis/dashboard)
> 2. Selected "Cloud Runtime Configuration API" and disabled the API. Since I'm only using Secret Manager, this API is unnecessary.

**Comment by Jukii17** [comment]
I had the same problem and I solved it by disabling the Cloud Runtime Configuration API in the Google Cloud Console. However, I had to run npm install -g firebase-tools again to deploy it. Thanks for sharing this solution, it must be temporary right? until Google fixes the bug.

> I was hitting this issue just recently and got it fixed.
> 
> **To circumvent it, I:**
> 
> 1. Opened my GCP console project, navigated to API & Services (https://console.cloud.google.com/apis/dashboard)
> 2. Selected "Cloud Runtime Configuration API" and disabled the API. Since I'm only using Secret Manager, this API is unnecessary.
> 
> **firebase deploy** for whatever reason tries to reach "_[apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1..._" and fails with 500, halting the deployment.
> 
> Edit: There's a request quota (during deploy) that can easily be hit if you're deploying multiple functions (5+). See [documentation](https://firebase.google.com/docs/functions/manage-functions?gen=2nd#deploy_functions).
> 
> In these cases, they recommend deployments of only the changed functions. ex: _firebase deploy --only functions:addMessage,functions:makeUppercase_

**Comment by colnaghijr** [comment]
> > I was hitting this issue just recently and got it fixed.
> > **To circumvent it, I:**
> > 
> > 1. Opened my GCP console project, navigated to API & Services (https://console.cloud.google.com/apis/dashboard)
> > 2. Selected "Cloud Runtime Configuration API" and disabled the API. Since I'm only using Secret Manager, this API is unnecessary.
> > 
> > **firebase deploy** for whatever reason tries to reach "_[apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1..._" and fails with 500, halting the deployment.
> > Edit: There's a request quota (during deploy) that can easily be hit if you're deploying multiple functions (5+). See [documentation](https://firebase.google.com/docs/functions/manage-functions?gen=2nd#deploy_functions).
> > In these cases, they recommend deployments of only the changed functions. ex: _firebase deploy --only functions:addMessage,functions:makeUppercase_
> 
> Should I expect any downstream effects of disabling this API? I can confirm this fixes my firebase functions deployment issue, but am uneasy generally about disabling APIs that I don't understand.

Very fair question. If you configure config (v1) or params (v2) values for your function (ex. require('[firebase-functions/params](https://firebase.google.com/docs/functions/config-env?gen=2nd#params)')), this API might be needed. I haven't used it yet.
Google usually does a great job with their tools when warning of disabled APIs that need to be enabled.

I have API Secret Keys that I'm using with my functions, though as I mentioned, I went with [Secret Manager](https://cloud.google.com/functions/docs/configuring/secrets) as it is the [recommended way](https://firebase.google.com/docs/functions/config-env?gen=2nd#secret-manager) for sensitive data to be stored.

**Comment by rscsam** [comment]
> > I was hitting this issue just recently and got it fixed.
> > **To circumvent it, I:**
> > 
> > 1. Opened my GCP console project, navigated to API & Services (https://console.cloud.google.com/apis/dashboard)
> > 2. Selected "Cloud Runtime Configuration API" and disabled the API. Since I'm only using Secret Manager, this API is unnecessary.
> > 
> > **firebase deploy** for whatever reason tries to reach "_[apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1..._" and fails with 500, halting the deployment.
> > Edit: There's a request quota (during deploy) that can easily be hit if you're deploying multiple functions (5+). See [documentation](https://firebase.google.com/docs/functions/manage-functions?gen=2nd#deploy_functions).
> > In these cases, they recommend deployments of only the changed functions. ex: _firebase deploy --only functions:addMessage,functions:makeUppercase_
> 
> Should I expect any downstream effects of disabling this API? I can confirm this fixes my firebase functions deployment issue, but am uneasy generally about disabling APIs that I don't understand.

After testing on a sandbox project, I can confirm disabling this API this will cause builds to fail on any project using `config` for runtime environment variables. Specifically I got:
> Error: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error

and in the debug log, the source of that error was due to
> Got response code 400; body Failed to generate manifest from function source: TypeError: Cannot read properties of undefined [...]

**Comment by ReedGraff** [comment]
> I was hitting this issue just recently and got it fixed.
> 
> **To circumvent it, I:**
> 
> 1. Opened my GCP console project, navigated to API & Services (https://console.cloud.google.com/apis/dashboard)
> 2. Selected "Cloud Runtime Configuration API" and disabled the API. Since I'm only using [Secret Manager](https://cloud.google.com/functions/docs/configuring/secrets), this API is unnecessary for me. NOTE: If you configure _config_ (v1) or _params_ (v2) values for your function (ex. require('[firebase-functions/params](https://firebase.google.com/docs/functions/config-env?gen=2nd#params)')), this API is needed and this fix won't work for your case.
> 
> **firebase deploy** for whatever reason tries to reach "_[apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1..._" and fails with 500, halting the deployment even when the project does not use config at all.
> 
> Edit: There's a request quota (during deploy) that can easily be hit if you're deploying multiple functions (5+). See [documentation](https://firebase.google.com/docs/functions/manage-functions?gen=2nd#deploy_functions).
> 
> In these cases, they recommend deployments of only the changed functions. ex: _firebase deploy --only functions:addMessage,functions:makeUppercase_

You just saved our company customers. 😅😅😅

**Comment by ahmedbahgaten** [comment]
Same

**Comment by mcarriere** [comment]
having this issue after deploying maybe 20 functions in a single deploy which i've done multiple times in the past. Now I haven't been able to deploy for a couple hours but if my coworkers try it works fine.

**Comment by ahmedbahgaten** [comment]
> having this issue after deploying maybe 20 functions in a single deploy which i've done multiple times in the past. Now I haven't been able to deploy for a couple hours but if my coworkers try it works fine.

I faced the same issue, and I had to turn on my VPN , and tried to redeploy and it worked! give it a try with a VPN turned on and I believe it will work!

**Comment by mcarriere** [comment]
> > having this issue after deploying maybe 20 functions in a single deploy which i've done multiple times in the past. Now I haven't been able to deploy for a couple hours but if my coworkers try it works fine.
> 
> I faced the same issue, and I had to turn on my VPN , and tried to redeploy and it worked! give it a try with a VPN turned on and I believe it will work!

I only managed to deploy a couple more functions before that other connection got blocked and started having the same issue

**Comment by shevvydj** [comment]
its not working for me currently either, i feel this is a google issue but they have not updated the service status

**Comment by robertuniqid** [comment]
> its not working for me currently either, i feel this is a google issue but they have not updated the service status

Same here, I've had this issue for almost 1 hour already.

**Comment by mlahp7** [comment]
> > > having this issue after deploying maybe 20 functions in a single deploy which i've done multiple times in the past. Now I haven't been able to deploy for a couple hours but if my coworkers try it works fine.
> > 
> > 
> > I faced the same issue, and I had to turn on my VPN , and tried to redeploy and it worked! give it a try with a VPN turned on and I believe it will work!
> 
> I only managed to deploy a couple more functions before that other connection got blocked and started having the same issue

This worked for me as well with a hotspot, debug logs point to a captcha error. I opened a new issue so we can hopefully get some visibility with the firebase / google team

https://github.com/firebase/firebase-tools/issues/8047

**Comment by jonnyisenberg69** [comment]
Resolved by using VPN. Really annoying - wasted an hour deleting artifacts and restarting Config API.

**Comment by stanrud** [comment]
> > having this issue after deploying maybe 20 functions in a single deploy which i've done multiple times in the past. Now I haven't been able to deploy for a couple hours but if my coworkers try it works fine.
> 
> I faced the same issue, and I had to turn on my VPN , and tried to redeploy and it worked! give it a try with a VPN turned on and I believe it will work!

Fixed for me!!! 🥳 Just connected my laptop to my phone's hotspot and it started to deploy right away.
I spent several hours trying to figure out why it wasn't working.

**Comment by vmferreira81** [comment]
> > > having this issue after deploying maybe 20 functions in a single deploy which i've done multiple times in the past. Now I haven't been able to deploy for a couple hours but if my coworkers try it works fine.
> > 
> > 
> > I faced the same issue, and I had to turn on my VPN , and tried to redeploy and it worked! give it a try with a VPN turned on and I believe it will work!
> 
> Fixed for me!!! 🥳 Just connected my laptop to my phone's hotspot and it started to deploy right away. I spent several hours trying to figure out why it wasn't working.

Just changed my wifi connection and worked! Lost a day on this!

**Comment by markcarey** [comment]
> > > > having this issue after deploying maybe 20 functions in a single deploy which i've done multiple times in the past. Now I haven't been able to deploy for a couple hours but if my coworkers try it works fine.
> > > 
> > > 
> > > I faced the same issue, and I had to turn on my VPN , and tried to redeploy and it worked! give it a try with a VPN turned on and I believe it will work!
> > 
> > 
> > Fixed for me!!! 🥳 Just connected my laptop to my phone's hotspot and it started to deploy right away. I spent several hours trying to figure out why it wasn't working.
> 
> Just changed my wifi connection and worked! Lost a day on this!

It's complete insane that this worked. Hours and hours of "Cloud Runtime is experiencing issues", and connecting via my photo's hotspot fixes it? C'mon, we are paying customers....

**Comment by nick-s5** [comment]
Using a VPN the CLI kept telling me it couldn't find my firebase project. Using my phone hotspot worked though.

**Comment by 5hee75** [comment]
Unfortunately I'm still seeing this issue, even when running from Cloud Shell.  I also tried the different connections on my laptop to no avail.

Now I'm worried I accidentally wiped my remote config values by disabling the cloud runtime config API for a brief time.  I sincerely hope not.  That allowed me to publish, but then I started getting runtime errors fetching my config values.

**Comment by HSCOGT** [comment]
Currently experiencing the same issue, changing my connection worked.

**Comment by modernlabrat** [comment]
okay so what's the issue, why can't I use my home network? please fix.

**Comment by guillermodelagala** [comment]
Same issue with firebase-tools 14.2.2

**Comment by iurisilvio** [comment]
We have same issue happening on GHA, so probably not a connectivity error.

**Comment by aalej** [comment]
Hey, for those encountering this issue again, please refer to #8936 for any updates. Our engineering team is currently looking into this.
