### ISSUE TITLE
punycode deprecation

### ISSUE THREAD

**Issue by JasonGoemaat** [firebase/firebase-tools#7476]
### [REQUIRED] Environment info

**firebase-tools: 13.13.3**

**Platform: Windows 10**

**node: 22.5.1**
### [REQUIRED] Test case

Trying to run emulator with this:

```
$ firebase --project demo-friendly-eats emulators:exec --import ./app-data-seed --ui 'ng serve'
(node:25952) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

### [REQUIRED] Steps to reproduce

Tried to run the firestore sample at [quickstart firestore](https://github.com/firebase/quickstart-js) following directions.   The npm script fails, I think it sees the deprecation as an error.   I was able to start it using the previous command manually though.

Reading up a little it seems like the punycode module has been deprecated since node 7, but changed to a runtime warning as of node 21.   I'm not sure where the node version 

### [REQUIRED] Expected behavior

Running with no errors or runtime warnings, running from npm script succeeds.

### [REQUIRED] Actual behavior

There is a red runtime warning about punycode being deprecated, and I think it is what prevents the npm script from working:

```
    "start": "npm run pre-build && firebase --project demo-friendly-eats emulators:exec --import ./app-data-seed --ui 'ng serve'",
```

**Comment by JasonGoemaat** [comment]
Took me a while, but found I could set the environment variable using `export NODE_OPTIONS=--trace-deprecation` to find what package it was coming from:

```
(node:21852) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:399:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:338:10)
    at loadBuiltinModule (node:internal/modules/helpers:96:7)
    at Module._load (node:internal/modules/cjs/loader:1070:17)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Module.require (node:internal/modules/cjs/loader:1304:12)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (C:\Users\jason\scoop\persist\nodejs\bin\node_modules\firebase-tools\node_modules\whatwg-url\lib\url-state-machine.js:2:18)
```

**Comment by aalej** [comment]
Hey @JasonGoemaat, thanks for reaching out. As you mentioned the deprecation warning you’re seeing is due to the `punycode` deprecation. At the moment, we’re working on moving all our dependencies to get rid of deprecation warnings such this. 

Also, firebase-tools currently does not officially support Node.js 22, I would recommend using Node.js 20.x since this is an LTS version. 

Lastly, to make sure we’re on the same page here, could you let me know what behavior was shown when running the command:
```
$ firebase --project demo-friendly-eats emulators:exec --import ./app-data-seed --ui 'ng serve'
```

When I tried running this locally, I encountered the deprecation warning but the emulators were able to start. Is this similar to what you observed, or did the emulators not start at all?

I’m using the following to try and reproduce the issue:

- firebase-tools: v13.13.3
- node: v22.5.1
- platform: macOS Sonoma 14.5

**Comment by aalej** [comment]
Hey @JasonGoemaat, could you try running the command below to see if you would be able to start the emulator:
```
firebase --project demo-friendly-eats emulators:exec --import ./app-data-seed --ui "ng serve"
```

It looks like the reason why the emulators were not able to start is because the command wasn’t able to correctly parse the argument `'ng serve'`.

The punycode deprecation warning might not be the cause of the issue, instead it could be related to [how cmd treats single quotes](https://stackoverflow.com/questions/51080215/differences-between-single-and-double-quotes-in-cmd/51090074#51090074).

**Comment by joehan** [comment]
Closing this since the template was fixed and this is a limitation of cmd

**Comment by alecfilios** [comment]
Any news on that?
I ge it both on emulator and on deploy

**Comment by 0wwafa** [comment]
I still see the deprecation warning using firebase-admin! @joehan @JasonGoemaat

**Comment by 0wwafa** [comment]
A simple solution is to add to package.json:

```
"overrides": {
  "whatwg-url": "13.0.0"
}
```
