### ISSUE TITLE
firebase deploy --> [DEP0040] DeprecationWarning

### ISSUE THREAD

**Issue by Abhijit-Revamp** [firebase/firebase-tools#7747]
### [REQUIRED] Environment info
**firebase-tools:** 13.19.0

**Platform:** macOS

### [REQUIRED] Test case

firebase deploy

### [REQUIRED] Steps to reproduce
firebase deploy
_(node:59297) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead._

### [REQUIRED] Expected behavior
deployment needs to happen without DeprecationWarning 

### [REQUIRED] Actual behavior
Gives DeprecationWarning

**Comment by joehan** [comment]
Hey @Abhijit-Revamp - this deprecation was done in Node 22, and will not appear if you are on Node 18/20. We're working on a fix for these warnings on Node 22, but its proving to be a long slog of upgrading (and waiting for) dependencies.

**Comment by njvb** [comment]
Hi @aalej, confirming your closure of my other ticket (7822) as it is a duplicate of this topic. Thank you!

**Comment by pranauv1** [comment]
`whatwg-url` from `node-fetch@2.x.x` is causing this warning, updating to `node-fetch@3.0.0` should solve the problem.

**Comment by Ferchu425** [comment]
Just to let you know that this issue is still alive as of 13.31.1

**Comment by joehan** [comment]
@Ferchu425 - I though I fixed this issue with https://github.com/firebase/firebase-tools/pull/8136, but it's possible I missed a spot. Could you share a minimal repro that triggers this warning on Node 22?

**Comment by Ferchu425** [comment]
Hi, went ahead a made some checks... made a new project, updated everything and ran again, it is not your fault, Im sorry, the issue seems to be related to another module now:

└─┬ eslint@8.57.1
  └─┬ ajv@6.12.6
    └─┬ uri-js@4.4.1
      └── punycode@2.3.1

Sorry again, we have this issue for a long time and the last check showed firebase, in fact surely the version you mentioned solved the dependency but we did not realice because the issue was still there...

**Comment by mkurcius** [comment]
I am was seeing this warning too, I have `firebase-tools@13.34.0` (latest at current point in time) in my devDependencies and `npm ls punycode` is not showing anything, so looks like it is not coming from firebase-tools.

I am not sure, but warning might originate from `npm` itself, bc when I updated npm to latest version: `npm i -g npm` it's now not appearing anymore. I am now on `npm@11.2.0`

**Comment by mkurcius** [comment]
FYI
I also updated node to current latest: v22.14.0
