### ISSUE TITLE
Firebase deploy fails with "Error: HTTP Error: 500, Internal error encountered."

### ISSUE THREAD

**Issue by bpaduch** [firebase/firebase-tools#865]
When deploying our site today on Travis CI, our deployment fails with the following error:

**Error: HTTP Error: 500, Internal error encountered.**

### Version info

firebase-tools@4.1.0

### Platform Information

Linux on Travis CI

Log is [here](https://travis-ci.org/ampproject/docs/jobs/415897536)

Note: The build last night that used v. 4.0.3 worked correctly.

cc: @pbakaus, @crystalfaith

**Comment by mbleigh** [comment]
We're going to need debug logs to be able to diagnose the problems here -- can you either flip on `--debug` in the CI build or alternatively make sure it is keeping `firebase-debug.log` as an artifact during failed builds?

**Comment by bpaduch** [comment]
@mbleigh - Please check out the details in https://travis-ci.org/ampproject/docs/jobs/415953980, which I hope provides the details you need.

cc: @rsimha

**Comment by rsimha** [comment]
Here are the failure logs: https://travis-ci.org/ampproject/docs/jobs/415953980#L7375-L7424

**Comment by mbleigh** [comment]
How (and when) did you generate the auth token that you're using in the CI system? Will it work if you generate a new one with `firebase login:ci`?

**Comment by rsimha** [comment]
New token generated. Build in progress: https://travis-ci.org/ampproject/docs/builds/415999283

**Comment by bpaduch** [comment]
Resolved.  Needed new auth token.

**Comment by ArtemBogush** [comment]
Just faced the same issue. Relogin/updating token didn't solve it.

here is the log: [firebase-debug.log](https://github.com/firebase/firebase-tools/files/2390414/firebase-debug.log)

Please help as we need to release an update asap to the users.

It was working yesterday but today we've updated firebase-tools to v4.3.1 (from v3.*). It works for our dev version of the project (basically a separate firebase project) but not for prod.

Please advice on possible solutions.

**Comment by Berlioz** [comment]
It's difficult to tell for sure from my standpoint, but I suspect that your issue has something to do with nonstandard IAM permissions being set on the user attempting to do the deploy. Try doing the deploy with a user that has the Editor permission on the corresponding Cloud project? If you reach out to Firebase Support and open a case referencing this issue, they'll have the accesses required to help you troubleshoot your IAM permissions in greater detail.

If that doesn't work, as a temporary workaround, you should be able to temporarily downgrade firebase-tools to a 3.x release using npm with `npm install -g firebase-tools@3.19.3` or whatever version you used to be on.

**Comment by ArtemBogush** [comment]
Thanks @Berlioz - downgrading resolved the issue for now!

Though we are looking to use function custom timeout from the code which requires firebase-tool 4+
The permission is set to "Owner" actually, though I'll file an issue to support as well.

Thanks again for he quick helpful reply!

**Comment by neer17** [comment]
Deploying functions later some time resolved my problem. This may be an internal firebase bug.

**Comment by ajayarajan** [comment]
Hi, I`m getting the following error while using FirebaseMessaging.sendAsyc 

com.google.firebase.messaging.FirebaseMessagingException: Internal error encountered.
	at com.google.firebase.messaging.FirebaseMessaging.handleSendHttpError(FirebaseMessaging.java:290)
	at com.google.firebase.messaging.FirebaseMessaging.access$600(FirebaseMessaging.java:55)
	at com.google.firebase.messaging.FirebaseMessaging$1.execute(FirebaseMessaging.java:259)
	at com.google.firebase.messaging.FirebaseMessaging$1.execute(FirebaseMessaging.java:240)
	at com.google.firebase.internal.CallableOperation.call(CallableOperation.java:36)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.api.client.http.HttpResponseException: 500 Internal Server Error
{
  "error": {
    "code": 500,
    "message": "Internal error encountered.",
    "errors": [
      {
        "message": "Internal error encountered.",
        "domain": "global",
        "reason": "backendError"
      }
    ],
    "status": "INTERNAL"
  }
}
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1070)


what could be the issue here, any response will be highly appreciated

**Comment by bkendall** [comment]
@ajayarajan This is not the appropriate venue for that question. You will find StackOverflow or the appropriate channel in the [Firebase Community](https://firebase.community) a better place.

**Comment by liron-navon** [comment]
This could be useless now, but for anyone who might visit here, in my case the hosting service was down (yea, I didn't believe google services can be brought down either ), you can see what services are down here:

https://status.firebase.google.com/

**Comment by timeworn** [comment]
yes, having same trouble now, looks like firebase is under weather :)

**Comment by robjr** [comment]
same as you @liron-navon, after trying many things to make it work, I was about to contact the support when I saw on the status page that some services were down.

**Comment by shavik** [comment]
hosting is down. but if you are deploying only functions using
**firebase deploy --only functions** will work.

**Comment by T-Knott-Mesh** [comment]
ROFL ! I'm so happy you just posted that ! Holy shit I have a beta onboarding this morning!

**Comment by StickNitro** [comment]
Same as @T-Knott-Mesh I thought I broke something, does firebase have a status page for services?

**Comment by equidevium** [comment]
Yeap firebase is down. Hard to believe that this happened.

**Comment by T-Knott-Mesh** [comment]
I can't believe it ! Hahahahaha oh well, it happens. I'm sure they are all
freaking out rn hahahaha.

**Comment by preginald** [comment]
Is there anyway I can edit code in the server instead of having to deploy? I need to fix a bug.

**Comment by lakshmi-fp** [comment]
i am also getting Error: HTTP Error: 500, Internal error encountered problem when deploying firebase deploy --only hosting

**Comment by denzdacs** [comment]
Encountering the same problem getting this error

 Error: HTTP Error: 500, Internal error encountered.

**Comment by Muhammad-Wasi** [comment]
Error: HTTP Error: 500, Internal error encountered.
Same Problem I'm facing when i hosting my project in firebase server

**Comment by CossyCossy** [comment]
how soon are they gonna be down????

**Comment by gilcreque** [comment]
Thank you for posting that it is down! I have been trying for the last 30 minutes to get this deployed through our CI.

**Comment by atomek1000** [comment]
haha i thought it was my network
Good that this site https://status.firebase.google.com/ exists

**Comment by Kobbersvard** [comment]
Haha I thought Iam fired 8-D

**Comment by Vivek-abstract** [comment]
Enjoyed reading your comments :smile: :laughing: 
You can check the current status here: https://status.firebase.google.com/incident/Hosting/19006

**Comment by CsabaSzabo** [comment]
Good to know that they have a status page, hopefully they'll fix it soon :)

https://status.firebase.google.com/incident/Hosting/19006

**Comment by Muhammad-Wasi** [comment]
its very tough time for me :-(

**Comment by denzdacs** [comment]
> Is there anyway I can edit code in the server instead of having to deploy? I need to fix a bug.

I dont think that you can do something like an ssh in firebase.

**Comment by kenara** [comment]
Yay! It's working. Had to do a 
`firebase login --reauth --no-localhost`

**Comment by denzdacs** [comment]
Mitigation is rolled out! Issue is resolved https://status.firebase.google.com/incident/Hosting/19006

**Comment by tufac2** [comment]
Same error! I have tried with several versions of firebase-tools and same problem.

I tried `firebase deploy --only functions` and it worked

**Comment by benatkin** [comment]
It hasn't been working for me for the last 20 minutes or so.

**Comment by rohitsuratekar** [comment]
I am facing same problem now, even when their website says service is normal.

**Comment by bkendall** [comment]
Thanks for the reports folks. There's a newer issue that's tied to the `500` errors today that I'd like to keep this activity on, so if you're having issues to day (August 19, 2019 - huh, almost exactly a year later for this bug), go to #1609.

We're aware and we're working on it. Sorry for the inconvenience 😕. Stay tuned to #1609 for more updates.

**Comment by benatkin** [comment]
I'm annoyed that the status page doesn't acknowledge the issue. Don't care about the reply here. Update the status page first.

Compounding the issue for me, I deleted my staging site and it wouldn't let me create a new one with the same name, even in the same project, so now I have to tell everyone to use the new URL.

**Comment by FCE-tc** [comment]
I am getting the same error when using 'firebase deploy'

`[info] +  database: rules syntax for database <my project name> is valid
[debug] [2019-08-21T14:52:22.716Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites/<my project name>/versions  

[debug] [2019-08-21T14:52:23.713Z] <<< HTTP RESPONSE 500
[debug] [2019-08-21T14:52:23.714Z] <<< HTTP RESPONSE BODY
[error] 
[error] Error: HTTP Error: 500, Internal error encountered.
[debug] [2019-08-21T14:52:23.855Z] Error Context: {
  "body": {
    "error": {
      "code": 500,
      "message": "Internal error encountered.",
      "status": "INTERNAL"
    }
  },
  "response": {
    "statusCode": 500,
    "body": {
      "error": {
        "code": 500,
        "message": "Internal error encountered.",
        "status": "INTERNAL"
      }
    },
    "headers": {
      "vary": "X-Origin, Referer, Origin,Accept-Encoding",
      "content-type": "application/json; charset=UTF-8",
      "date": "Wed, 21 Aug 2019 14:52:23 GMT",
      "server": "ESF",
      "cache-control": "private",
      "x-xss-protection": "0",
      "x-frame-options": "SAMEORIGIN",
      "x-content-type-options": "nosniff",
      "alt-svc": "quic=\":443\"; ma=2592000; v=\"46,43,39\"",
      "accept-ranges": "none",
      "transfer-encoding": "chunked"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "firebasehosting.googleapis.com",
        "port": 443,
        "hostname": "firebasehosting.googleapis.com",
        "hash": null,
        "search": null,
        "query": null,
        "pathname": "/v1beta1/sites/<my project name>/versions",
        "path": "/v1beta1/sites/<my project name>/versions",
        "href": "https://firebasehosting.googleapis.com/v1beta1/sites/<my project name>/versions"
      },
      "method": "POST"
    }
  }
}`

**Comment by piavgh** [comment]
Same here

> I am getting the same error when using 'firebase deploy'
> 
> `[info] + database: rules syntax for database is valid
> [debug] [2019-08-21T14:52:22.716Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites//versions
> 
> [debug] [2019-08-21T14:52:23.713Z] <<< HTTP RESPONSE 500
> [debug] [2019-08-21T14:52:23.714Z] <<< HTTP RESPONSE BODY
> [error]
> [error] Error: HTTP Error: 500, Internal error encountered.
> [debug] [2019-08-21T14:52:23.855Z] Error Context: {
> "body": {
> "error": {
> "code": 500,
> "message": "Internal error encountered.",
> "status": "INTERNAL"
> }
> },
> "response": {
> "statusCode": 500,
> "body": {
> "error": {
> "code": 500,
> "message": "Internal error encountered.",
> "status": "INTERNAL"
> }
> },
> "headers": {
> "vary": "X-Origin, Referer, Origin,Accept-Encoding",
> "content-type": "application/json; charset=UTF-8",
> "date": "Wed, 21 Aug 2019 14:52:23 GMT",
> "server": "ESF",
> "cache-control": "private",
> "x-xss-protection": "0",
> "x-frame-options": "SAMEORIGIN",
> "x-content-type-options": "nosniff",
> "alt-svc": "quic=":443"; ma=2592000; v="46,43,39"",
> "accept-ranges": "none",
> "transfer-encoding": "chunked"
> },
> "request": {
> "uri": {
> "protocol": "https:",
> "slashes": true,
> "auth": null,
> "host": "firebasehosting.googleapis.com",
> "port": 443,
> "hostname": "firebasehosting.googleapis.com",
> "hash": null,
> "search": null,
> "query": null,
> "pathname": "/v1beta1/sites//versions",
> "path": "/v1beta1/sites//versions",
> "href": "https://firebasehosting.googleapis.com/v1beta1/sites//versions"
> },
> "method": "POST"
> }
> }
> }`

**Comment by DarzeHub** [comment]
Same here. HTTP Error: 500

**Comment by davej** [comment]
Looks like there's a bunch of us getting a 500 in the last 30 minutes. Looks like Firebase is having an issue.

**Comment by bongartzc** [comment]
Yes I am also getting a 500 error.

**Comment by davej** [comment]
Also see #1609

**Comment by carvalhoMoreira** [comment]
Brazil is off too. Getting error HTTP 500: Internal error on deploying to firebase hosting. It started by 12:00 PM

**Comment by poleselfg** [comment]
Same here

**Comment by junaidte14** [comment]
I was getting the same error 5 minutes ago but it's working fine.

**Comment by poleselfg** [comment]
> I was getting the same error 5 minutes ago but now it's working fine.

let me try

**Comment by maxnatchanon** [comment]
Still getting 500 error here (asia-east2).

**Comment by junaidte14** [comment]
I have tested again and now I'm getting the same error. What's going on.....

**Comment by poleselfg** [comment]
> I was getting the same error 5 minutes ago but now it's working fine.

nope same here in argentina

**Comment by magnetronus** [comment]
Yes I am also getting a 500 error.

**Comment by el-yomi** [comment]
same here in Japan

**Comment by el-yomi** [comment]
I'm still getting 500 error from Japan

**Comment by junaidte14** [comment]
now it's working for me again. I guess the development team is testing the issue by enabling/disabling access to deploy.

**Comment by el-yomi** [comment]
Oh, thank you now it's working fine for me as well.

**Comment by poleselfg** [comment]
WORKING FINE NOW!

**Comment by FCE-tc** [comment]
Can confirm working again. Thanks for the fix.

**Comment by raskri** [comment]
This is happening again!

**Comment by quentin-wrnr** [comment]
Same for me, error 500 on several projects

**Comment by MrDrummer** [comment]
Seems to be back up!

**Comment by quentin-wrnr** [comment]
@MrDrummer not for me in France :/

**Comment by KappaDiElle** [comment]
happening again now for me in Italy,
but "--only functions" works well

**Comment by MrDrummer** [comment]
Seems to be working again now.

Quite ironic, as I was trying to deploy our dependencies status dashboard, which includes GCP and firebase!

**Comment by samtstern** [comment]
Hey everyone just FYI: if you get `500` errors using Firebase services you should *always* do this:

1) Check the [status dashboard](https://status.firebase.google.com) and see if it's a known incident.
2) If there's nothing there, write in to [Firebase support](https://firebase.google.com/support)

500 errors mean that the backend is experiencing an unexpected issue and GitHub is not a great place to get help with urgent issues like that, especially since none of our backend code is on GitHub.
