### ISSUE TITLE
Intermittent Developer Connect quota errors on App Hosting deploy

### ISSUE THREAD

**Issue by jhuleatt** [firebase/firebase-tools#8711]
I'm seeing Developer Connect quota errors on some App Hosting deploy attempts. Usually, waiting a minute and retrying fixes the issue. However, I'm not sure why Developer Connect is involved at all, when I'm deploying directly from source.

### [REQUIRED] Environment info

**firebase-tools:** 14.6.0

**Platform:** macOS

### [REQUIRED] Test case

1. Create an App Hosting backend with `firebase init apphosting`
1. Run `firebase deploy --only apphosting`

### [REQUIRED] Steps to reproduce

See test case. Try a few times in a row if it doesn't happen right away.

### [REQUIRED] Expected behavior

Successful deploy

### [REQUIRED] Actual behavior

```
Error: Request to https://serviceusage.googleapis.com/v1/projects/<redacted>/services/developerconnect.googleapis.com had HTTP Error: 429, Quota exceeded for quota metric 'Default requests' and limit 'Default requests per minute' of service 'serviceusage.googleapis.com' for consumer 'project_number:<redacted>'.
[2025-06-05T14:40:18.694Z] Error Context: {
  "body": {
    "error": {
      "code": 429,
      "message": "Quota exceeded for quota metric 'Default requests' and limit 'Default requests per minute' of service 'serviceusage.googleapis.com' for consumer 'project_number:<redacted>'.",
      "status": "RESOURCE_EXHAUSTED",
      "details": [
        {
          "@type": "type.googleapis.com/google.rpc.ErrorInfo",
          "reason": "RATE_LIMIT_EXCEEDED",
          "domain": "googleapis.com",
          "metadata": {
            "consumer": "projects/<redacted>",
            "quota_location": "global",
            "quota_limit_value": "600",
            "service": "serviceusage.googleapis.com",
            "quota_limit": "DefaultRequestsPerMinutePerProject",
            "quota_unit": "1/min/{project}",
            "quota_metric": "serviceusage.googleapis.com/default_requests"
          }
        },
        {
          "@type": "type.googleapis.com/google.rpc.Help",
          "links": [
            {
              "description": "Request a higher quota limit.",
              "url": "https://cloud.google.com/docs/quotas/help/request_increase"
            }
          ]
        }
      ]
    }
  },
  "response": {
    "statusCode": 429
  }
}
```

**Comment by MrRoyce** [comment]
I have also started seeing this the past few days.  It usually clears up after retrying a time or 2. Its hard to tell if this is a real quota that we can request an update for or if it is an internal GCloud bug.  The documentation on increasing quotas is all over the place.

**Comment by JulindM** [comment]
Its not just `apphosting`. Trying to deploy `functions` and just as @MrRoyce mentioned, its intermittent and trying after 2-3 times it works again.

---

One thing of note is that when I tried deploying a v2 function for the first time, I received the same error, but looking at the logs, the error was something completely different regarding the inital Eventarc setup.

```
Validation failed for trigger *******: Invalid resource state for "": Permission denied while using the Eventarc Service Agent. If you recently started to use Eventarc, it may take a few minutes before all necessary permissions are propagated to the Service Agent. Otherwise, verify that it has Eventarc Service Agent role.
```

Nevertheless trying to deploy other v2 functions afterwards after the initial eventarc setup, still lead to the intermittent quota errors.

**Comment by JeremyFrederick** [comment]
This issue started happening the past couple of weeks. I've tried restructuring my functions so I can deploy in smaller groups, but I still see this error when deploying a single function (ie. firebase deploy --only functions:functionName). This has been a major issue for me when deploying larger groups, I will almost always get 1-2 failures and have to manually go back and deploy those functions.

**Comment by Shadowstep33** [comment]
I just joined the club! In case it matters for hunting the bug, I happened to have just recently consolidated two `v1` `document.onCreate` triggers into the same one. Thusly, I had to delete the function from firebase. 

**Edit: and it indeed was fixed after trying 2-3 times**

**Comment by maciejgoscinski-latrace** [comment]
Any progress or acknowledgement on the topic on Google side?
Whenever I check the Google Cloud Console Quotas page, there's no data on the actual usage of this quota and no chart is rendered. Almost every time we run our CICD build, the first run fails and we have to retry.
This costs us additional money for running every build twice, and also puts us in a very inconvenient situation, where the deployment is not atomic, some functions are already updated to new version, and some are not.

**Comment by pradella** [comment]
I'm having the same issue while deploying functions. Started ~2 weeks ago, it happens randomly.

**Comment by maciejgoscinski-latrace** [comment]
Issue is clearly related with the 12 June Google Services outage that affected many sites downstream.
[Google Incident Report](https://status.cloud.google.com/incidents/ow5i3PPK96RduMcb1SsW)
According to the incident report "On May 29, 2025, a new feature was added to Service Control for additional quota policy checks." which combined with a later policy change on 12 June led to a huge service disruption.

**Comment by jayman2989** [comment]
Having this issue today - haven't had it since I partitioned my functions into sub files years ago, and now I only deploy a grouping of 5-10 at any given time. Long standing, bill paying GCloud account.

**Comment by ajbarry** [comment]
I am hitting this intermittently over the last few weeks while only deploying a single cloud function, ie `firebase deploy --only functions:myFunction`. If firebase-tools cli needs to make a lot of api calls to validate the environment then it seems the quotas are really tight or inappropriate for the tool itself.

**Comment by mulderpf** [comment]
I just started getting this since yesterday and the error is:
`Error: Request to https://serviceusage.googleapis.com/v1/projects/XXXXXX/services/cloudscheduler.googleapis.com had HTTP Error: 429, Quota exceeded for quota metric 'Default requests' and limit 'Default requests per minute' of service 'serviceusage.googleapis.com' for consumer 'project_number:563584335869'.`

I left the project number in there as this is the same project_number I believe that everyone is seeing, it's not mine.  (Confirmed here that others are seeing the same project number: https://www.reddit.com/r/Firebase/comments/1ldn7j3/firebase_deploy_429_quota_exceeded/ and on StackOverflow from 5 years ago

**Comment by pascal-cm** [comment]
I can confirm this issue persists and that it seems to appear randomly at any stage of a deployment (using `firebase deploy` from a local machine in my case):

```
i  extensions: ensuring required API firebaseextensions.googleapis.com is enabled...
✔  extensions: required API firebaseextensions.googleapis.com is enabled
i  functions: Loaded environment variables from .env.
i  functions: preparing functions directory for uploading...
i  functions: packaged /.../firebase/functions (52.82 KB) for uploading
i  functions: ensuring required API identitytoolkit.googleapis.com is enabled...

Error: Request to https://serviceusage.googleapis.com/v1/projects/.../services/identitytoolkit.googleapis.com had HTTP Error: 429, Quota exceeded for quota metric 'Default requests' and limit 'Default requests per minute' of service 'serviceusage.googleapis.com' for consumer 'project_number:563584335869'.
```

What we ([redditors](https://www.reddit.com/r/Firebase/comments/1ldn7j3/firebase_deploy_429_quota_exceeded/)) conclude is that it's always the same project number, **563584335869**, which is not one of our projects and thus has nothing to do with our own quota, i.e. how we use Firebase CLI commands or how many services we call in what time.

As of writing, I surmise from comments on reddit, it may well happen for deployments of individual functions.

Leaving this with you @inlined and @taeold.

I will post detailed and sanitized logs should I encounter this error again.

**Comment by salvia34** [comment]
> I can confirm this issue persists and that it seems to appear randomly at any stage of a deployment (using `firebase deploy` from a local machine in my case):
> 
> ```
> i  extensions: ensuring required API firebaseextensions.googleapis.com is enabled...
> ✔  extensions: required API firebaseextensions.googleapis.com is enabled
> i  functions: Loaded environment variables from .env.
> i  functions: preparing functions directory for uploading...
> i  functions: packaged /.../firebase/functions (52.82 KB) for uploading
> i  functions: ensuring required API identitytoolkit.googleapis.com is enabled...
> 
> Error: Request to https://serviceusage.googleapis.com/v1/projects/.../services/identitytoolkit.googleapis.com had HTTP Error: 429, Quota exceeded for quota metric 'Default requests' and limit 'Default requests per minute' of service 'serviceusage.googleapis.com' for consumer 'project_number:563584335869'.
> ```
> 
> What we ([redditors](https://www.reddit.com/r/Firebase/comments/1ldn7j3/firebase_deploy_429_quota_exceeded/)) conclude is that it's always the same project number, **563584335869**, which is not one of our projects and thus has nothing to do with our own quota, i.e. how we use Firebase CLI commands or how many services we call in what time.
> 
> As of writing, I surmise from comments on reddit, it may well happen for deployments of individual functions.
> 
> Leaving this with you [@inlined](https://github.com/inlined) and [@taeold](https://github.com/taeold).
> 
> I will post detailed and sanitized logs should I encounter this error again.

Same problem here today.

**Comment by patternpaul** [comment]
Searching the code for that project ID shows that it's the default Client ID being used for the CLI. I am going to try cutting my own to see if it resolves the issue long term.

Just taking a wild stab though

**Comment by joehan** [comment]
Hey all, sorry for the issues here. As some of yall have noticed, this call is being made against the quota of the shared CLI Oauth project. We'll have a fix going out in the next release to use the customer project instead, which should fix this issue.

**Comment by MrRoyce** [comment]
Thanks @joehan   

Can you give more information on this quota?  Is this something new or was it in place before?  What is the amount allowed on the free plan?  How long is it for, an hour, a day, etc. 

Thanks!

**Comment by jantorestolsvik** [comment]
Hi, I have updated to the latest version 15.3.1 and this is still an issue for me.

**Comment by T-P-F** [comment]
Also still seeing this periodically with 15.5.1. project_number:563584335869 is still being used internally despite what @joehan said above about a fix.

**Comment by pradella** [comment]
> Also still seeing this periodically with 15.5.1. project_number:563584335869 is still being used internally despite what [@joehan](https://github.com/joehan) said above about a fix.

Happened twice last week, but I was able to deploy on the 2nd try

**Comment by T-P-F** [comment]
See this open issue: https://github.com/firebase/firebase-tools/issues/9879#issuecomment-3871588425

**Comment by joehan** [comment]
Hey all, apologies that this is still happening. The fix for this (which moves quota usage to your project instead of the project with the OAuth app used by firebase login) will be included in this week's release of the CLI, 15.6.0.

I know this sounds quite similar to my last message - we applied this change only to select APIs to be safe, and the upcoming version will cover the cloud billing APIs which have been causing some issues lately
