### ISSUE TITLE
Node 24 warning

### ISSUE THREAD

**Issue by Smrtnyk** [firebase/firebase-tools#9422]
I have moved to node 24 since it is an lts now
but I get this warning when installing firebase-tools
```text
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'superstatic@9.2.0',
npm warn EBADENGINE   required: { node: '18 || 20 || 22' },
npm warn EBADENGINE   current: { node: 'v24.11.0', npm: '11.6.2' }
npm warn EBADENGINE }
```
Can it be fixed?

**Comment by KingDarBoja** [comment]
~~Shall be fixed by https://github.com/firebase/superstatic/pull/493~~

EDIT: Superstatic v10 already supports Node 24 and this PR https://github.com/firebase/firebase-tools/pull/8565 is missing that thing.

**Comment by maxratajczak** [comment]
There's a PR open to add support for Node 24 but it seems like the PR has been abandoned and no one is working on it anymore...

https://github.com/firebase/firebase-tools/pull/8565

**Comment by aalej** [comment]
Hey folks, we're working on adding support for Node 24 on firebase-tools and we are planning on including it in our next major release(v15), which is tentatively scheduled on the 2nd or 3rd week of November.

**Comment by joehan** [comment]
Hey all, this should be fixed in today's minor version release by https://github.com/firebase/firebase-tools/pull/8565

I had been planning to roll this into the upcoming major verison, but there's really no need to given that it is not a breaking change.

**Comment by kdawgwilk** [comment]
Still getting this error when trying to run the emulators on latest `firebase-tools` version so Node 24 support is still not complete
```
⬢  functions: Failed to load function definition from source: FirebaseError: Detected node engine 24 in package.json, which is not a supported version. Valid versions are 20, 22
```

**Comment by maxratajczak** [comment]
> Still getting this error when trying to run the emulators on latest `firebase-tools` version so Node 24 support is still not complete
> ```
> ⬢  functions: Failed to load function definition from source: FirebaseError: Detected node engine 24 in package.json, which is not a supported version. Valid versions are 20, 22
> ```

Same here I get this too

**Comment by kdawgwilk** [comment]
Looks like it also needs to be added here 
https://github.com/firebase/firebase-tools/blob/d68aa330c486eca9a31b358c1e4545d4c3dd1857/src/deploy/functions/runtimes/supported/types.ts#L86-L91

**Comment by kdawgwilk** [comment]
Good news, I was able to run functions in the emulators locally with NodeJS 24 after #9475 merged and was released in 14.26.0 🎉
